const MODULE_CATALOG = [
  // ── Dashboard ──────────────────────────────────────────────────────────────
  {
    tab: "Dashboard",
    slug: "admin",
    name: "Admin Dashboard",
    description: "Admin panel and operational controls",
    icon: "dashboard",
    order: 1,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin",
  },

  // ── Catalog Management ────────────────────────────────────────────────────
  {
    tab: "Catalog Management",
    slug: "products",
    name: "Product Management",
    description: "Product catalog, moderation, and seller products",
    icon: "box",
    order: 2,
    forPlatform: true,
    forSeller: true,
    apiPath: "/products",
  },
  {
    tab: "Catalog Management",
    slug: "platform",
    name: "Platform Catalog",
    description: "Shared platform catalog controls not covered by a dedicated management module",
    icon: "settings",
    order: 3,
    forPlatform: true,
    forSeller: false,
    apiPath: "/platform",
  },
  {
    tab: "Catalog Management",
    slug: "categories",
    name: "Category Management",
    description: "Category tree and category attributes",
    icon: "folder-tree",
    order: 3.1,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/platform/categories",
    apiAliases: ["/platform/categories", "/admin/categories"],
  },
  {
    tab: "Catalog Management",
    slug: "sub_categories",
    name: "Sub Category Management",
    description: "Second-level category administration",
    icon: "folder",
    order: 3.2,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/platform/categories",
  },
  {
    tab: "Catalog Management",
    slug: "sub_sub_categories",
    name: "Sub Sub Category Management",
    description: "Third-level category administration",
    icon: "folder-open",
    order: 3.3,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/platform/categories",
  },
  {
    tab: "Catalog Management",
    slug: "brands",
    name: "Brand Management",
    description: "Brand catalog management",
    icon: "badge",
    order: 3.4,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/platform/brands",
    apiAliases: ["/platform/brands"],
  },
  {
    tab: "Catalog Management",
    slug: "option_masters",
    name: "Option Master Management",
    description: "Product option master definitions",
    icon: "settings-2",
    order: 3.5,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/platform/product-options",
    apiAliases: ["/platform/product-options"],
  },
  {
    tab: "Catalog Management",
    slug: "option_values",
    name: "Option Value Management",
    description: "Product option values",
    icon: "list",
    order: 3.6,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/platform/product-option-values",
    apiAliases: ["/platform/product-option-values"],
  },
  {
    tab: "Catalog Management",
    slug: "warranty",
    name: "Warranty Management",
    description: "Warranty templates, registration, and claims",
    icon: "badge-check",
    order: 3.7,
    forPlatform: true,
    forSeller: false,
    apiPath: "/warranty",
  },
  {
    tab: "Catalog Management",
    slug: "reviews",
    name: "Review & Rating Management",
    description: "Product reviews and ratings moderation",
    icon: "star",
    order: 3.8,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/platform/product-reviews",
    apiAliases: ["/platform/product-reviews"],
  },

  // ── Inventory Management ──────────────────────────────────────────────────
  {
    tab: "Inventory Management",
    slug: "inventory",
    name: "Inventory Management",
    description: "Stock levels, variant inventory, adjustments, and warehouses",
    icon: "warehouse",
    order: 4,
    forPlatform: true,
    forSeller: true,
    apiPath: "/inventory",
  },

  // ── Orders Management ─────────────────────────────────────────────────────
  {
    tab: "Orders Management",
    slug: "orders",
    name: "Order Management",
    description: "Orders, seller orders, cancellations, and status updates",
    icon: "shopping-cart",
    order: 5,
    forPlatform: true,
    forSeller: true,
    apiPath: "/orders",
  },
  {
    tab: "Orders Management",
    slug: "cancellations",
    name: "Cancellation Management",
    description: "Order cancellations, retry, and manual refund resolution",
    icon: "x-circle",
    order: 5.5,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/cancellations",
    apiAliases: ["/cancellations"],
  },
  {
    tab: "Orders Management",
    slug: "returns",
    name: "Return Management",
    description: "Returns, refunds, and reverse logistics",
    icon: "undo",
    order: 6,
    forPlatform: true,
    forSeller: true,
    apiPath: "/returns",
  },
  {
    tab: "Orders Management",
    slug: "payments",
    name: "Payment Management",
    description: "Payments, refunds, and payment operations",
    icon: "credit-card",
    order: 7,
    forPlatform: true,
    forSeller: false,
    apiPath: "/payments",
  },
  {
    tab: "Orders Management",
    slug: "cod-config",
    name: "COD Configuration",
    description: "Cash on delivery rules, charges, and eligibility settings",
    icon: "truck",
    order: 7.1,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/payments/admin/cod-config",
  },
  {
    tab: "Orders Management",
    slug: "chargebacks",
    name: "Chargeback Management",
    description: "Payment chargebacks and dispute resolution",
    icon: "alert-circle",
    order: 7.2,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/chargebacks",
  },
  {
    tab: "Orders Management",
    slug: "wallets",
    name: "Wallet Management",
    description: "Wallet balances and wallet transactions",
    icon: "wallet",
    order: 8,
    forPlatform: true,
    forSeller: false,
    apiPath: "/wallets",
  },
  {
    tab: "Orders Management",
    slug: "wallet-management",
    name: "Wallet Admin",
    description: "Customer wallet balances, credits, debits, and transaction audit",
    icon: "wallet",
    order: 8.1,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/wallets",
    apiAliases: ["/wallet/admin/transactions"],
  },
  {
    tab: "Orders Management",
    slug: "carts",
    name: "Cart Management",
    description: "Shopping carts and checkout baskets",
    icon: "shopping-bag",
    order: 9,
    forPlatform: true,
    forSeller: false,
    apiPath: "/carts",
  },
  {
    tab: "Orders Management",
    slug: "subscriptions",
    name: "Subscription Management",
    description: "Plans, subscriptions, and platform fees",
    icon: "repeat",
    order: 10,
    forPlatform: true,
    forSeller: false,
    apiPath: "/subscriptions",
  },
  {
    tab: "Orders Management",
    slug: "subscription-plans",
    name: "Subscription Plan Management",
    description: "Platform subscription plans and plan configuration",
    icon: "layers",
    order: 10.1,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/platform/subscription-plans",
    apiAliases: ["/platform/subscription-plans"],
  },

  // ── Users & Access ────────────────────────────────────────────────────────
  {
    tab: "Users & Access",
    slug: "admin_users",
    name: "Admin/Sub Admin Management",
    description: "Admin users, sub-admins, and delegated staff accounts",
    icon: "user-cog",
    order: 10.5,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/admin-users",
    apiAliases: ["/admin/access/sub-admins", "/admin/access/admins"],
  },
  {
    tab: "Users & Access",
    slug: "rbac",
    name: "RBAC Management",
    description: "Roles, permissions, and access assignments",
    icon: "shield",
    order: 11,
    forPlatform: true,
    forSeller: false,
    apiPath: "/rbac",
  },
  {
    tab: "Users & Access",
    slug: "users",
    name: "User Management",
    description: "Customer accounts, profiles, and KYC",
    icon: "user",
    order: 12,
    forPlatform: true,
    forSeller: false,
    apiPath: "/users",
  },
  {
    tab: "Users & Access",
    slug: "sellers",
    name: "Seller Management",
    description: "Seller onboarding, profiles, and sub-admins",
    icon: "store",
    order: 13,
    forPlatform: true,
    forSeller: true,
    apiPath: "/sellers",
  },
  {
    tab: "Users & Access",
    slug: "seller_kyc",
    name: "Seller KYC Management",
    description: "Seller KYC review and verification",
    icon: "clipboard-check",
    order: 13.1,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/sellers/:sellerId/kyc",
  },
  {
    tab: "Users & Access",
    slug: "seller_bank",
    name: "Seller Bank Management",
    description: "Seller bank verification and payout readiness",
    icon: "banknote",
    order: 13.2,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/sellers/:sellerId/bank",
  },
  {
    tab: "Users & Access",
    slug: "sellers/commissions",
    name: "Seller Commission Management",
    description: "Seller commissions, settlements, and payouts",
    icon: "percent",
    order: 14,
    forPlatform: true,
    forSeller: true,
    apiPath: "/sellers/commissions",
  },
  {
    tab: "Users & Access",
    slug: "seller-payouts",
    name: "Seller Payout Management",
    description: "Seller payout batches, approvals, and settlement tracking",
    icon: "send",
    order: 14.1,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/payouts",
  },

  // ── Marketing ─────────────────────────────────────────────────────────────
  {
    tab: "Marketing",
    slug: "coupons",
    name: "Coupon Management",
    description: "Coupons and discount codes",
    icon: "ticket",
    order: 14.5,
    forPlatform: true,
    forSeller: true,
    apiPath: "/coupons",
    apiAliases: ["/admin/pricing/coupons"],
  },
  {
    tab: "Marketing",
    slug: "pricing",
    name: "Pricing & Promotions",
    description: "Coupons, discounts, campaign pricing, and promotion controls",
    icon: "tag",
    order: 15,
    forPlatform: true,
    forSeller: true,
    apiPath: "/pricing",
  },
  {
    tab: "Marketing",
    slug: "dynamic-pricing",
    name: "Dynamic Pricing",
    description: "Dynamic pricing rules and price adjustments",
    icon: "activity",
    order: 16,
    forPlatform: true,
    forSeller: false,
    apiPath: "/dynamic-pricing",
  },
  {
    tab: "Marketing",
    slug: "referral",
    name: "Referral Commerce",
    description: "Influencers, referral codes, commission rules, and payouts",
    icon: "share-2",
    order: 17,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/referral",
  },
  {
    tab: "Marketing",
    slug: "influencer-management",
    name: "Influencer Management",
    description: "Influencer profiles, promotion links, and payout status",
    icon: "users",
    order: 17.1,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/referral/influencers",
  },
  {
    tab: "Marketing",
    slug: "loyalty",
    name: "Loyalty Management",
    description: "Loyalty points and customer rewards",
    icon: "gift",
    order: 18,
    forPlatform: true,
    forSeller: false,
    apiPath: "/loyalty",
  },
  {
    tab: "Marketing",
    slug: "recommendations",
    name: "Recommendation Management",
    description: "Related products, cross-sell, up-sell, and personalization",
    icon: "sparkles",
    order: 19,
    forPlatform: true,
    forSeller: false,
    apiPath: "/recommendations",
  },
  {
    tab: "Marketing",
    slug: "banners",
    name: "Banner Management",
    description: "Promotion banners and campaign media",
    icon: "image",
    order: 19.5,
    forPlatform: true,
    forSeller: false,
    apiPath: "/pricing/promotion-banners",
    apiAliases: ["/admin/pricing/promotion-banners"],
  },
  {
    tab: "Marketing",
    slug: "deals",
    name: "Deal Management",
    description: "Flash deals, sponsored placements, deal payouts, and sponsorships",
    icon: "zap",
    order: 19.8,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/deals",
    apiAliases: ["/deals"],
  },
  {
    tab: "Marketing",
    slug: "notifications",
    name: "Notification Management",
    description: "Notifications and communication preferences",
    icon: "bell",
    order: 20,
    forPlatform: true,
    forSeller: true,
    apiPath: "/notifications",
  },
  {
    tab: "Marketing",
    slug: "notification-templates",
    name: "Notification Templates",
    description: "Email, SMS, and push notification templates",
    icon: "mail",
    order: 20.1,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/notifications",
  },

  // ── Tax & Compliance ──────────────────────────────────────────────────────
  {
    tab: "Tax & Compliance",
    slug: "tax",
    name: "Tax Management",
    description: "Tax invoices, HSN codes, GST, tax reports, and filings",
    icon: "receipt",
    order: 21,
    forPlatform: true,
    forSeller: false,
    apiPath: "/tax",
  },
  {
    tab: "Tax & Compliance",
    slug: "tax-invoices",
    name: "Tax Invoice Management",
    description: "GST tax invoices generated from orders",
    icon: "file-text",
    order: 21.1,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/tax/invoices",
  },
  {
    tab: "Tax & Compliance",
    slug: "credit-notes",
    name: "Credit Note Management",
    description: "Tax credit notes issued on refunds and returns",
    icon: "file-minus",
    order: 21.2,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/tax/credit-notes",
  },

  // ── Delivery & Shipping ───────────────────────────────────────────────────
  {
    tab: "Delivery & Shipping",
    slug: "delivery",
    name: "Delivery Management",
    description: "Delivery serviceability, shipping rules, manifests, and tracking",
    icon: "truck",
    order: 22,
    forPlatform: true,
    forSeller: true,
    apiPath: "/delivery",
  },

  // ── Reports & Analytics ───────────────────────────────────────────────────
  {
    tab: "Reports & Analytics",
    slug: "analytics",
    name: "Analytics",
    description: "Sales, product, inventory, and seller analytics",
    icon: "chart",
    order: 24,
    forPlatform: true,
    forSeller: true,
    apiPath: "/analytics",
  },
  {
    tab: "Reports & Analytics",
    slug: "reports",
    name: "Report Management",
    description: "Operational reports and analytics dashboards",
    icon: "bar-chart",
    order: 24.1,
    forPlatform: true,
    forSeller: true,
    apiPath: "/admin/reports",
    apiAliases: ["/admin/analytics", "/analytics"],
  },
  {
    tab: "Reports & Analytics",
    slug: "analytics-events",
    name: "Analytics Events",
    description: "Raw event stream: views, clicks, cart adds, purchases",
    icon: "activity",
    order: 24.2,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/analytics",
    apiAliases: ["/analytics/events"],
  },

  // ── Location Management ───────────────────────────────────────────────────
  {
    tab: "Location Management",
    slug: "countries",
    name: "Country Management",
    description: "Country master data",
    icon: "globe",
    order: 24.5,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/common/countries",
    apiAliases: ["/common/countries"],
  },
  {
    tab: "Location Management",
    slug: "states",
    name: "State Management",
    description: "State master data, scoped to countries",
    icon: "map",
    order: 24.6,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/common/states",
    apiAliases: ["/common/states"],
  },
  {
    tab: "Location Management",
    slug: "cities",
    name: "City Management",
    description: "City master data, scoped to countries and states",
    icon: "building",
    order: 24.7,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/common/cities",
    apiAliases: ["/common/cities"],
  },
  {
    tab: "Location Management",
    slug: "zip_codes",
    name: "Zip Code Management",
    description: "Zip/pin codes, serviceability, and local delivery metadata",
    icon: "map-pin",
    order: 24.8,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/common/zip-codes",
    apiAliases: ["/common/zip-codes"],
  },

  // ── Settings ──────────────────────────────────────────────────────────────
  {
    tab: "Settings",
    slug: "cms_pages",
    name: "CMS/Page Management",
    description: "Content pages, FAQs, and policies",
    icon: "file",
    order: 24.9,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/cms",
    apiAliases: ["/cms"],
  },
  {
    tab: "Settings",
    slug: "cms",
    name: "CMS Management",
    description: "Banners, content pages, FAQs, and policies",
    icon: "file-text",
    order: 25,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/cms",
    apiAliases: ["/cms", "/pricing/promotion-banners"],
  },
  {
    tab: "Settings",
    slug: "fraud",
    name: "Fraud Management",
    description: "Fraud detection and risk review",
    icon: "alert-triangle",
    order: 26,
    forPlatform: true,
    forSeller: false,
    apiPath: "/fraud",
  },
  {
    tab: "Settings",
    slug: "api-keys",
    name: "API Key Management",
    description: "Platform API keys and third-party integration credentials",
    icon: "key",
    order: 27,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/platform/api-keys",
  },
  {
    tab: "Settings",
    slug: "feature-flags",
    name: "Feature Flags",
    description: "Runtime feature toggles for platform capabilities",
    icon: "toggle-right",
    order: 27.1,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/platform/feature-flags",
  },
  {
    tab: "Settings",
    slug: "webhooks",
    name: "Webhook Management",
    description: "Outbound webhook endpoints and delivery logs",
    icon: "rss",
    order: 27.2,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/platform/webhooks",
  },
  {
    tab: "Settings",
    slug: "system-health",
    name: "System Health",
    description: "Service health checks, uptime status, and dependency pings",
    icon: "activity",
    order: 28,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/system/health",
  },
  {
    tab: "Settings",
    slug: "queue-management",
    name: "Queue Management",
    description: "BullMQ job queues — pause, resume, and inspect",
    icon: "list",
    order: 28.1,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/system/queues",
  },
  {
    tab: "Settings",
    slug: "dead-letter-queue",
    name: "Dead Letter Queue",
    description: "Failed event retry and discard from the dead-letter store",
    icon: "alert-triangle",
    order: 28.2,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/system/dead-letter",
  },
];

const DEFAULT_PLATFORM_MODULES = MODULE_CATALOG.filter(
  (m) => m.forPlatform !== false
).map((m) => m.slug);

const DEFAULT_SELLER_MODULES = MODULE_CATALOG.filter(
  (m) => m.forSeller === true
).map((m) => m.slug);

const API_MODULES = ["auth", ...MODULE_CATALOG.map((m) => m.slug), "meta"];

const MODULE_CATALOG_BY_SLUG = new Map(MODULE_CATALOG.map((m) => [m.slug, m]));

function getModuleCatalogItem(slug) {
  return MODULE_CATALOG_BY_SLUG.get(slug) || null;
}

function groupModuleCatalogByTab(modules = MODULE_CATALOG) {
  return modules.reduce((tabs, module) => {
    let tab = tabs.find((t) => t.tab === module.tab);
    if (!tab) { tab = { tab: module.tab, modules: [] }; tabs.push(tab); }
    tab.modules.push(module);
    return tabs;
  }, []);
}

module.exports = {
  MODULE_CATALOG,
  DEFAULT_PLATFORM_MODULES,
  DEFAULT_SELLER_MODULES,
  API_MODULES,
  getModuleCatalogItem,
  groupModuleCatalogByTab,
};
