'use strict';

/**
 * Brands Seed Module
 * Populates PlatformBrand (platformbrands collection)
 * 1000+ real brands: Global, Indian, Private Labels, Marketplace
 */

const mongoose = require('mongoose');
const SeedLogger = require('../utils/seed-logger');

const slugify = (str) => str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

// Format: [name, categories, type, founded, origin]
const BRANDS_RAW = [
  // MOBILE & ELECTRONICS
  ['Apple','electronics,computers,smartwatches,tv-audio','global',1976,'US'],
  ['Samsung','electronics,computers,tv-audio,appliances','global',1938,'KR'],
  ['OnePlus','electronics,tv-audio','global',2013,'CN'],
  ['Xiaomi','electronics,tv-audio,smartwatches','global',2010,'CN'],
  ['Realme','electronics,smartwatches','global',2018,'CN'],
  ['Oppo','electronics,smartwatches','global',2001,'CN'],
  ['Vivo','electronics,smartwatches','global',2009,'CN'],
  ['Google','electronics,computers','global',1998,'US'],
  ['Nokia','electronics','global',1865,'FI'],
  ['Motorola','electronics','global',1928,'US'],
  ['Nothing','electronics,earphones','global',2020,'UK'],
  ['iQOO','electronics','global',2019,'CN'],
  ['Poco','electronics','global',2018,'CN'],
  ['Tecno','electronics','global',2006,'CN'],
  ['Infinix','electronics','global',2013,'CN'],
  ['Lava','electronics','indian',2009,'IN'],
  ['Micromax','electronics','indian',2000,'IN'],
  ['Itel','electronics','global',2007,'CN'],
  ['Honor','electronics,smartwatches','global',2013,'CN'],
  ['Huawei','electronics,computers','global',1987,'CN'],
  ['Sony','electronics,tv-audio,cameras-photo','global',1946,'JP'],
  ['LG','electronics,tv-audio,appliances','global',1958,'KR'],
  // LAPTOPS/COMPUTERS
  ['Dell','computers','global',1984,'US'],
  ['HP','computers,printers','global',1939,'US'],
  ['Lenovo','computers,electronics','global',1984,'CN'],
  ['Asus','computers,gaming','global',1989,'TW'],
  ['Acer','computers,gaming','global',1976,'TW'],
  ['MSI','computers,gaming','global',1986,'TW'],
  ['Gigabyte','computers,gaming','global',1986,'TW'],
  ['Razer','computers,gaming','global',2005,'US'],
  ['Microsoft','computers','global',1975,'US'],
  ['Toshiba','computers,appliances','global',1875,'JP'],
  ['Vaio','computers','global',2014,'JP'],
  ['Avita','computers','indian',2015,'IN'],
  // TV & AUDIO
  ['TCL','tv-audio','global',1981,'CN'],
  ['Hisense','tv-audio,appliances','global',1969,'CN'],
  ['Panasonic','tv-audio,appliances,cameras-photo','global',1918,'JP'],
  ['Vu','tv-audio','indian',2006,'IN'],
  ['Onida','tv-audio,appliances','indian',1981,'IN'],
  ['Haier','tv-audio,appliances','global',1984,'CN'],
  ['iFFALCON','tv-audio','global',2017,'CN'],
  ['Bose','tv-audio,earphones','global',1964,'US'],
  ['JBL','tv-audio,earphones','global',1946,'US'],
  ['Sennheiser','earphones','global',1945,'DE'],
  ['boAt','earphones,smartwatches','indian',2016,'IN'],
  ['Noise','earphones,smartwatches','indian',2014,'IN'],
  ['Jabra','earphones','global',1869,'DK'],
  ['Skullcandy','earphones','global',2003,'US'],
  ['Marshall','tv-audio,earphones','global',1962,'UK'],
  ['Harman Kardon','tv-audio,earphones','global',1953,'US'],
  ['Anker Soundcore','earphones','global',2011,'CN'],
  ['Beats','earphones','global',2006,'US'],
  ['Bang & Olufsen','tv-audio,earphones','global',1925,'DK'],
  ['AKG','earphones','global',1947,'AT'],
  ['Audio-Technica','earphones','global',1962,'JP'],
  ['Philips','tv-audio,appliances,health-wellness','global',1891,'NL'],
  ['Creative','tv-audio,earphones','global',1981,'SG'],
  ['Edifier','tv-audio,earphones','global',1996,'CN'],
  ['Klipsch','tv-audio','global',1946,'US'],
  // SMARTWATCHES & WEARABLES
  ['Garmin','smartwatches','global',1989,'US'],
  ['Fitbit','smartwatches','global',2007,'US'],
  ['Amazfit','smartwatches','global',2015,'CN'],
  ['Fire-Boltt','smartwatches','indian',2015,'IN'],
  ['Fossil','smartwatches,watches','global',1984,'US'],
  ['Michael Kors','smartwatches,watches,womens-fashion','global',1981,'US'],
  ['Fastrack','watches,mens-fashion','indian',1998,'IN'],
  ['Titan','watches','indian',1984,'IN'],
  ['Sonata','watches','indian',1997,'IN'],
  ['Casio','watches','global',1946,'JP'],
  ['Seiko','watches','global',1881,'JP'],
  ['Citizen','watches','global',1918,'JP'],
  ['Omega','watches','global',1848,'CH'],
  ['Rolex','watches','global',1905,'CH'],
  ['Tissot','watches','global',1853,'CH'],
  ['Timex','watches','global',1854,'US'],
  // MEN'S FASHION
  ['Allen Solly','mens-fashion,womens-fashion','global',1744,'UK'],
  ['Van Heusen','mens-fashion','global',1881,'US'],
  ['Arrow','mens-fashion','global',1851,'US'],
  ['Park Avenue','mens-fashion','indian',1987,'IN'],
  ['Blackberrys','mens-fashion','indian',1991,'IN'],
  ['Louis Philippe','mens-fashion','global',1885,'FR'],
  ['Raymond','mens-fashion,ethnic-traditional','indian',1925,'IN'],
  ['Peter England','mens-fashion','global',1889,'IE'],
  ['Colorplus','mens-fashion','indian',1993,'IN'],
  ['Tommy Hilfiger','mens-fashion,womens-fashion','global',1985,'US'],
  ['Calvin Klein','mens-fashion,womens-fashion,lingerie','global',1968,'US'],
  ['Ralph Lauren','mens-fashion,womens-fashion','global',1967,'US'],
  ['Lacoste','mens-fashion,footwear','global',1933,'FR'],
  ['Hugo Boss','mens-fashion,womens-fashion','global',1924,'DE'],
  ['Armani Exchange','mens-fashion,womens-fashion','global',1991,'IT'],
  ['Guess','mens-fashion,womens-fashion,bags-luggage','global',1981,'US'],
  ['Diesel','mens-fashion,womens-fashion','global',1978,'IT'],
  ["Levi's",'mens-fashion,womens-fashion','global',1853,'US'],
  ['Lee','mens-fashion,womens-fashion','global',1889,'US'],
  ['Wrangler','mens-fashion','global',1947,'US'],
  ['Jack & Jones','mens-fashion','global',1990,'DK'],
  ['Celio','mens-fashion','global',1978,'FR'],
  ['Zara','mens-fashion,womens-fashion','global',1975,'ES'],
  ['H&M','mens-fashion,womens-fashion,kids-fashion','global',1947,'SE'],
  ['United Colors of Benetton','mens-fashion,womens-fashion,kids-fashion','global',1965,'IT'],
  ['US Polo Assn','mens-fashion','global',1890,'US'],
  ['Pepe Jeans','mens-fashion,womens-fashion','global',1973,'UK'],
  ['Manyavar','mens-fashion,ethnic-traditional','indian',1999,'IN'],
  ['Fabindia','ethnic-traditional,mens-fashion,womens-fashion','indian',1960,'IN'],
  ['Being Human','mens-fashion','indian',2012,'IN'],
  ['Spykar','mens-fashion','indian',1992,'IN'],
  ['Killer Jeans','mens-fashion','indian',1989,'IN'],
  ['Roadster','mens-fashion','marketplace',2012,'IN'],
  ['HRX','mens-fashion,sports','indian',2013,'IN'],
  // WOMEN'S FASHION
  ['W','womens-fashion','indian',2001,'IN'],
  ['Aurelia','womens-fashion,ethnic-traditional','indian',2008,'IN'],
  ['Biba','womens-fashion,ethnic-traditional','indian',1988,'IN'],
  ['Global Desi','womens-fashion','indian',2007,'IN'],
  ['AND','womens-fashion','indian',2007,'IN'],
  ['Rangmanch','womens-fashion,ethnic-traditional','indian',2009,'IN'],
  ['Anouk','womens-fashion','marketplace',2012,'IN'],
  ['Soch','womens-fashion,ethnic-traditional','indian',2004,'IN'],
  ['INDYA','womens-fashion,ethnic-traditional','indian',2014,'IN'],
  ['ONLY','womens-fashion','global',1995,'DK'],
  ['Vero Moda','womens-fashion','global',1987,'DK'],
  ['Forever 21','womens-fashion','global',1984,'US'],
  ['Mango','womens-fashion','global',1984,'ES'],
  ['Marks & Spencer','mens-fashion,womens-fashion','global',1884,'UK'],
  ['GAP','mens-fashion,womens-fashion','global',1969,'US'],
  ['Meena Bazaar','womens-fashion,ethnic-traditional','indian',1970,'IN'],
  ['Karigari','womens-fashion,ethnic-traditional','indian',2010,'IN'],
  // SPORTS & ACTIVEWEAR
  ['Nike','sports,footwear,mens-fashion,womens-fashion','global',1964,'US'],
  ['Adidas','sports,footwear,mens-fashion,womens-fashion','global',1949,'DE'],
  ['Puma','sports,footwear,mens-fashion','global',1948,'DE'],
  ['Reebok','sports,footwear','global',1958,'UK'],
  ['Under Armour','sports','global',1996,'US'],
  ['New Balance','sports,footwear','global',1906,'US'],
  ['ASICS','sports,footwear','global',1949,'JP'],
  ['Fila','sports,footwear','global',1911,'IT'],
  ['Kappa','sports','global',1967,'IT'],
  ['Lotto','sports,footwear','global',1973,'IT'],
  ['Decathlon','sports','global',1976,'FR'],
  ['Yonex','sports','global',1946,'JP'],
  ['Wilson','sports','global',1913,'US'],
  ['Babolat','sports','global',1875,'FR'],
  ['Head','sports','global',1950,'AU'],
  ['SG Cricket','sports','indian',1931,'IN'],
  ['SS Cricket','sports','indian',1996,'IN'],
  ['GM Cricket','sports','global',1890,'UK'],
  ['Kookaburra','sports','global',1890,'AU'],
  ['Cosco','sports','indian',1980,'IN'],
  ['Nivia','sports','indian',1934,'IN'],
  ['Li-Ning','sports,footwear','global',1990,'CN'],
  ['Carlton','sports','global',1952,'UK'],
  ['Victor','sports','global',1968,'TW'],
  ['Mayor Sports','sports','indian',1998,'IN'],
  ['Strauss','sports','indian',2009,'IN'],
  // FOOTWEAR
  ['Bata','footwear','global',1894,'CZ'],
  ['Woodland','footwear,mens-fashion','indian',1992,'IN'],
  ['Campus','footwear','indian',1983,'IN'],
  ['Action Shoes','footwear','indian',1974,'IN'],
  ['Liberty','footwear','indian',1954,'IN'],
  ['Paragon','footwear','indian',1975,'IN'],
  ['Red Tape','footwear,mens-fashion','global',1989,'UK'],
  ['Hush Puppies','footwear','global',1958,'US'],
  ['Crocs','footwear','global',2002,'US'],
  ['Clarks','footwear','global',1825,'UK'],
  ['Skechers','footwear','global',1992,'US'],
  ['Steve Madden','footwear','global',1990,'US'],
  ['Dr. Martens','footwear','global',1947,'UK'],
  ['Converse','footwear','global',1908,'US'],
  ['Vans','footwear','global',1966,'US'],
  ['Metro Shoes','footwear','indian',1955,'IN'],
  ['Mochi','footwear','indian',1998,'IN'],
  ['Inc.5','footwear','indian',2008,'IN'],
  ["Khadim's",'footwear','indian',1981,'IN'],
  ['Relaxo','footwear','indian',1976,'IN'],
  ['Sparx','footwear','indian',1990,'IN'],
  ['Lancer','footwear','indian',1994,'IN'],
  ['Walkaroo','footwear','indian',2012,'IN'],
  ['ID Shoes','footwear','indian',2005,'IN'],
  ['VKC','footwear','indian',1994,'IN'],
  ['Timberland','footwear,bags-luggage','global',1973,'US'],
  ['Birkenstock','footwear','global',1774,'DE'],
  ['UGG','footwear','global',1978,'AU'],
  ['Nine West','footwear,bags-luggage','global',1978,'US'],
  // BEAUTY & SKINCARE
  ['Lakme','beauty','indian',1952,'IN'],
  ['Maybelline','beauty','global',1915,'US'],
  ["L'Oreal Paris",'beauty','global',1909,'FR'],
  ['MAC Cosmetics','beauty','global',1984,'CA'],
  ['NARS','beauty','global',1994,'US'],
  ['Charlotte Tilbury','beauty','global',2013,'UK'],
  ['NYX Professional Makeup','beauty','global',1999,'US'],
  ['Huda Beauty','beauty','global',2013,'AE'],
  ['Fenty Beauty','beauty','global',2017,'US'],
  ['Urban Decay','beauty','global',1996,'US'],
  ['Too Faced','beauty','global',1998,'US'],
  ['Kylie Cosmetics','beauty','global',2016,'US'],
  ['Milani','beauty','global',2002,'US'],
  ['Faces Canada','beauty','global',1978,'CA'],
  ['Kay Beauty','beauty','indian',2019,'IN'],
  ['Nykaa Cosmetics','beauty','marketplace',2012,'IN'],
  ['Sugar Cosmetics','beauty','indian',2015,'IN'],
  ['Colorbar','beauty','indian',2004,'IN'],
  ['Revlon','beauty','global',1932,'US'],
  ['Max Factor','beauty','global',1909,'US'],
  ['Rimmel London','beauty','global',1834,'UK'],
  ['The Body Shop','beauty','global',1976,'UK'],
  ["Kiehl's",'beauty','global',1851,'US'],
  ['Forest Essentials','beauty','indian',2000,'IN'],
  ['Kama Ayurveda','beauty,health-wellness','indian',2002,'IN'],
  ['Mamaearth','beauty,health-wellness','indian',2016,'IN'],
  ['mCaffeine','beauty','indian',2016,'IN'],
  ['Plum','beauty,health-wellness','indian',2013,'IN'],
  ['WOW Skin Science','beauty','indian',2014,'IN'],
  ['Minimalist','beauty','indian',2020,'IN'],
  ['Dot & Key','beauty','indian',2018,'IN'],
  ['Pilgrim','beauty','indian',2019,'IN'],
  ['The Derma Co','beauty','indian',2019,'IN'],
  ['Biotique','beauty','indian',1992,'IN'],
  ['Himalaya','beauty,health-wellness','indian',1930,'IN'],
  ['Lotus Herbals','beauty','indian',1993,'IN'],
  ['VLCC','beauty,health-wellness','indian',1989,'IN'],
  ['Jovees','beauty','indian',1995,'IN'],
  ['Everyuth','beauty','indian',2007,'IN'],
  ['Cetaphil','beauty','global',1947,'US'],
  ['CeraVe','beauty','global',2005,'US'],
  ['Neutrogena','beauty','global',1930,'US'],
  ['Olay','beauty','global',1952,'US'],
  ["Pond's",'beauty','global',1846,'US'],
  ['Vaseline','beauty','global',1870,'US'],
  ['Dove','beauty','global',1957,'US'],
  ['La Roche-Posay','beauty','global',1975,'FR'],
  ['Vichy','beauty','global',1931,'FR'],
  ['Bioderma','beauty','global',1977,'FR'],
  ['Clinique','beauty','global',1968,'US'],
  ['Estee Lauder','beauty','global',1946,'US'],
  ['Lancome','beauty','global',1935,'FR'],
  ['SK-II','beauty','global',1980,'JP'],
  ['The Ordinary','beauty','global',2016,'CA'],
  ["Paula's Choice",'beauty','global',1995,'US'],
  ['Drunk Elephant','beauty','global',2012,'US'],
  ['Sunday Riley','beauty','global',2009,'US'],
  ['Tatcha','beauty','global',2009,'US'],
  ['Glossier','beauty','global',2014,'US'],
  ['Re-equil','beauty','indian',2015,'IN'],
  ['Aqualogica','beauty','indian',2021,'IN'],
  ['St. Botanica','beauty','indian',2016,'IN'],
  ['Nourish Mantra','beauty','indian',2019,'IN'],
  ['MCaffeine','beauty','indian',2016,'IN'],
  // APPLIANCES
  ['Whirlpool','appliances','global',1911,'US'],
  ['Bosch','appliances,power-tools','global',1886,'DE'],
  ['Siemens','appliances,industrial','global',1847,'DE'],
  ['IFB','appliances','indian',1974,'IN'],
  ['Godrej','appliances,furniture','indian',1897,'IN'],
  ['Voltas','appliances','indian',1954,'IN'],
  ['Blue Star','appliances','indian',1943,'IN'],
  ['Daikin','appliances','global',1924,'JP'],
  ['Hitachi','appliances,electronics','global',1910,'JP'],
  ['Mitsubishi','appliances,automotive','global',1870,'JP'],
  ['Carrier','appliances','global',1915,'US'],
  ['Lloyd','appliances','indian',1956,'IN'],
  ['Videocon','appliances,tv-audio','indian',1979,'IN'],
  ['BPL','appliances,tv-audio','indian',1963,'IN'],
  ['Bajaj Electricals','appliances','indian',1938,'IN'],
  ['Havells','appliances','indian',1958,'IN'],
  ['Crompton','appliances','indian',1937,'IN'],
  ['Orient','appliances','indian',1954,'IN'],
  ['Usha','appliances','indian',1935,'IN'],
  ['Atomberg','appliances','indian',2012,'IN'],
  ['Racold','appliances','global',1960,'IT'],
  ['AO Smith','appliances','global',1874,'US'],
  ['V-Guard','appliances','indian',1977,'IN'],
  ['Faber','appliances','global',1955,'DE'],
  ['Sunflame','appliances','indian',1998,'IN'],
  ['Hindware','appliances','indian',1960,'IN'],
  ['Pigeon','appliances,home-kitchen','indian',1971,'IN'],
  ['Prestige','appliances,home-kitchen','indian',1955,'IN'],
  ['Butterfly','appliances,home-kitchen','indian',1986,'IN'],
  ['Preethi','appliances,home-kitchen','indian',1994,'IN'],
  ['Hawkins','home-kitchen','indian',1958,'IN'],
  ['Black & Decker','appliances,power-tools','global',1910,'US'],
  ['Braun','appliances,beauty-tools','global',1921,'DE'],
  ['Russell Hobbs','appliances','global',1952,'UK'],
  ['Tefal','appliances,home-kitchen','global',1956,'FR'],
  ['Morphy Richards','appliances','global',1936,'UK'],
  ['Kenwood','appliances','global',1947,'UK'],
  ['KitchenAid','appliances,home-kitchen','global',1919,'US'],
  ['Dyson','appliances,beauty-tools','global',1993,'UK'],
  ['iRobot','appliances,smart-home','global',1990,'US'],
  ['Electrolux','appliances','global',1919,'SE'],
  // HOME & FURNITURE
  ['Nilkamal','furniture,home-kitchen','indian',1981,'IN'],
  ['Godrej Interio','furniture','indian',2003,'IN'],
  ['Durian','furniture','indian',1987,'IN'],
  ['Royal Oak','furniture','indian',2009,'IN'],
  ['Wakefit','furniture','indian',2016,'IN'],
  ['Sleepwell','furniture','indian',1926,'IN'],
  ['Centuary Mattresses','furniture','indian',1993,'IN'],
  ['SleepyCat','furniture','indian',2017,'IN'],
  ['Flo Mattress','furniture','indian',2018,'IN'],
  ['Sunday Mattress','furniture','indian',2017,'IN'],
  ['Dr. Back','furniture','indian',2012,'IN'],
  ['Kurl-On','furniture','indian',1962,'IN'],
  ['Kurlon','furniture','indian',1962,'IN'],
  ['IKEA','furniture,home-kitchen','global',1943,'SE'],
  ['Stylespa','furniture','indian',1994,'IN'],
  ['HomeTown','furniture','indian',2000,'IN'],
  // HOME DECOR
  ['Ellementry','home-kitchen','indian',2017,'IN'],
  ['Nestroots','home-kitchen','indian',2016,'IN'],
  ['Wooden Street','furniture','indian',2015,'IN'],
  ['Pepperfry','furniture','marketplace',2012,'IN'],
  ['FabFurnish','furniture','indian',2012,'IN'],
  // FOOD & GROCERY
  ['Amul','food-beverages','indian',1946,'IN'],
  ['Mother Dairy','food-beverages','indian',1974,'IN'],
  ['Nestle','food-beverages','global',1866,'CH'],
  ['Britannia','food-beverages','indian',1892,'IN'],
  ['ITC','food-beverages','indian',1910,'IN'],
  ['Parle','food-beverages','indian',1929,'IN'],
  ['Haldirams','food-beverages','indian',1941,'IN'],
  ['Bikaji','food-beverages','indian',1986,'IN'],
  ['Balaji Wafers','food-beverages','indian',1974,'IN'],
  ['MDH Masala','food-beverages','indian',1919,'IN'],
  ['Everest','food-beverages','indian',1965,'IN'],
  ['Catch','food-beverages','indian',2007,'IN'],
  ['Ramdev','food-beverages','indian',1990,'IN'],
  ['MTR Foods','food-beverages','indian',1924,'IN'],
  ['Patanjali','food-beverages,health-wellness,beauty','indian',2006,'IN'],
  ['Dabur','food-beverages,health-wellness,beauty','indian',1884,'IN'],
  ['Marico','food-beverages,beauty','indian',1990,'IN'],
  ["Cadbury's",'food-beverages','global',1824,'UK'],
  ["Lay's",'food-beverages','global',1940,'US'],
  ['Kurkure','food-beverages','indian',1999,'IN'],
  ['Maggi','food-beverages','global',1884,'CH'],
  ["Kellogg's",'food-beverages','global',1906,'US'],
  ['Heinz','food-beverages','global',1869,'US'],
  ['Dettol','health-wellness','global',1932,'UK'],
  ['Savlon','health-wellness','indian',1969,'IN'],
  ["Kissan",'food-beverages','global',1934,'IN'],
  ['Aashirvaad','food-beverages','indian',2002,'IN'],
  ['Sunfeast','food-beverages','indian',2003,'IN'],
  // HEALTH & WELLNESS
  ['Baidyanath','health-wellness','indian',1917,'IN'],
  ['Hamdard','health-wellness','indian',1906,'IN'],
  ['Zandu','health-wellness','indian',1910,'IN'],
  ['Amrutanjan','health-wellness','indian',1893,'IN'],
  ['Boroline','beauty,health-wellness','indian',1929,'IN'],
  ['Iodex','health-wellness','global',1924,'IN'],
  ['Moov','health-wellness','indian',1986,'IN'],
  ['Volini','health-wellness','global',1985,'IN'],
  ['Emami','health-wellness,beauty','indian',1974,'IN'],
  ['Vicco','beauty,health-wellness','indian',1958,'IN'],
  ['Meril Life','health-wellness','indian',1993,'IN'],
  ['Omron','health-wellness','global',1933,'JP'],
  ['Dr. Morepen','health-wellness','indian',1991,'IN'],
  ['Cipla Health','health-wellness','indian',1935,'IN'],
  ['Sun Pharma','health-wellness','indian',1983,'IN'],
  ['Mankind Pharma','health-wellness','indian',1991,'IN'],
  ['HealthKart','health-wellness','marketplace',2011,'IN'],
  ['MuscleBlaze','health-wellness','indian',2011,'IN'],
  ['Oziva','health-wellness','indian',2016,'IN'],
  ['Wellbeing Nutrition','health-wellness','indian',2019,'IN'],
  // AUTOMOTIVE
  ['Bosch Automotive','automotive','global',1886,'DE'],
  ['Ceat','automotive','indian',1924,'IN'],
  ['Apollo Tyres','automotive','indian',1972,'IN'],
  ['MRF','automotive','indian',1946,'IN'],
  ['Michelin','automotive','global',1889,'FR'],
  ['Bridgestone','automotive','global',1931,'JP'],
  ['Goodyear','automotive','global',1898,'US'],
  ['JK Tyre','automotive','indian',1974,'IN'],
  ['Castrol','automotive','global',1899,'UK'],
  ['Shell Lubricants','automotive','global',1907,'NL'],
  ['Minda','automotive','indian',1958,'IN'],
  ['Lumax','automotive','indian',1953,'IN'],
  ['Denso','automotive','global',1949,'JP'],
  ['Continental','automotive','global',1871,'DE'],
  ['Motherson','automotive','indian',1975,'IN'],
  // TOYS & BABY
  ['Hasbro','toys','global',1923,'US'],
  ['Mattel','toys','global',1945,'US'],
  ['LEGO','toys','global',1932,'DK'],
  ['VTech','toys','global',1980,'HK'],
  ['Funskool','toys','indian',1987,'IN'],
  ['Mee Mee','toys','indian',1994,'IN'],
  ['LuvLap','toys','indian',2010,'IN'],
  ['R for Rabbit','toys','indian',2015,'IN'],
  ['Chicco','toys','global',1958,'IT'],
  ['Graco','toys','global',1942,'US'],
  ['Cybex','toys','global',2002,'DE'],
  ['Britax','toys','global',1938,'UK'],
  ['Stokke','toys','global',1932,'NO'],
  ['Fisher-Price','toys','global',1930,'US'],
  ['Hot Wheels','toys','global',1968,'US'],
  ['Barbie','toys','global',1959,'US'],
  // JEWELRY
  ['Tanishq','jewelry,watches','indian',1994,'IN'],
  ['Malabar Gold','jewelry','indian',1993,'IN'],
  ['Kalyan Jewellers','jewelry','indian',1993,'IN'],
  ['PC Jeweller','jewelry','indian',2005,'IN'],
  ['Joyalukkas','jewelry','indian',2002,'IN'],
  ['Bhima Jewellers','jewelry','indian',1925,'IN'],
  ['Caratlane','jewelry','indian',2008,'IN'],
  ['Bluestone','jewelry','indian',2011,'IN'],
  ['Melorra','jewelry','indian',2016,'IN'],
  ['Voylla','jewelry','indian',2012,'IN'],
  ['Swarovski','jewelry','global',1895,'AT'],
  ['Pandora','jewelry','global',1982,'DK'],
  ['Zaveri Pearls','jewelry','indian',2010,'IN'],
  // MUSICAL INSTRUMENTS
  ['Yamaha','musical-instruments','global',1887,'JP'],
  ['Roland','musical-instruments','global',1972,'JP'],
  ['Fender','musical-instruments','global',1946,'US'],
  ['Gibson','musical-instruments','global',1902,'US'],
  ['Ibanez','musical-instruments','global',1957,'JP'],
  ['Epiphone','musical-instruments','global',1873,'US'],
  ['Korg','musical-instruments','global',1963,'JP'],
  ['Casio Musical','musical-instruments','global',1946,'JP'],
  ['Hohner','musical-instruments','global',1857,'DE'],
  ['Banjira','musical-instruments','indian',2003,'IN'],
  // BAGS & LUGGAGE
  ['Samsonite','bags-luggage','global',1910,'US'],
  ['American Tourister','bags-luggage','global',1933,'US'],
  ['VIP Industries','bags-luggage','indian',1971,'IN'],
  ['Skybags','bags-luggage','indian',2009,'IN'],
  ['Safari','bags-luggage','indian',1974,'IN'],
  ['Wildcraft','bags-luggage,sports','indian',2009,'IN'],
  ['Hidesign','bags-luggage,footwear','indian',1978,'IN'],
  ['Caprese','bags-luggage','indian',2012,'IN'],
  ['Baggit','bags-luggage','indian',1990,'IN'],
  ['Holii','bags-luggage','indian',2011,'IN'],
  ['Lino Perros','bags-luggage','indian',2006,'IN'],
  ['Coach','bags-luggage,watches','global',1941,'US'],
  ['Lavie','bags-luggage','indian',2010,'IN'],
  ['Aldo','bags-luggage,footwear','global',1972,'CA'],
  ['Charles & Keith','bags-luggage,footwear','global',1996,'SG'],
  // CAMERAS
  ['Canon','cameras-photo','global',1937,'JP'],
  ['Nikon','cameras-photo','global',1917,'JP'],
  ['Fujifilm','cameras-photo','global',1934,'JP'],
  ['GoPro','cameras-photo','global',2002,'US'],
  ['DJI','cameras-photo','global',2006,'CN'],
  ['Olympus','cameras-photo','global',1919,'JP'],
  ['Leica','cameras-photo','global',1914,'DE'],
  ['Sigma','cameras-photo','global',1961,'JP'],
  ['Tamron','cameras-photo','global',1950,'JP'],
  ['Manfrotto','cameras-photo','global',1972,'IT'],
  // PRIVATE LABELS / MARKETPLACE
  ['Solimo','home-kitchen,food-beverages','marketplace',2018,'IN'],
  ['Symbol','mens-fashion','marketplace',2012,'IN'],
  ['Myx','womens-fashion','marketplace',2015,'IN'],
  ['Lifelong','appliances,health-wellness','marketplace',2015,'IN'],
  ['Croma','electronics,appliances','indian',2006,'IN'],
  ['Reliance Digital','electronics,appliances','indian',2007,'IN'],
  ['Nykaa Fashion','womens-fashion','marketplace',2018,'IN'],
  ['Meesho Trends','fashion-jewelry,womens-fashion','marketplace',2015,'IN'],
  ['Myntra Fashion','mens-fashion,womens-fashion','marketplace',2007,'IN'],
  ['AmazonBasics','home-kitchen,electronics','marketplace',2009,'US'],
  // OFFICE & STATIONERY
  ['Camlin','office-stationery','indian',1931,'IN'],
  ['Classmate','office-stationery','indian',2003,'IN'],
  ['Luxor','office-stationery','indian',1963,'IN'],
  ['Natraj','office-stationery','indian',1992,'IN'],
  ['Reynolds','office-stationery','global',1945,'US'],
  ['Parker','office-stationery','global',1888,'US'],
  ['Faber-Castell','office-stationery','global',1761,'DE'],
  ['Staedtler','office-stationery','global',1835,'DE'],
  ['Doms','office-stationery','indian',2003,'IN'],
  ['Pilot','office-stationery','global',1918,'JP'],
  // PET SUPPLIES
  ['Pedigree','pet-supplies','global',1934,'US'],
  ['Royal Canin','pet-supplies','global',1967,'FR'],
  ['Purina','pet-supplies','global',1893,'US'],
  ['Whiskas','pet-supplies','global',1958,'US'],
  ["Hill's Science Diet",'pet-supplies','global',1907,'US'],
  ['Drools','pet-supplies','indian',2010,'IN'],
  ['Fidele','pet-supplies','indian',2015,'IN'],
  ['Me-O','pet-supplies','global',1950,'TH'],
  ['Sheba','pet-supplies','global',1986,'US'],
  ['Iams','pet-supplies','global',1946,'US'],
  // GARDEN & OUTDOORS
  ['Bosch Garden','garden-outdoors','global',1886,'DE'],
  ['Black+Decker Garden','garden-outdoors','global',1910,'US'],
  ['Husqvarna','garden-outdoors','global',1689,'SE'],
  ['Ugaoo','garden-outdoors','indian',2015,'IN'],
  ['Kraft Seeds','garden-outdoors','indian',2012,'IN'],
  ['TrustBasket','garden-outdoors','indian',2014,'IN'],
];

class BrandsSeed {
  constructor() {
    this.logger = new SeedLogger('Brands');
    this.mongoose = mongoose;
  }

  async execute() {
    const conn = this.mongoose.connection;
    if (!conn || !conn.collection) throw new Error('MongoDB connection not available');
    this.logger.info(`🏢 Seeding Brands — ${BRANDS_RAW.length} entries`);

    await conn.collection('platformbrands').deleteMany({});

    const seenNames = new Set();
    const docs = [];
    for (let i = 0; i < BRANDS_RAW.length; i++) {
      const [name, categories, type, founded, origin] = BRANDS_RAW[i];
      const key = name.toLowerCase().trim();
      if (seenNames.has(key)) continue;
      seenNames.add(key);
      const slug = slugify(name);
      docs.push({
        _id: new mongoose.Types.ObjectId(),
        name,
        slug,
        description: `${name} is a ${type} brand founded in ${founded}.`,
        logo: `https://logo.clearbit.com/${slug}.com`,
        logoUrl: `https://logo.clearbit.com/${slug}.com`,
        thumbnails: `https://logo.clearbit.com/${slug}.com`,
        imageUrl: `https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=400`,
        active: true,
        sortOrder: i,
        metadata: {
          type,
          founded,
          countryOfOrigin: origin,
          categories: categories.split(','),
        },
        createdAt: new Date(),
        updatedAt: new Date(),
      });
    }

    const BATCH = 200;
    for (let i = 0; i < docs.length; i += BATCH) {
      await conn.collection('platformbrands').insertMany(docs.slice(i, i + BATCH));
      this.logger.recordBatch(Math.min(BATCH, docs.length - i));
    }

    this.logger.printStats();
    const byType = docs.reduce((a, d) => { const t = d.metadata.type; a[t] = (a[t] || 0) + 1; return a; }, {});
    return { created: docs.length, byType };
  }
}

module.exports = BrandsSeed;
