const mongoose = require("mongoose");
const SeedLogger = require("../utils/seed-logger");

const attr = (key, label, type, opts = {}) => ({
  platformOptionId: opts.platformOptionId || "",
  allowCustomOptions: opts.allowCustomOptions || false,
  key,
  label,
  type,
  required: opts.required || false,
  options: opts.options || [],
  unit: opts.unit || null,
  isVariantAttribute: opts.isVariant || false,
  isFilterable: opts.filterable !== false,
  isSearchable: opts.searchable !== false,
});

const ATTR = {
  color: attr("color", "Color", "select", {
    options: [
      "Black",
      "White",
      "Red",
      "Blue",
      "Green",
      "Yellow",
      "Navy",
      "Grey",
      "Brown",
      "Pink",
      "Purple",
      "Orange",
      "Maroon",
      "Olive",
      "Teal",
      "Gold",
      "Silver",
      "Beige",
      "Charcoal",
      "Lavender",
      "Mustard",
      "Rust",
      "Coral",
      "Peach",
    ],
    isVariant: true,
  }),
  size_apparel: attr("size", "Size", "select", {
    options: ["XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL", "Free Size"],
    isVariant: true,
    required: true,
  }),
  size_shoes: attr("size", "Shoe Size", "select", {
    options: ["4", "5", "6", "7", "8", "9", "10", "11", "12", "13"],
    isVariant: true,
    required: true,
  }),
  material: attr("material", "Material", "select", {
    options: [
      "Cotton",
      "Polyester",
      "Silk",
      "Wool",
      "Linen",
      "Nylon",
      "Viscose",
      "Rayon",
      "Satin",
      "Chiffon",
      "Georgette",
      "Crepe",
      "Denim",
      "Leather",
      "Suede",
      "Canvas",
      "Mesh",
      "Jersey",
      "Fleece",
      "Velvet",
      "Acrylic",
      "Spandex",
      "Modal",
      "Bamboo",
    ],
    filterable: true,
  }),
  fit: attr("fit", "Fit", "select", {
    options: [
      "Slim Fit",
      "Regular Fit",
      "Relaxed Fit",
      "Loose Fit",
      "Oversized",
      "Skinny",
      "Straight",
      "Bootcut",
    ],
  }),
  occasion: attr("occasion", "Occasion", "multi_select", {
    options: [
      "Casual",
      "Formal",
      "Party",
      "Sports",
      "Ethnic",
      "Wedding",
      "Festive",
      "Office",
      "Beach",
    ],
  }),
  gender: attr("gender", "Gender", "select", {
    options: ["Men", "Women", "Unisex", "Boys", "Girls"],
    required: true,
    filterable: true,
  }),
  age_group: attr("age_group", "Age Group", "select", {
    options: [
      "Infant (0-2y)",
      "Toddler (2-5y)",
      "Kids (5-12y)",
      "Teen (12-17y)",
      "Adult 18+",
    ],
  }),
  pattern: attr("pattern", "Pattern", "select", {
    options: [
      "Solid",
      "Striped",
      "Checked",
      "Printed",
      "Embroidered",
      "Floral",
      "Abstract",
      "Geometric",
      "Animal Print",
      "Polka Dot",
      "Tie-Dye",
    ],
  }),
  sleeve: attr("sleeve_length", "Sleeve Length", "select", {
    options: [
      "Full Sleeve",
      "Half Sleeve",
      "3/4 Sleeve",
      "Sleeveless",
      "Cap Sleeve",
      "Bell Sleeve",
    ],
  }),
  collar: attr("collar_type", "Collar Type", "select", {
    options: [
      "Round Neck",
      "V-Neck",
      "Polo",
      "Mandarin",
      "Button-Down",
      "Hooded",
      "Cowl Neck",
      "Square Neck",
    ],
  }),
  wash: attr("wash_care", "Wash Care", "select", {
    options: [
      "Machine Wash",
      "Hand Wash",
      "Dry Clean Only",
      "Do Not Wash",
      "Spot Clean",
    ],
  }),
  ram: attr("ram", "RAM", "select", {
    options: [
      "2GB",
      "3GB",
      "4GB",
      "6GB",
      "8GB",
      "12GB",
      "16GB",
      "32GB",
      "64GB",
    ],
    isVariant: true,
    unit: "GB",
  }),
  storage: attr("storage", "Internal Storage", "select", {
    options: ["16GB", "32GB", "64GB", "128GB", "256GB", "512GB", "1TB", "2TB"],
    isVariant: true,
    unit: "GB",
  }),
  display: attr("display_size", "Display Size", "number", { unit: "inches" }),
  resolution: attr("resolution", "Resolution", "select", {
    options: [
      "HD (1280x720)",
      "Full HD (1920x1080)",
      "2K (2560x1440)",
      "4K (3840x2160)",
      "8K (7680x4320)",
    ],
  }),
  processor: attr("processor", "Processor", "select", {
    options: [
      "Intel Core i3",
      "Intel Core i5",
      "Intel Core i7",
      "Intel Core i9",
      "AMD Ryzen 3",
      "AMD Ryzen 5",
      "AMD Ryzen 7",
      "AMD Ryzen 9",
      "Apple M1",
      "Apple M2",
      "Apple M3",
      "Snapdragon 8 Gen 2",
      "Snapdragon 8 Gen 3",
      "MediaTek Dimensity 9200",
      "Exynos 2400",
    ],
  }),
  battery: attr("battery", "Battery", "text"),
  camera: attr("camera", "Camera", "text"),
  os: attr("os", "Operating System", "select", {
    options: [
      "Android 13",
      "Android 14",
      "iOS 17",
      "Windows 11",
      "macOS Sonoma",
      "Linux",
      "Chrome OS",
    ],
  }),
  connectivity: attr("connectivity", "Connectivity", "multi_select", {
    options: [
      "Wi-Fi",
      "Bluetooth",
      "5G",
      "4G LTE",
      "USB-C",
      "Thunderbolt",
      "NFC",
    ],
  }),
  refresh_rate: attr("refresh_rate", "Refresh Rate", "select", {
    options: ["60Hz", "90Hz", "120Hz", "144Hz", "165Hz", "240Hz"],
    unit: "Hz",
  }),
  network_gen: attr("network", "Network", "select", {
    options: ["5G", "4G LTE", "3G", "2G"],
    isVariant: true,
  }),
  capacity_ltr: attr("capacity", "Capacity", "number", { unit: "Litres" }),
  energy_star: attr("energy_rating", "Energy Rating", "select", {
    options: ["1 Star", "2 Star", "3 Star", "4 Star", "5 Star"],
    filterable: true,
  }),
  wattage: attr("wattage", "Wattage", "number", { unit: "Watts" }),
  voltage: attr("voltage", "Voltage", "select", {
    options: ["110V", "220V", "240V"],
  }),
  width: attr("width", "Width", "number", { unit: "cm" }),
  height_attr: attr("height", "Height", "number", { unit: "cm" }),
  depth: attr("depth", "Depth", "number", { unit: "cm" }),
  weight_kg: attr("weight_capacity", "Weight Capacity", "number", {
    unit: "kg",
  }),
  finish: attr("finish", "Finish", "select", {
    options: [
      "Matte",
      "Glossy",
      "Satin",
      "Walnut",
      "Teak",
      "Wenge",
      "Oak",
      "Cherry",
      "Pine",
      "Mahogany",
      "Lacquered",
      "Powder Coated",
    ],
  }),
  material_furniture: attr("material", "Material", "select", {
    options: [
      "Solid Wood",
      "Engineered Wood",
      "MDF",
      "Plywood",
      "Steel",
      "Aluminium",
      "Wrought Iron",
      "Glass",
      "Marble",
      "Bamboo",
      "Rattan",
    ],
  }),
  assembly: attr("assembly_required", "Assembly Required", "boolean", {}),

  graphics: attr("graphics", "Graphics", "text"),
  storage_type: attr("storage_type", "Storage Type", "select", {
    options: ["HDD", "SSD", "NVMe SSD"],
  }),
  front_camera: attr("front_camera", "Front Camera", "text"),
  rear_camera: attr("rear_camera", "Rear Camera", "text"),
  fast_charging: attr("fast_charging", "Fast Charging", "boolean"),
  bluetooth_version: attr("bluetooth_version", "Bluetooth Version", "select", {
    options: ["4.2", "5.0", "5.1", "5.2", "5.3", "5.4"],
  }),
  wifi_standard: attr("wifi_standard", "Wi-Fi Standard", "select", {
    options: ["Wi-Fi 5", "Wi-Fi 6", "Wi-Fi 6E", "Wi-Fi 7"],
  }),
  sim_type: attr("sim_type", "SIM Type", "select", {
    options: ["Single SIM", "Dual SIM", "eSIM"],
  }),
  interface: attr("interface", "Interface", "select", {
    options: [
      "USB-A",
      "USB-C",
      "Lightning",
      "Micro USB",
      "SATA",
      "PCIe",
      "M.2",
    ],
  }),
  read_speed: attr("read_speed", "Read Speed", "text"),
  write_speed: attr("write_speed", "Write Speed", "text"),
  compatible_model: attr("compatible_model", "Compatible Model", "text"),
  platform: attr("platform", "Platform", "multi_select", {
    options: [
      "Windows",
      "macOS",
      "Android",
      "iOS",
      "PlayStation",
      "Xbox",
      "Nintendo Switch",
    ],
  }),
  runtime: attr("runtime", "Runtime", "text"),
  charging_time: attr("charging_time", "Charging Time", "text"),
  printer_type: attr("printer_type", "Printer Type", "select", {
    options: ["Inkjet", "Laser", "Thermal"],
  }),
  print_technology: attr("print_technology", "Print Technology", "select", {
    options: ["Inkjet", "Laser", "Thermal"],
  }),

  flavor: attr("flavor", "Flavor", "select", {
    options: [
      "Chocolate",
      "Vanilla",
      "Strawberry",
      "Mango",
      "Mixed Fruit",
      "Unflavored",
      "Masala",
      "Salt & Pepper",
      "Honey",
      "Chilli",
      "Cheese",
      "Tomato",
      "Caramel",
      "Mint",
      "Orange",
      "Lemon",
      "Butterscotch",
    ],
    isVariant: true,
  }),
  pack_size: attr("pack_size", "Pack Size", "select", {
    options: [
      "100g",
      "200g",
      "250g",
      "500g",
      "1kg",
      "2kg",
      "5kg",
      "Pack of 2",
      "Pack of 3",
      "Pack of 6",
      "Pack of 12",
      "Pack of 24",
    ],
    isVariant: true,
  }),
  shelf_life: attr("shelf_life", "Shelf Life", "number", { unit: "months" }),
  veg_nonveg: attr("food_type", "Food Type", "select", {
    options: ["Vegetarian", "Non-Vegetarian", "Vegan", "Eggitarian"],
  }),
  language: attr("language", "Language", "select", {
    options: [
      "English",
      "Hindi",
      "Bengali",
      "Telugu",
      "Marathi",
      "Tamil",
      "Gujarati",
      "Kannada",
      "Malayalam",
      "Punjabi",
    ],
  }),
  pages: attr("pages", "Number of Pages", "number", {}),
  format: attr("format", "Format", "select", {
    options: [
      "Paperback",
      "Hardcover",
      "E-book",
      "Audiobook",
      "Board Book",
      "Spiral Bound",
    ],
  }),
  sport: attr("sport", "Sport", "select", {
    options: [
      "Cricket",
      "Football",
      "Basketball",
      "Tennis",
      "Badminton",
      "Table Tennis",
      "Swimming",
      "Cycling",
      "Running",
      "Gym",
      "Yoga",
      "Golf",
    ],
  }),
  metal: attr("metal", "Metal Type", "select", {
    options: [
      "Gold (22K)",
      "Gold (18K)",
      "Gold (14K)",
      "Silver (92.5%)",
      "Platinum",
      "Rose Gold",
      "White Gold",
      "Stainless Steel",
      "Brass",
    ],
  }),
  stone: attr("stone", "Stone Type", "select", {
    options: [
      "Diamond",
      "Ruby",
      "Emerald",
      "Sapphire",
      "Pearl",
      "Topaz",
      "Amethyst",
      "Garnet",
      "Turquoise",
      "Coral",
      "Opal",
      "No Stone",
    ],
  }),
  purity: attr("purity", "Purity (Karat)", "select", {
    options: ["14K", "18K", "22K", "24K", "925 Silver", "950 Platinum"],
  }),
  warranty: attr("warranty", "Warranty", "select", {
    options: [
      "No Warranty",
      "3 Months",
      "6 Months",
      "1 Year",
      "2 Years",
      "3 Years",
      "5 Years",
      "Lifetime",
    ],
  }),
  brand_attr: attr("brand", "Brand", "text", { searchable: true }),
  country_origin: attr("country_of_origin", "Country of Origin", "select", {
    options: [
      "India",
      "China",
      "USA",
      "South Korea",
      "Japan",
      "Germany",
      "Bangladesh",
      "Vietnam",
      "Taiwan",
      "Thailand",
    ],
  }),
  skin_type: attr("skin_type", "Skin Type", "multi_select", {
    options: [
      "All Skin Types",
      "Normal",
      "Dry",
      "Oily",
      "Combination",
      "Sensitive",
      "Acne-Prone",
    ],
  }),
  concern: attr("concern", "Skin Concern", "multi_select", {
    options: [
      "Anti-Aging",
      "Brightening",
      "Moisturizing",
      "Acne Control",
      "Dark Spots",
      "Pore Minimizing",
      "Sun Protection",
      "Hydration",
    ],
  }),
  spf: attr("spf", "SPF", "select", {
    options: [
      "SPF 15",
      "SPF 20",
      "SPF 30",
      "SPF 50",
      "SPF 50+",
      "SPF 100",
      "No SPF",
    ],
  }),
  volume: attr("volume_ml", "Volume", "select", {
    options: [
      "5ml",
      "10ml",
      "15ml",
      "20ml",
      "30ml",
      "50ml",
      "75ml",
      "100ml",
      "150ml",
      "200ml",
      "250ml",
      "300ml",
      "500ml",
      "1000ml",
    ],
    isVariant: true,
    unit: "ml",
  }),
  vehicle_type: attr("vehicle_type", "Vehicle Type", "select", {
    options: [
      "2-Wheeler",
      "4-Wheeler",
      "Truck",
      "Bus",
      "SUV",
      "Sedan",
      "Hatchback",
      "Commercial",
    ],
  }),

  neckline: attr("neckline", "Neckline", "select", {
    options: [
      "Round Neck",
      "V-Neck",
      "Square Neck",
      "Halter Neck",
      "Cowl Neck",
      "High Neck",
      "Keyhole Neck",
    ],
  }),
  closure_type: attr("closure_type", "Closure Type", "select", {
    options: [
      "Lace-Up",
      "Slip-On",
      "Velcro",
      "Zip",
      "Button",
      "Buckle",
      "Drawstring",
      "Magnetic Snap",
    ],
  }),
  formulation: attr("formulation", "Formulation", "select", {
    options: [
      "Cream",
      "Gel",
      "Liquid",
      "Powder",
      "Serum",
      "Spray",
      "Foam",
      "Oil",
      "Stick",
      "Lotion",
    ],
  }),
  fragrance_family: attr("fragrance_family", "Fragrance Family", "select", {
    options: [
      "Floral",
      "Woody",
      "Fresh",
      "Oriental",
      "Fruity",
      "Citrus",
      "Spicy",
    ],
  }),
  power_source: attr("power_source", "Power Source", "select", {
    options: ["Battery Operated", "Rechargeable", "Corded Electric", "Manual"],
  }),
  load_type: attr("load_type", "Load Type", "select", {
    options: ["Front Load", "Top Load", "Semi Automatic", "Washer Dryer"],
  }),
  function_type: attr("function_type", "Function Type", "select", {
    options: ["Fully Automatic", "Semi Automatic", "Manual"],
  }),
  washing_capacity: attr("washing_capacity", "Washing Capacity", "select", {
    options: ["Below 6 kg", "6-6.9 kg", "7-7.9 kg", "8-8.9 kg", "9 kg & Above"],
  }),
  inverter_technology: attr(
    "inverter_technology",
    "Inverter Technology",
    "boolean",
    {},
  ),
  geyser_type: attr("geyser_type", "Geyser Type", "select", {
    options: ["Instant", "Storage", "Gas", "Solar"],
  }),
  ac_type: attr("ac_type", "AC Type", "select", {
    options: ["Split", "Window", "Portable", "Tower", "Cassette"],
  }),
  tonnage: attr("tonnage", "Tonnage", "select", {
    options: ["0.8 Ton", "1 Ton", "1.2 Ton", "1.5 Ton", "2 Ton", "2.5 Ton"],
  }),
  room_size: attr("room_size", "Room Size", "select", {
    options: ["Small", "Medium", "Large", "Extra Large"],
  }),
  fan_type: attr("fan_type", "Fan Type", "select", {
    options: ["Ceiling", "Table", "Pedestal", "Wall", "Exhaust", "Tower"],
  }),
  air_delivery: attr("air_delivery", "Air Delivery", "text"),
  microwave_type: attr("microwave_type", "Microwave Type", "select", {
    options: ["Solo", "Grill", "Convection", "OTG", "Air Fryer Oven"],
  }),
  refrigerator_type: attr("refrigerator_type", "Refrigerator Type", "select", {
    options: [
      "Single Door",
      "Double Door",
      "Triple Door",
      "Side-by-Side",
      "French Door",
      "Mini",
    ],
  }),
  freezer_position: attr("freezer_position", "Freezer Position", "select", {
    options: ["Top", "Bottom", "Side", "Convertible", "No Freezer"],
  }),
  diameter: attr("diameter", "Diameter", "number", { unit: "cm" }),
  set_size: attr("set_size", "Set Size", "select", {
    options: [
      "Single",
      "Set of 2",
      "Set of 3",
      "Set of 4",
      "Set of 6",
      "Set of 12",
    ],
  }),
  cookware_compatibility: attr(
    "cookware_compatibility",
    "Cooktop Compatibility",
    "multi_select",
    {
      options: ["Gas Stove", "Induction", "Electric", "Ceramic", "Halogen"],
    },
  ),
  non_stick: attr("non_stick", "Non-Stick Coating", "boolean", {}),
  bedding_size: attr("bedding_size", "Bedding Size", "select", {
    options: ["Single", "Double", "Queen", "King", "Super King"],
    isVariant: true,
  }),
  thread_count: attr("thread_count", "Thread Count", "select", {
    options: ["Below 150", "150-199", "200-299", "300-399", "400 and Above"],
  }),
  curtain_length: attr("curtain_length", "Curtain Length", "select", {
    options: ["Window", "Door", "Long Door", "Extra Long"],
    isVariant: true,
  }),
  light_source: attr("light_source", "Light Source", "select", {
    options: ["LED", "CFL", "Incandescent", "Halogen", "Fluorescent", "Solar"],
  }),
  bulb_base: attr("bulb_base", "Bulb Base", "select", {
    options: ["B22", "E27", "E14", "GU10", "G9", "Integrated LED"],
  }),
  bed_size: attr("bed_size", "Bed Size", "select", {
    options: ["Single", "Diwan", "Double", "Queen", "King", "Bunk"],
    isVariant: true,
  }),
  storage_included: attr("storage_included", "Storage Included", "boolean", {}),
  delivery_condition: attr(
    "delivery_condition",
    "Delivery Condition",
    "select",
    {
      options: [
        "Pre-assembled",
        "Knock Down",
        "DIY",
        "Basic Assembly Required",
      ],
    },
  ),
  seating_capacity: attr("seating_capacity", "Seating Capacity", "select", {
    options: [
      "1 Seater",
      "2 Seater",
      "3 Seater",
      "4 Seater",
      "5 Seater",
      "6 Seater",
      "8 Seater",
    ],
  }),
  mattress_type: attr("mattress_type", "Mattress Type", "select", {
    options: [
      "Memory Foam",
      "Orthopedic",
      "Spring",
      "Coir",
      "Latex",
      "Foam",
      "Hybrid",
    ],
  }),
  firmness: attr("firmness", "Firmness", "select", {
    options: ["Soft", "Medium Soft", "Medium", "Medium Firm", "Firm"],
  }),
  item_weight: attr("item_weight", "Net Weight", "number", { unit: "g" }),
  dietary_preference: attr(
    "dietary_preference",
    "Dietary Preference",
    "multi_select",
    {
      options: [
        "Vegetarian",
        "Vegan",
        "Gluten Free",
        "Sugar Free",
        "High Protein",
        "Low Fat",
        "Organic",
      ],
    },
  ),
  container_type: attr("container_type", "Container Type", "select", {
    options: ["Pouch", "Box", "Bottle", "Jar", "Can", "Tetra Pack", "Sachet"],
  }),
  organic_certified: attr(
    "organic_certified",
    "Organic Certified",
    "boolean",
    {},
  ),
  sport_size: attr("sport_size", "Size", "select", {
    options: ["XS", "S", "M", "L", "XL", "Free Size", "Junior", "Senior"],
    isVariant: true,
  }),
  skill_level: attr("skill_level", "Skill Level", "select", {
    options: ["Beginner", "Intermediate", "Advanced", "Professional"],
  }),
  playing_level: attr("playing_level", "Playing Level", "select", {
    options: [
      "Recreational",
      "Training",
      "Match",
      "Tournament",
      "Professional",
    ],
  }),
  grip_size: attr("grip_size", "Grip Size", "select", {
    options: ["G1", "G2", "G3", "G4", "G5", "Standard"],
  }),
  cycle_size: attr("cycle_size", "Cycle Size", "select", {
    options: [
      "12 inch",
      "14 inch",
      "16 inch",
      "18 inch",
      "20 inch",
      "24 inch",
      "26 inch",
      "27.5 inch",
      "29 inch",
    ],
    isVariant: true,
  }),
  gear_count: attr("gear_count", "Gear Count", "select", {
    options: [
      "Single Speed",
      "6 Gear",
      "7 Gear",
      "18 Gear",
      "21 Gear",
      "24 Gear",
    ],
  }),
  water_resistance: attr("water_resistance", "Water Resistance", "boolean", {}),
  author: attr("author", "Author", "text", {}),
  publisher: attr("publisher", "Publisher", "text", {}),
  publication_year: attr("publication_year", "Publication Year", "number", {}),
  isbn: attr("isbn", "ISBN", "text", {}),
  battery_operated: attr("battery_operated", "Battery Operated", "boolean", {}),
  microphone: attr("microphone", "Microphone Type", "select", {
    options: ["Dynamic", "Condenser", "Lapel", "Karaoke", "Studio", "USB"],
  }),
  compatible_device: attr(
    "compatible_device",
    "Compatible Device",
    "multi_select",
    {
      options: [
        "Mobile",
        "Laptop",
        "Desktop",
        "Tablet",
        "Camera",
        "Speaker",
        "Musical Instrument",
      ],
    },
  ),
  diaper_size: attr("diaper_size", "Diaper Size", "select", {
    options: ["Newborn", "XS", "S", "M", "L", "XL", "XXL"],
    isVariant: true,
  }),
  baby_weight_range: attr("baby_weight_range", "Baby Weight Range", "select", {
    options: [
      "Up to 5 kg",
      "4-8 kg",
      "7-12 kg",
      "9-14 kg",
      "12-17 kg",
      "15 kg and Above",
    ],
  }),
  hair_type: attr("hair_type", "Hair Type", "multi_select", {
    options: [
      "All Hair Types",
      "Dry",
      "Oily",
      "Normal",
      "Curly",
      "Frizzy",
      "Sensitive Scalp",
    ],
  }),
  minimum_age: attr("minimum_age", "Minimum Age", "select", {
    options: [
      "0 Months",
      "3 Months",
      "6 Months",
      "1 Year",
      "2 Years",
      "3 Years",
      "5 Years",
      "8 Years",
      "12 Years",
    ],
  }),
  skill_development: attr(
    "skill_development",
    "Skill Development",
    "multi_select",
    {
      options: [
        "Motor Skills",
        "Problem Solving",
        "Creativity",
        "Memory",
        "STEM Learning",
        "Language",
        "Social Skills",
      ],
    },
  ),
};

// ─── Category tree data ───────────────────────────────────────────────────────
const CATEGORY_TREE = [
  {
    key: "electronics",
    name: "Electronics",
    order: 1,
    attrs: [ATTR.brand_attr, ATTR.warranty, ATTR.country_origin],
    subs: [
      {
        key: "mobiles",
        name: "Mobiles",
        attrs: [
          ATTR.brand_attr,
          ATTR.color,
          ATTR.processor,
          ATTR.ram,
          ATTR.storage,
          ATTR.display,
          ATTR.camera,
          ATTR.battery,
          ATTR.os,
          ATTR.network_gen,
          ATTR.refresh_rate,
          ATTR.connectivity,
          ATTR.fast_charging,
          ATTR.warranty,
        ],
        children: [
          "Android Phones",
          "iPhones",
          "Feature Phones",
          "5G Phones",
          "Gaming Phones",
          "Camera Phones",
          "Budget Phones",
          "Premium Phones",
          "Foldable Phones",
          "Refurbished Phones",
        ],
      },
      {
        key: "computers",
        name: "Computers",
        attrs: [
          ATTR.brand_attr,
          ATTR.processor,
          ATTR.graphics,
          ATTR.ram,
          ATTR.storage,
          ATTR.storage_type,
          ATTR.display,
          ATTR.resolution,
          ATTR.os,
          ATTR.connectivity,
          ATTR.warranty,
        ],
        children: [
          "Laptops",
          "Desktop PCs",
          "Gaming Laptops",
          "Business Laptops",
          "MacBooks",
          "All-in-One PCs",
          "Mini PCs",
          "Monitors",
          "PC Components",
          "Printers",
        ],
      },
      {
        key: "tv-audio",
        name: "TVs & Audio",
        attrs: [
          ATTR.brand_attr,
          ATTR.display,
          ATTR.resolution,
          ATTR.refresh_rate,
          ATTR.os,
          ATTR.connectivity,
          ATTR.energy_star,
          ATTR.warranty,
        ],
        children: [
          "Smart TVs",
          "Android TVs",
          "Google TVs",
          "LED TVs",
          "OLED TVs",
          "QLED TVs",
          "Soundbars",
          "Home Theatre",
          "Bluetooth Speakers",
          "Streaming Devices",
        ],
      },
      {
        key: "tablets",
        name: "Tablets",
        attrs: [
          ATTR.brand_attr,
          ATTR.processor,
          ATTR.ram,
          ATTR.storage,
          ATTR.display,
          ATTR.os,
          ATTR.battery,
          ATTR.connectivity,
          ATTR.color,
          ATTR.warranty,
        ],
        children: [
          "Android Tablets",
          "iPads",
          "Windows Tablets",
          "Kids Tablets",
          "Drawing Tablets",
          "Gaming Tablets",
          "E-Readers",
          "Business Tablets",
          "Student Tablets",
          "Rugged Tablets",
        ],
      },
      {
        key: "wearables",
        name: "Wearables",
        attrs: [
          ATTR.brand_attr,
          ATTR.color,
          ATTR.display,
          ATTR.battery,
          ATTR.connectivity,
          ATTR.warranty,
        ],
        children: [
          "Smart Watches",
          "Fitness Bands",
          "Smart Rings",
          "Kids Smart Watches",
          "Sports Watches",
          "GPS Watches",
          "Hybrid Smart Watches",
          "Health Trackers",
          "ECG Watches",
          "Outdoor Watches",
        ],
      },
      {
        key: "camera",
        name: "Camera",
        attrs: [ATTR.brand_attr, ATTR.camera, ATTR.connectivity, ATTR.warranty],
        children: [
          "DSLR Cameras",
          "Mirrorless Cameras",
          "Point & Shoot Cameras",
          "Action Cameras",
          "Instant Cameras",
          "Drone Cameras",
          "Camera Lenses",
          "Tripods",
          "Camera Bags",
          "Camera Flashes",
        ],
      },
      {
        key: "storage",
        name: "Storage",
        attrs: [
          ATTR.brand_attr,
          ATTR.storage,
          ATTR.storage_type,
          ATTR.interface,
          ATTR.warranty,
        ],
        children: [
          "External SSD",
          "External Hard Drives",
          "Internal SSD",
          "Internal Hard Drives",
          "USB Flash Drives",
          "Memory Cards",
          "NAS Storage",
          "Portable SSD",
          "MicroSD Cards",
          "CFExpress Cards",
        ],
      },
      {
        key: "music-accessories",
        name: "Music Accessories",
        attrs: [ATTR.brand_attr, ATTR.color, ATTR.connectivity, ATTR.warranty],
        children: [
          "Headsets",
          "Chargers",
          "Power Banks",
          "Mobile Cases",
          "Keyboards",
          "Mouse",
          "Webcams",
          "Microphones",
          "Laptop Bags",
          "USB Hubs",
        ],
      },
      {
        key: "gaming",
        name: "Gaming",
        attrs: [
          ATTR.brand_attr,
          ATTR.color,
          ATTR.platform,
          ATTR.connectivity,
          ATTR.warranty,
        ],
        children: [
          "Gaming Consoles",
          "Gaming Controllers",
          "VR Headsets",
          "Gaming Chairs",
          "Gaming Desks",
          "Gaming Keyboards",
          "Gaming Mouse",
          "Gaming Headsets",
          "Gaming Monitors",
          "Racing Wheels",
        ],
      },
      {
        key: "smart-devices",
        name: "Smart Devices",
        attrs: [ATTR.brand_attr, ATTR.connectivity, ATTR.warranty],
        children: [
          "Smart Speakers",
          "Smart Bulbs",
          "Smart Plugs",
          "Security Cameras",
          "Smart Door Locks",
          "Video Doorbells",
          "Robot Vacuums",
          "Smart Sensors",
          "Smart Curtains",
          "Home Automation Hubs",
        ],
      },
    ],
  },

  {
    key: "fashion",
    name: "Fashion",
    order: 2,
    attrs: [ATTR.brand_attr],
    subs: [
      {
        key: "mens-topwear",
        name: "Men's Topwear",
        attrs: [
          ATTR.color,
          ATTR.size_apparel,
          ATTR.material,
          ATTR.fit,
          ATTR.pattern,
          ATTR.sleeve,
          ATTR.neckline,
          ATTR.collar,
          ATTR.occasion,
          ATTR.wash,
        ],
        children: [
          "Men T-Shirts",
          "Men Casual Shirts",
          "Men Formal Shirts",
          "Men Polo T-Shirts",
          "Men Hoodies",
          "Men Sweatshirts",
          "Men Jackets",
          "Men Blazers",
          "Men Sweaters",
          "Men Suits",
        ],
      },
      {
        key: "mens-bottomwear",
        name: "Men's Bottomwear",
        attrs: [
          ATTR.color,
          ATTR.size_apparel,
          ATTR.material,
          ATTR.fit,
          ATTR.pattern,
          ATTR.closure_type,
          ATTR.occasion,
          ATTR.wash,
        ],
        children: [
          "Men Jeans",
          "Men Casual Trousers",
          "Men Formal Trousers",
          "Men Cargos",
          "Men Shorts",
          "Men Track Pants",
          "Men Joggers",
          "Men Chinos",
          "Men Activewear",
          "Men Innerwear",
        ],
      },
      {
        key: "mens-ethnic-wear",
        name: "Men's Ethnic Wear",
        attrs: [
          ATTR.color,
          ATTR.size_apparel,
          ATTR.material,
          ATTR.fit,
          ATTR.pattern,
          ATTR.occasion,
          ATTR.wash,
        ],
        children: [
          "Men Kurtas",
          "Kurta Sets",
          "Nehru Jackets",
          "Sherwanis",
          "Pathani Suits",
          "Dhoti Pants",
          "Ethnic Jackets",
          "Sherwani Dupattas",
          "Bandhgalas",
          "Men Dhotis",
        ],
      },
      {
        key: "mens-footwear",
        name: "Men's Footwear",
        attrs: [
          ATTR.color,
          ATTR.size_shoes,
          ATTR.material,
          ATTR.closure_type,
          ATTR.occasion,
        ],
        children: [
          "Men Sports Shoes",
          "Men Sneakers",
          "Men Formal Shoes",
          "Men Casual Shoes",
          "Men Sandals",
          "Men Flip-Flops",
          "Men Loafers",
          "Men Boots",
          "Men Slippers",
          "Men Running Shoes",
        ],
      },
      {
        key: "mens-accessories",
        name: "Men's Accessories",
        attrs: [ATTR.color, ATTR.material],
        children: [
          "Men Watches",
          "Men Sunglasses",
          "Men Belts",
          "Men Wallets",
          "Men Caps",
          "Men Ties",
          "Men Bags",
          "Men Cufflinks",
          "Men Rings",
          "Men Bracelets",
        ],
      },

      {
        key: "womens-western-wear",
        name: "Women's Western Wear",
        attrs: [
          ATTR.color,
          ATTR.size_apparel,
          ATTR.material,
          ATTR.fit,
          ATTR.pattern,
          ATTR.neckline,
          ATTR.sleeve,
          ATTR.occasion,
          ATTR.wash,
        ],
        children: [
          "Women Tops",
          "Women T-Shirts",
          "Dresses",
          "Jumpsuits",
          "Shirts",
          "Skirts",
          "Co-ord Sets",
          "Blazers",
          "Sweaters",
          "Cardigans",
        ],
      },
      {
        key: "womens-bottomwear",
        name: "Women's Bottomwear",
        attrs: [
          ATTR.color,
          ATTR.size_apparel,
          ATTR.material,
          ATTR.fit,
          ATTR.pattern,
          ATTR.closure_type,
          ATTR.occasion,
          ATTR.wash,
        ],
        children: [
          "Women Jeans",
          "Women Trousers",
          "Leggings",
          "Palazzos",
          "Jeggings",
          "Shorts",
          "Joggers",
          "Track Pants",
          "Culottes",
          "Capris",
        ],
      },
      {
        key: "womens-ethnic-wear",
        name: "Women's Ethnic Wear",
        attrs: [
          ATTR.color,
          ATTR.size_apparel,
          ATTR.material,
          ATTR.fit,
          ATTR.pattern,
          ATTR.occasion,
          ATTR.wash,
        ],
        children: [
          "Sarees",
          "Kurtas",
          "Kurta Sets",
          "Salwar Suits",
          "Lehenga Cholis",
          "Anarkali Suits",
          "Dupattas",
          "Blouses",
          "Ethnic Skirts",
          "Dress Materials",
        ],
      },
      {
        key: "womens-footwear",
        name: "Women's Footwear",
        attrs: [
          ATTR.color,
          ATTR.size_shoes,
          ATTR.material,
          ATTR.closure_type,
          ATTR.occasion,
        ],
        children: [
          "Women Heels",
          "Women Flats",
          "Women Sneakers",
          "Women Sports Shoes",
          "Women Sandals",
          "Women Wedges",
          "Women Boots",
          "Women Bellies",
          "Women Slippers",
          "Women Loafers",
        ],
      },
      {
        key: "womens-accessories",
        name: "Women's Accessories",
        attrs: [ATTR.color, ATTR.material],
        children: [
          "Women Handbags",
          "Women Sling Bags",
          "Women Sunglasses",
          "Women Watches",
          "Women Wallets",
          "Hair Accessories",
          "Scarves",
          "Belts",
          "Women Clutches",
          "Women Backpacks",
        ],
      },
      {
        key: "womens-jewellery",
        name: "Women's Jewellery",
        attrs: [ATTR.color, ATTR.metal, ATTR.stone, ATTR.purity, ATTR.occasion],
        children: [
          "Earrings",
          "Necklaces",
          "Chains",
          "Rings",
          "Bangles",
          "Bracelets",
          "Jewellery Sets",
          "Pendants",
          "Nose Pins",
          "Anklets",
        ],
      },

      {
        key: "kids-clothing",
        name: "Kids' Clothing",
        attrs: [
          ATTR.age_group,
          ATTR.color,
          ATTR.size_apparel,
          ATTR.material,
          ATTR.fit,
          ATTR.pattern,
          ATTR.occasion,
          ATTR.wash,
        ],
        children: [
          "Boys T-Shirts",
          "Boys Shirts",
          "Boys Jeans",
          "Boys Shorts",
          "Girls Dresses",
          "Girls Tops",
          "Girls T-Shirts",
          "Girls Jeans",
          "Girls Skirts",
          "Kids Ethnic Wear",
        ],
      },
      {
        key: "infant-wear",
        name: "Infant Wear",
        attrs: [ATTR.age_group, ATTR.color, ATTR.material, ATTR.wash],
        children: [
          "Rompers",
          "Bodysuits",
          "Baby Sets",
          "Frocks",
          "Infant Nightwear",
          "Baby Caps",
          "Mittens and Booties",
          "Swaddles",
          "Baby Towels",
          "Baby Sleeping Bags",
        ],
      },
      {
        key: "kids-footwear",
        name: "Kids' Footwear",
        attrs: [
          ATTR.age_group,
          ATTR.color,
          ATTR.size_shoes,
          ATTR.material,
          ATTR.closure_type,
        ],
        children: [
          "Kids School Shoes",
          "Kids Sports Shoes",
          "Kids Sneakers",
          "Kids Sandals",
          "Kids Flip-Flops",
          "Kids Clogs",
          "Baby Booties",
          "Kids Slippers",
          "Kids Loafers",
          "Kids Boots",
        ],
      },
      {
        key: "kids-accessories",
        name: "Kids' Accessories",
        attrs: [ATTR.age_group, ATTR.color, ATTR.material],
        children: [
          "School Bags",
          "Lunch Boxes",
          "Kids Watches",
          "Kids Sunglasses",
          "Hair Bands",
          "Caps",
          "Belts",
          "Kids Water Bottles",
          "Kids Wallets",
          "Kids Ties",
        ],
      },

      {
        key: "bags-luggage",
        name: "Bags & Luggage",
        attrs: [ATTR.color, ATTR.material, ATTR.closure_type, ATTR.warranty],
        children: [
          "Laptop Backpacks",
          "School Backpacks",
          "Travel Backpacks",
          "Cabin Luggage",
          "Check-in Luggage",
          "Trolley Bags",
          "Duffle Bags",
          "Briefcases",
          "Messenger Bags",
          "Suitcases",
        ],
      },
    ],
  },
  {
    key: "beauty",
    name: "Beauty & Personal Care",
    order: 5,
    attrs: [ATTR.brand_attr, ATTR.country_origin],
    subs: [
      {
        key: "skincare",
        name: "Skin Care",
        attrs: [ATTR.skin_type, ATTR.concern, ATTR.formulation, ATTR.volume],
        children: [
          "Moisturizers & Creams",
          "Face Serums",
          "Sunscreens",
          "Face Wash & Cleansers",
          "Toners & Mists",
          "Eye Care",
          "Face Masks",
          "Scrubs & Exfoliators",
          "Lip Care",
          "Facial Oils",
        ],
      },
      {
        key: "grooming",
        name: "Grooming",
        attrs: [ATTR.formulation, ATTR.volume],
        children: [
          "Shaving Creams & Foams",
          "Razors & Cartridges",
          "Beard Oils",
          "Beard Washes",
          "Aftershaves",
          "Men's Face Wash",
          "Men's Moisturizers",
          "Hair Styling for Men",
          "Men's Trimmers",
          "Grooming Kits",
        ],
      },
      {
        key: "makeup",
        name: "Makeup",
        attrs: [ATTR.color, ATTR.skin_type, ATTR.formulation, ATTR.finish],
        children: [
          "Lipsticks & Glosses",
          "Foundations",
          "Concealers",
          "Compacts & Powders",
          "Eye Shadow Palettes",
          "Mascaras & Eyeliners",
          "Blushes & Bronzers",
          "Nail Polish",
          "Makeup Primers",
          "Makeup Removers",
        ],
      },
      {
        key: "perfume",
        name: "Perfume",
        attrs: [ATTR.gender, ATTR.fragrance_family, ATTR.volume],
        children: [
          "Perfumes for Women",
          "Perfumes for Men",
          "Unisex Perfumes",
          "Deodorants & Roll-Ons",
          "Body Mists",
          "Attars",
          "Luxury Perfumes",
          "Pocket Perfumes",
          "Solid Perfumes",
          "Fragrance Gift Sets",
        ],
      },
      {
        key: "bath-spa",
        name: "Bath & Spa",
        attrs: [ATTR.skin_type, ATTR.formulation, ATTR.volume],
        children: [
          "Body Washes",
          "Bath Soaps",
          "Body Lotions",
          "Body Scrubs",
          "Hand & Foot Creams",
          "Massage Oils",
          "Talcum Powders",
          "Bath Salts",
          "Body Butters",
          "Bath Sponges & Loofahs",
        ],
      },
      {
        key: "hygiene",
        name: "Hygiene",
        attrs: [ATTR.pack_size],
        children: [
          "Sanitary Pads",
          "Tampons",
          "Menstrual Cups",
          "Panty Liners",
          "Intimate Wash",
          "Feminine Wipes",
          "Period Panties",
          "Hand Sanitizers",
          "Hand Washes",
          "Hygiene Kits",
        ],
      },
      {
        key: "haircare",
        name: "Hair Care",
        attrs: [ATTR.formulation, ATTR.volume],
        children: [
          "Shampoos",
          "Conditioners",
          "Hair Oils",
          "Hair Serums",
          "Hair Masks",
          "Hair Colors",
          "Hair Styling Products",
          "Hair Sprays",
          "Dry Shampoos",
          "Hair Creams & Gels",
        ],
      },
      {
        key: "derma",
        name: "Derma",
        attrs: [ATTR.skin_type, ATTR.concern, ATTR.formulation, ATTR.volume],
        children: [
          "Acne Treatments",
          "Pigmentation Serums",
          "Eczema Creams",
          "Anti-Aging Treatments",
          "Rosacea Care",
          "Scar Gels",
          "Dermatologist Sunscreens",
          "Clinical Cleansers",
          "Peeling Solutions",
          "Stretch Mark Creams",
        ],
      },
      {
        key: "oral-care",
        name: "Oral Care",
        attrs: [ATTR.pack_size],
        children: [
          "Toothpaste",
          "Manual Toothbrushes",
          "Electric Toothbrushes",
          "Mouthwash",
          "Tongue Cleaners",
          "Dental Floss",
          "Teeth Whitening Products",
          "Kids Oral Care",
          "Denture Care",
          "Breath Fresheners",
        ],
      },
      {
        key: "beauty-supp",
        name: "Beauty Supp",
        attrs: [ATTR.pack_size],
        children: [
          "Collagen Powders",
          "Biotin Gummies",
          "Skin Glowing Vitamins",
          "Hair Growth Supplements",
          "Nail Health Vitamins",
          "Weight Management Supps",
          "Protein Powders",
          "Apple Cider Vinegar",
          "Green Tea Extracts",
          "Omega-3 for Skin",
        ],
      },
    ],
  },

  {
    key: "appliances",
    name: "Home Appliances",
    order: 6,
    attrs: [ATTR.brand_attr, ATTR.country_origin, ATTR.warranty],
    subs: [
      {
        key: "laundry",
        name: "Laundry",
        attrs: [
          ATTR.color,
          ATTR.load_type,
          ATTR.function_type,
          ATTR.washing_capacity,
          ATTR.energy_star,
          ATTR.inverter_technology,
          ATTR.warranty,
        ],
        children: [
          "Front Load Washing Machines",
          "Top Load Washing Machines",
          "Semi Automatic Washing Machines",
          "Fully Automatic Washing Machines",
          "Washer Dryers",
          "Portable Washing Machines",
          "Dry Irons",
          "Steam Irons",
          "Garment Steamers",
          "Ironing Boards",
        ],
      },
      {
        key: "heating",
        name: "Heating",
        attrs: [ATTR.color, ATTR.wattage, ATTR.voltage, ATTR.warranty],
        children: [
          "Instant Water Geysers",
          "Storage Water Geysers",
          "Gas Geysers",
          "Solar Water Heaters",
          "Immersion Rods",
          "Fan Heaters",
          "Oil-Filled Room Heaters",
          "Heat Convectors",
          "Quartz Heaters",
          "Halogen Heaters",
        ],
      },
      {
        key: "acs",
        name: "ACs",
        attrs: [
          ATTR.color,
          ATTR.ac_type,
          ATTR.tonnage,
          ATTR.energy_star,
          ATTR.inverter_technology,
          ATTR.room_size,
          ATTR.wattage,
          ATTR.warranty,
        ],
        children: [
          "Split ACs",
          "Window ACs",
          "Portable ACs",
          "Tower ACs",
          "Cassette ACs",
          "Hot & Cold ACs",
          "Smart ACs",
          "Commercial ACs",
          "Multi-Split ACs",
          "Inverter ACs",
        ],
      },
      {
        key: "fans",
        name: "Fans",
        attrs: [
          ATTR.color,
          ATTR.fan_type,
          ATTR.air_delivery,
          ATTR.wattage,
          ATTR.voltage,
          ATTR.energy_star,
          ATTR.warranty,
        ],
        children: [
          "Ceiling Fans",
          "Table Fans",
          "Pedestal Fans",
          "Wall Fans",
          "Exhaust Fans",
          "Tower Fans",
          "BLDC Fans",
          "Designer Fans",
          "Smart Fans",
          "Rechargeable Fans",
        ],
      },
      {
        key: "dishwashers",
        name: "Dishwashers",
        attrs: [
          ATTR.color,
          ATTR.energy_star,
          ATTR.wattage,
          ATTR.voltage,
          ATTR.warranty,
        ],
        children: [
          "Freestanding Dishwashers",
          "Built-in Dishwashers",
          "Countertop Dishwashers",
          "Portable Dishwashers",
          "Compact Dishwashers",
          "Smart Dishwashers",
          "Dishwasher Detergents",
          "Dishwasher Salt",
          "Dishwasher Rinse Aids",
          "Dishwasher Cleaners",
        ],
      },
      {
        key: "microwaves",
        name: "Microwaves",
        attrs: [
          ATTR.color,
          ATTR.microwave_type,
          ATTR.capacity_ltr,
          ATTR.wattage,
          ATTR.voltage,
          ATTR.warranty,
        ],
        children: [
          "Solo Microwave Ovens",
          "Grill Microwave Ovens",
          "Convection Microwave Ovens",
          "Countertop Microwave Ovens",
          "Commercial Microwave Ovens",
          "OTG Ovens",
          "Air Fryer Ovens",
          "Microwave Cookware",
          "Microwave Oven Stands",
          "Microwave Covers",
        ],
      },
      {
        key: "fridges",
        name: "Fridges",
        attrs: [
          ATTR.color,
          ATTR.refrigerator_type,
          ATTR.capacity_ltr,
          ATTR.freezer_position,
          ATTR.energy_star,
          ATTR.inverter_technology,
          ATTR.warranty,
        ],
        children: [
          "Single Door Refrigerators",
          "Double Door Refrigerators",
          "Triple Door Refrigerators",
          "Side-by-Side Refrigerators",
          "French Door Refrigerators",
          "Bottom Freezer Refrigerators",
          "Mini Refrigerators",
          "Convertible Refrigerators",
          "Wine Coolers",
          "Deep Freezers",
        ],
      },
      {
        key: "home",
        name: "Home",
        attrs: [ATTR.color, ATTR.wattage, ATTR.voltage, ATTR.warranty],
        children: [
          "RO Water Purifiers",
          "UV Water Purifiers",
          "Water Dispensers",
          "Canister Vacuum Cleaners",
          "Robot Vacuum Cleaners",
          "Handheld Vacuum Cleaners",
          "Air Purifiers",
          "Dehumidifiers",
          "Inverters",
          "Voltage Stabilizers",
        ],
      },
      {
        key: "kitchen",
        name: "Kitchen",
        attrs: [
          ATTR.color,
          ATTR.capacity_ltr,
          ATTR.wattage,
          ATTR.voltage,
          ATTR.warranty,
        ],
        children: [
          "Mixer Grinders",
          "Juicer Mixer Grinders",
          "Air Fryers",
          "Induction Cooktops",
          "Electric Kettles",
          "Toasters",
          "Food Processors",
          "Coffee Makers",
          "Sandwich Makers",
          "Electric Cookers",
        ],
      },
      {
        key: "built-in",
        name: "Built-In",
        attrs: [
          ATTR.color,
          ATTR.wattage,
          ATTR.voltage,
          ATTR.finish,
          ATTR.warranty,
        ],
        children: [
          "Wall-Mounted Chimneys",
          "Island Chimneys",
          "Built-in Chimneys",
          "Auto-Clean Chimneys",
          "Gas Hobs",
          "Built-in Hobs",
          "Induction Hobs",
          "Built-in Microwave Ovens",
          "Built-in Dishwashers",
          "Chimney Filters",
        ],
      },
    ],
  },

  {
    key: "home-kitchen",
    name: "Home",
    order: 7,
    attrs: [ATTR.brand_attr, ATTR.country_origin],
    subs: [
      {
        key: "cookware",
        name: "Cookware",
        attrs: [
          ATTR.color,
          ATTR.material,
          ATTR.finish,
          ATTR.capacity_ltr,
          ATTR.diameter,
          ATTR.set_size,
          ATTR.cookware_compatibility,
          ATTR.non_stick,
        ],
        children: [
          "Pressure Cookers",
          "Frying Pans",
          "Kadhai & Woks",
          "Saucepans",
          "Cookware Sets",
          "Tawas",
          "Kitchen Knives",
          "Choppers & Slicers",
          "Spatulas & Ladles",
          "Gas Lighters",
        ],
      },
      {
        key: "kitchen-storage",
        name: "Kitchen Storage",
        attrs: [
          ATTR.color,
          ATTR.material,
          ATTR.capacity_ltr,
          ATTR.set_size,
          ATTR.closure_type,
        ],
        children: [
          "Food Storage Containers",
          "Lunch Boxes",
          "Water Bottles",
          "Kitchen Jars",
          "Kitchen Racks & Holders",
          "Oil Dispensers",
          "Spice Boxes",
          "Casseroles",
          "Tiffin Boxes",
          "Thermos Flasks",
        ],
      },
      {
        key: "tableware",
        name: "Tableware",
        attrs: [ATTR.color, ATTR.material, ATTR.finish, ATTR.set_size],
        children: [
          "Dinner Sets",
          "Plates",
          "Bowls",
          "Cups & Mugs",
          "Glassware",
          "Serving Trays",
          "Cutlery Sets",
          "Tea & Coffee Sets",
          "Serving Bowls",
          "Drinkware",
        ],
      },
      {
        key: "home-furnishing",
        name: "Home Furnishing",
        attrs: [ATTR.color, ATTR.material, ATTR.pattern, ATTR.wash],
        children: [
          "Bedsheets",
          "Curtains",
          "Cushion Covers",
          "Blankets",
          "Comforters",
          "Pillow Covers",
          "Doormats",
          "Carpets & Rugs",
          "Sofa Covers",
          "Mattress Protectors",
        ],
      },
      {
        key: "home-decor",
        name: "Home Decor",
        attrs: [ATTR.color, ATTR.material, ATTR.finish],
        children: [
          "Wall Art",
          "Wall Clocks",
          "Vases",
          "Candles",
          "Photo Frames",
          "Decorative Lamps",
          "Artificial Plants",
          "Wall Shelves",
          "Showpieces",
          "Wall Stickers",
        ],
      },
      {
        key: "lighting",
        name: "Lighting",
        attrs: [
          ATTR.color,
          ATTR.material,
          ATTR.light_source,
          ATTR.wattage,
          ATTR.voltage,
          ATTR.warranty,
        ],
        children: [
          "LED Bulbs",
          "Tube Lights",
          "Ceiling Lights",
          "Table Lamps",
          "Wall Lights",
          "String Lights",
          "Emergency Lights",
          "Night Lamps",
          "Outdoor Lights",
          "Decorative Bulbs",
        ],
      },
      {
        key: "bathroom",
        name: "Bathroom",
        attrs: [ATTR.color, ATTR.material, ATTR.set_size],
        children: [
          "Bath Towels",
          "Hand Towels",
          "Bathrobes",
          "Bath Mats",
          "Soap Dispensers",
          "Soap Dishes",
          "Toothbrush Holders",
          "Bathroom Shelves",
          "Shower Caddies",
          "Shower Curtains",
        ],
      },
      {
        key: "cleaning",
        name: "Cleaning",
        attrs: [ATTR.pack_size],
        children: [
          "Floor Cleaners",
          "Bathroom Cleaners",
          "Kitchen Cleaners",
          "Laundry Detergents",
          "Dishwashing Products",
          "Mops",
          "Brooms",
          "Garbage Bags",
          "Cleaning Brushes",
          "Sponges & Wipes",
        ],
      },
      {
        key: "gardening",
        name: "Gardening",
        attrs: [ATTR.color, ATTR.material, ATTR.capacity_ltr],
        children: [
          "Plant Pots",
          "Planters",
          "Gardening Tools",
          "Watering Cans",
          "Garden Hoses",
          "Plant Stands",
          "Grow Bags",
          "Garden Sprayers",
          "Gardening Gloves",
          "Live Plants",
        ],
      },
      {
        key: "pooja-essentials",
        name: "Pooja Essentials",
        attrs: [ATTR.color, ATTR.material],
        children: [
          "Diyas",
          "Incense Sticks",
          "Pooja Thalis",
          "God Idols",
          "Camphor",
          "Prayer Bells",
          "Oil Lamps",
          "Rangoli Colors",
          "Pooja Kits",
          "Cotton Wicks",
        ],
      },
    ],
  },

  {
    key: "furniture",
    name: "Furniture",
    order: 8,
    attrs: [ATTR.brand_attr, ATTR.country_origin, ATTR.warranty],
    subs: [
      {
        key: "bedroom-furniture",
        name: "Bedroom Furniture",
        attrs: [
          ATTR.material_furniture,
          ATTR.finish,
          ATTR.delivery_condition,
          ATTR.assembly,
          ATTR.width,
          ATTR.height_attr,
          ATTR.depth,
          ATTR.warranty,
        ],
        children: [
          "Beds",
          "Wardrobes",
          "Bedside Tables",
          "Dressing Tables",
          "Chest of Drawers",
          "Headboards",
          "Bedroom Benches",
          "Bedroom Sets",
          "Vanity Tables",
          "Bunk Beds",
        ],
      },
      {
        key: "living-room-furniture",
        name: "Living Room Furniture",
        attrs: [
          ATTR.material_furniture,
          ATTR.finish,
          ATTR.delivery_condition,
          ATTR.assembly,
          ATTR.width,
          ATTR.height_attr,
          ATTR.depth,
          ATTR.warranty,
        ],
        children: [
          "Sofas",
          "Sofa Beds",
          "Recliners",
          "TV Units",
          "Coffee Tables",
          "Side Tables",
          "Bean Bags",
          "Ottomans",
          "Display Units",
          "Center Tables",
        ],
      },
      {
        key: "dining-furniture",
        name: "Dining Furniture",
        attrs: [
          ATTR.material_furniture,
          ATTR.finish,
          ATTR.seating_capacity,
          ATTR.delivery_condition,
          ATTR.assembly,
          ATTR.width,
          ATTR.height_attr,
          ATTR.depth,
          ATTR.warranty,
        ],
        children: [
          "Dining Sets",
          "Dining Tables",
          "Dining Chairs",
          "Dining Benches",
          "Bar Cabinets",
          "Bar Stools",
          "Crockery Units",
          "Kitchen Trolleys",
          "Dining Buffets",
          "Folding Dining Tables",
        ],
      },
      {
        key: "office-study-furniture",
        name: "Office & Study Furniture",
        attrs: [
          ATTR.material_furniture,
          ATTR.finish,
          ATTR.delivery_condition,
          ATTR.assembly,
          ATTR.width,
          ATTR.height_attr,
          ATTR.depth,
          ATTR.warranty,
        ],
        children: [
          "Office Chairs",
          "Ergonomic Chairs",
          "Study Tables",
          "Computer Tables",
          "Office Desks",
          "Bookshelves",
          "Filing Cabinets",
          "Laptop Tables",
          "Study Chairs",
          "Conference Tables",
        ],
      },
      {
        key: "storage-furniture",
        name: "Storage Furniture",
        attrs: [
          ATTR.material_furniture,
          ATTR.finish,
          ATTR.delivery_condition,
          ATTR.assembly,
          ATTR.width,
          ATTR.height_attr,
          ATTR.depth,
          ATTR.warranty,
        ],
        children: [
          "Storage Cabinets",
          "Sideboards",
          "Bookcases",
          "Shoe Racks",
          "Wall Shelves",
          "Corner Cabinets",
          "Display Cabinets",
          "Collapsible Wardrobes",
          "Utility Cabinets",
          "Trunks & Boxes",
        ],
      },
      {
        key: "kids-furniture",
        name: "Kids' Furniture",
        attrs: [
          ATTR.material_furniture,
          ATTR.finish,
          ATTR.delivery_condition,
          ATTR.assembly,
          ATTR.width,
          ATTR.height_attr,
          ATTR.depth,
          ATTR.warranty,
        ],
        children: [
          "Kids Beds",
          "Kids Study Tables",
          "Kids Chairs",
          "Toy Storage Units",
          "Kids Wardrobes",
          "Activity Tables",
          "Baby Cradles",
          "Kids Furniture Sets",
          "Kids Bookshelves",
          "Nursing Chairs",
        ],
      },
      {
        key: "outdoor-furniture",
        name: "Outdoor Furniture",
        attrs: [
          ATTR.material_furniture,
          ATTR.finish,
          ATTR.seating_capacity,
          ATTR.delivery_condition,
          ATTR.assembly,
          ATTR.width,
          ATTR.height_attr,
          ATTR.depth,
          ATTR.warranty,
        ],
        children: [
          "Patio Chairs",
          "Garden Tables",
          "Outdoor Sofas",
          "Garden Swings",
          "Hammocks",
          "Folding Chairs",
          "Outdoor Benches",
          "Balcony Sets",
          "Outdoor Loungers",
          "Gazebos",
        ],
      },
      {
        key: "mattresses-bedding",
        name: "Mattresses & Bedding",
        attrs: [
          ATTR.bedding_size,
          ATTR.mattress_type,
          ATTR.firmness,
          ATTR.width,
          ATTR.height_attr,
          ATTR.depth,
          ATTR.warranty,
        ],
        children: [
          "Memory Foam Mattresses",
          "Orthopedic Mattresses",
          "Spring Mattresses",
          "Coir Mattresses",
          "Latex Mattresses",
          "Hybrid Mattresses",
          "Mattress Protectors",
          "Mattress Toppers",
          "Bed Wedges",
          "Futon Mattresses",
        ],
      },
      {
        key: "pooja-furniture",
        name: "Pooja Furniture",
        attrs: [
          ATTR.material_furniture,
          ATTR.finish,
          ATTR.delivery_condition,
          ATTR.assembly,
          ATTR.width,
          ATTR.height_attr,
          ATTR.depth,
          ATTR.warranty,
        ],
        children: [
          "Wooden Temples",
          "Marble Temples",
          "Metal Temples",
          "Wall Mounted Temples",
          "Pooja Chowkis",
          "Pooja Shelves",
          "Singhasans",
          "Pooja Mandapas",
          "Pooja Cabinets",
          "Pooja Stools",
        ],
      },
      {
        key: "accent-furniture",
        name: "Accent Furniture",
        attrs: [
          ATTR.material_furniture,
          ATTR.finish,
          ATTR.delivery_condition,
          ATTR.assembly,
          ATTR.width,
          ATTR.height_attr,
          ATTR.depth,
          ATTR.warranty,
        ],
        children: [
          "Console Tables",
          "Nested Tables",
          "Pouffes",
          "Accent Chairs",
          "Rocking Chairs",
          "Room Dividers",
          "Plant Stands",
          "Magazine Racks",
          "Entryway Benches",
          "Lounge Chairs",
        ],
      },
    ],
  },

  {
    key: "food-beverages",
    name: "Food & Beverages",
    order: 9,
    attrs: [ATTR.brand_attr, ATTR.country_origin],
    subs: [
      {
        key: "breakfast-cereals",
        name: "Breakfast Cereals",
        attrs: [
          ATTR.flavor,
          ATTR.pack_size,
          ATTR.item_weight,
          ATTR.shelf_life,
          ATTR.veg_nonveg,
          ATTR.dietary_preference,
          ATTR.container_type,
        ],
        children: [
          "Cornflakes",
          "Muesli",
          "Oats",
          "Granola",
          "Chocos",
          "Porridge",
          "Pancake Mixes",
          "Breakfast Bars",
          "Multigrain Cereals",
        ],
      },
      {
        key: "oils-ghees",
        name: "Oils & Ghees",
        attrs: [
          ATTR.pack_size,
          ATTR.volume,
          ATTR.item_weight,
          ATTR.shelf_life,
          ATTR.veg_nonveg,
          ATTR.dietary_preference,
          ATTR.container_type,
        ],
        children: [
          "Sunflower Oil",
          "Mustard Oil",
          "Groundnut Oil",
          "Rice Bran Oil",
          "Olive Oil",
          "Coconut Oil",
          "Desi Ghee",
          "Cow Ghee",
          "Vanaspati",
        ],
      },
      {
        key: "teas-coffees",
        name: "Teas & Coffees",
        attrs: [
          ATTR.flavor,
          ATTR.pack_size,
          ATTR.item_weight,
          ATTR.shelf_life,
          ATTR.veg_nonveg,
          ATTR.dietary_preference,
          ATTR.container_type,
        ],
        children: [
          "Tea Powder",
          "Tea Bags",
          "Green Tea",
          "Herbal Tea",
          "Instant Coffee",
          "Filter Coffee",
          "Coffee Beans",
          "Cold Coffee Mixes",
          "Premium Tea & Coffee",
        ],
      },
      {
        key: "edible-seeds",
        name: "Edible Seeds",
        attrs: [
          ATTR.pack_size,
          ATTR.item_weight,
          ATTR.shelf_life,
          ATTR.veg_nonveg,
          ATTR.dietary_preference,
          ATTR.container_type,
          ATTR.organic_certified,
        ],
        children: [
          "Chia Seeds",
          "Flax Seeds",
          "Pumpkin Seeds",
          "Sunflower Seeds",
          "Watermelon Seeds",
          "Sesame Seeds",
          "Basil Seeds",
          "Quinoa",
          "Seed Mixes",
        ],
      },
      {
        key: "chocolates",
        name: "Chocolates",
        attrs: [
          ATTR.flavor,
          ATTR.pack_size,
          ATTR.item_weight,
          ATTR.shelf_life,
          ATTR.veg_nonveg,
          ATTR.dietary_preference,
          ATTR.container_type,
        ],
        children: [
          "Chocolate Bars",
          "Dark Chocolates",
          "Milk Chocolates",
          "Premium Chocolates",
          "Chocolate Gift Packs",
          "Wafer Chocolates",
          "Chocolate Spreads",
          "Choco Chips",
          "Imported Chocolates",
        ],
      },
      {
        key: "gourmet-specials",
        name: "Gourmet Specials",
        attrs: [
          ATTR.flavor,
          ATTR.pack_size,
          ATTR.item_weight,
          ATTR.shelf_life,
          ATTR.veg_nonveg,
          ATTR.dietary_preference,
          ATTR.container_type,
        ],
        children: [
          "Gourmet Sauces",
          "Imported Snacks",
          "Premium Pasta",
          "Olives & Pickles",
          "Gourmet Cheese",
          "Exotic Spices",
          "Premium Dry Fruits",
          "Gourmet Coffee",
          "Gift Hampers",
        ],
      },
      {
        key: "summer-specials",
        name: "Summer Specials",
        attrs: [
          ATTR.flavor,
          ATTR.pack_size,
          ATTR.volume,
          ATTR.shelf_life,
          ATTR.veg_nonveg,
          ATTR.dietary_preference,
          ATTR.container_type,
        ],
        children: [
          "Squashes & Syrups",
          "Fruit Juices",
          "Instant Drink Mixes",
          "Cold Coffee",
          "Iced Tea",
          "Coconut Water",
          "Energy Drinks",
          "Packaged Water",
          "Soda & Mixers",
        ],
      },
      {
        key: "dry-fruits-nuts",
        name: "Dry Fruits",
        attrs: [
          ATTR.pack_size,
          ATTR.item_weight,
          ATTR.shelf_life,
          ATTR.veg_nonveg,
          ATTR.dietary_preference,
          ATTR.container_type,
        ],
        children: [
          "Almonds",
          "Cashews",
          "Pistachios",
          "Walnuts",
          "Raisins",
          "Dates",
          "Seeds",
          "Mixed Dry Fruits",
          "Trail Mixes",
        ],
      },
      {
        key: "nutrition-drinks",
        name: "Nutrition Drinks",
        attrs: [
          ATTR.flavor,
          ATTR.pack_size,
          ATTR.volume,
          ATTR.item_weight,
          ATTR.shelf_life,
          ATTR.veg_nonveg,
          ATTR.dietary_preference,
          ATTR.container_type,
        ],
        children: [
          "Health Drink Powders",
          "Malt Drinks",
          "Kids Nutrition Drinks",
          "Women Nutrition Drinks",
          "Diabetic Nutrition",
          "Meal Replacement Drinks",
          "Energy Drink Powders",
          "Protein Drinks",
          "Nutrition Shakes",
        ],
      },
      {
        key: "proteins",
        name: "Proteins",
        attrs: [
          ATTR.flavor,
          ATTR.pack_size,
          ATTR.item_weight,
          ATTR.shelf_life,
          ATTR.veg_nonveg,
          ATTR.dietary_preference,
          ATTR.container_type,
        ],
        children: [
          "Whey Protein",
          "Plant Protein",
          "Mass Gainers",
          "Protein Bars",
          "Protein Cookies",
          "Protein Shakes",
          "BCAA",
          "Creatine",
          "Pre-Workout",
        ],
      },
      {
        key: "medical-supplies",
        name: "Medical Supplies",
        attrs: [],
        children: [
          "Thermometers",
          "Oximeters",
          "BP Monitors",
          "Glucometers",
          "Test Strips",
          "First Aid Kits",
          "Masks",
          "Sanitizers",
          "Pain Relief Sprays",
        ],
      },
      {
        key: "vitamin-supplements",
        name: "Vitamin Supplements",
        attrs: [
          ATTR.pack_size,
          ATTR.item_weight,
          ATTR.shelf_life,
          ATTR.veg_nonveg,
          ATTR.dietary_preference,
          ATTR.container_type,
        ],
        children: [
          "Multivitamins",
          "Vitamin C",
          "Vitamin D",
          "Calcium Supplements",
          "Iron Supplements",
          "Omega 3",
          "Immunity Boosters",
          "Biotin",
          "Probiotics",
        ],
      },
      {
        key: "ayurveda-more",
        name: "Ayurveda & More",
        attrs: [
          ATTR.pack_size,
          ATTR.item_weight,
          ATTR.volume,
          ATTR.shelf_life,
          ATTR.veg_nonveg,
          ATTR.dietary_preference,
          ATTR.container_type,
        ],
        children: [
          "Chyawanprash",
          "Ayurvedic Juices",
          "Herbal Supplements",
          "Honey",
          "Amla Products",
          "Digestive Care",
          "Herbal Teas",
          "Ayurvedic Oils",
          "Wellness Powders",
        ],
      },
      {
        key: "household-supplies",
        name: "Household Supplies",
        attrs: [
          ATTR.pack_size,
          ATTR.item_weight,
          ATTR.volume,
          ATTR.container_type,
        ],
        children: [
          "Laundry Detergents",
          "Dishwash Liquids",
          "Floor Cleaners",
          "Toilet Cleaners",
          "Air Fresheners",
          "Garbage Bags",
          "Paper Napkins",
          "Kitchen Towels",
          "Insect Repellents",
        ],
      },
      {
        key: "new-brands",
        name: "New Brands",
        attrs: [
          ATTR.pack_size,
          ATTR.item_weight,
          ATTR.shelf_life,
          ATTR.veg_nonveg,
          ATTR.dietary_preference,
          ATTR.container_type,
        ],
        children: [
          "New Snacks",
          "New Beverages",
          "New Breakfast Foods",
          "New Health Foods",
          "New Gourmet Products",
          "New Chocolates",
          "New Organic Foods",
          "New Staples",
          "New Personal Care",
        ],
      },
      {
        key: "pet-essentials",
        name: "Pet Essentials",
        attrs: [ATTR.pack_size, ATTR.item_weight],
        children: [
          "Dog Food",
          "Cat Food",
          "Pet Treats",
          "Pet Bowls",
          "Pet Grooming",
          "Pet Shampoo",
          "Pet Toys",
          "Pet Beds",
          "Pet Litter",
        ],
      },
    ],
  },

  {
    key: "sports",
    name: "Sports & Fitness",
    order: 11,
    attrs: [ATTR.brand_attr],
    subs: [
      {
        key: "badminton",
        name: "Badminton",
        attrs: [
          ATTR.color,
          ATTR.material,
          ATTR.skill_level,
          ATTR.playing_level,
        ],
        children: [
          "Badminton Racquets",
          "Badminton Shuttlecocks",
          "Badminton Shoes",
          "Badminton Nets",
          "Racquet Grips",
          "Racquet Covers",
          "Badminton Kits",
          "Training Shuttlecocks",
          "Badminton Accessories",
        ],
      },
      {
        key: "fitness",
        name: "Fitness",
        attrs: [
          ATTR.color,
          ATTR.material,
          ATTR.item_weight,
          ATTR.weight_kg,
          ATTR.warranty,
        ],
        children: [
          "Dumbbells",
          "Resistance Bands",
          "Skipping Ropes",
          "Fitness Benches",
          "Kettlebells",
          "Pull-Up Bars",
          "Ab Exercisers",
          "Push-Up Bars",
          "Gym Gloves",
        ],
      },
      {
        key: "cricket-gear",
        name: "Cricket Gear",
        attrs: [
          ATTR.color,
          ATTR.material,
          ATTR.skill_level,
          ATTR.playing_level,
        ],
        children: [
          "Cricket Bats",
          "Cricket Balls",
          "Batting Gloves",
          "Batting Pads",
          "Cricket Helmets",
          "Cricket Kits",
          "Wicket Sets",
          "Cricket Shoes",
          "Cricket Bags",
        ],
      },
      {
        key: "cycling",
        name: "Cycling",
        attrs: [
          ATTR.color,
          ATTR.material,
          ATTR.cycle_size,
          ATTR.gear_count,
          ATTR.age_group,
          ATTR.warranty,
        ],
        children: [
          "Mountain Bikes",
          "Road Bikes",
          "Hybrid Cycles",
          "Electric Cycles",
          "Kids Cycles",
          "Cycling Helmets",
          "Cycle Lights",
          "Cycle Pumps",
          "Cycle Locks",
        ],
      },
      {
        key: "yoga",
        name: "Yoga",
        attrs: [ATTR.color, ATTR.material],
        children: [
          "Yoga Mats",
          "Yoga Blocks",
          "Yoga Straps",
          "Meditation Cushions",
          "Yoga Bolsters",
          "Foam Rollers",
          "Yoga Wheels",
          "Mat Bags",
          "Yoga Towels",
        ],
      },
      {
        key: "running",
        name: "Running",
        attrs: [ATTR.color, ATTR.material],
        children: [
          "Running Shoes",
          "Running T-Shirts",
          "Running Shorts",
          "Running Armbands",
          "Hydration Belts",
          "Running Socks",
          "Running Caps",
          "Running Jackets",
          "Running Accessories",
        ],
      },
      {
        key: "swimming",
        name: "Swimming",
        attrs: [ATTR.color, ATTR.size_apparel, ATTR.material, ATTR.skill_level],
        children: [
          "Swimwear",
          "Swimming Goggles",
          "Swimming Caps",
          "Kickboards",
          "Pool Floats",
          "Swimming Towels",
          "Ear Plugs",
          "Training Fins",
          "Swimming Accessories",
        ],
      },
      {
        key: "kids-cycles",
        name: "Kids' Cycles",
        attrs: [
          ATTR.color,
          ATTR.material,
          ATTR.cycle_size,
          ATTR.gear_count,
          ATTR.age_group,
          ATTR.warranty,
        ],
        children: [
          "Kids Bicycles",
          "Baby Tricycles",
          "Balance Bikes",
          "Training Wheel Cycles",
          "Kids Scooters",
          "Kids Helmets",
          "Kids Cycle Bells",
          "Kids Cycle Lights",
          "Kids Ride-Ons",
        ],
      },
      {
        key: "exercise-bike",
        name: "Exercise Bike",
        attrs: [ATTR.color, ATTR.material, ATTR.weight_kg, ATTR.warranty],
        children: [
          "Upright Exercise Bikes",
          "Spin Bikes",
          "Recumbent Bikes",
          "Air Bikes",
          "Mini Exercise Bikes",
          "Magnetic Exercise Bikes",
          "Foldable Exercise Bikes",
          "Bike Seats",
          "Exercise Bike Accessories",
        ],
      },
      {
        key: "protein-supplements",
        name: "Protein Supplements",
        attrs: [
          ATTR.flavor,
          ATTR.pack_size,
          ATTR.item_weight,
          ATTR.dietary_preference,
          ATTR.container_type,
        ],
        children: [
          "Whey Protein",
          "Plant Protein",
          "Mass Gainers",
          "Protein Bars",
          "Protein Shakes",
          "BCAA Supplements",
          "Creatine",
          "Pre Workout",
          "Post Workout Recovery",
        ],
      },
    ],
  },

  {
    key: "books",
    name: "Books & Media",
    order: 12,
    attrs: [],
    subs: [
      {
        key: "childrens-books",
        name: "Children Books",
        attrs: [
          ATTR.language,
          ATTR.pages,
          ATTR.format,
          ATTR.author,
          ATTR.publisher,
          ATTR.publication_year,
          ATTR.isbn,
          ATTR.age_group,
        ],
        children: [
          "Picture Books",
          "Story Books",
          "Activity Books",
          "Early Learning Books",
          "Board Books",
          "Coloring Books",
          "Children Encyclopedias",
          "Young Adult Books",
          "Bedtime Stories",
        ],
      },
      {
        key: "exam-prep",
        name: "Exam Prep",
        attrs: [
          ATTR.language,
          ATTR.pages,
          ATTR.format,
          ATTR.author,
          ATTR.publisher,
          ATTR.publication_year,
          ATTR.isbn,
        ],
        children: [
          "UPSC Books",
          "SSC Books",
          "Banking Exam Books",
          "Railway Exam Books",
          "JEE Books",
          "NEET Books",
          "GATE Books",
          "CAT & MBA Entrance Books",
          "Teaching Exam Books",
        ],
      },
      {
        key: "fiction",
        name: "Fiction",
        attrs: [
          ATTR.language,
          ATTR.pages,
          ATTR.format,
          ATTR.author,
          ATTR.publisher,
          ATTR.publication_year,
          ATTR.isbn,
        ],
        children: [
          "Romance",
          "Mystery & Thriller",
          "Science Fiction",
          "Fantasy",
          "Classics",
          "Historical Fiction",
          "Literary Fiction",
          "Short Stories",
          "Horror",
        ],
      },
      {
        key: "comics",
        name: "Comics",
        attrs: [
          ATTR.language,
          ATTR.pages,
          ATTR.format,
          ATTR.author,
          ATTR.publisher,
          ATTR.publication_year,
          ATTR.isbn,
          ATTR.age_group,
        ],
        children: [
          "Superhero Comics",
          "Manga",
          "Graphic Novels",
          "Kids Comics",
          "Indian Comics",
          "Comic Boxsets",
          "Humour Comics",
          "Adventure Comics",
          "Collector Comics",
        ],
      },
      {
        key: "boxsets",
        name: "Boxsets",
        attrs: [
          ATTR.language,
          ATTR.pages,
          ATTR.format,
          ATTR.author,
          ATTR.publisher,
          ATTR.publication_year,
          ATTR.isbn,
        ],
        children: [
          "Fiction Boxsets",
          "Children Book Boxsets",
          "Comic Boxsets",
          "Harry Potter Boxsets",
          "Academic Boxsets",
          "Manga Boxsets",
          "Classic Literature Boxsets",
          "Self Help Boxsets",
          "Gift Boxsets",
        ],
      },
      {
        key: "guitars",
        name: "Guitars",
        attrs: [
          ATTR.brand_attr,
          ATTR.color,
          ATTR.material,
          ATTR.skill_level,
          ATTR.warranty,
        ],
        children: [
          "Acoustic Guitars",
          "Electric Guitars",
          "Bass Guitars",
          "Classical Guitars",
          "Semi-Acoustic Guitars",
          "Kids Guitars",
          "Guitar Combos",
          "Guitar Strings",
          "Guitar Picks",
        ],
      },
      {
        key: "keyboards",
        name: "Keyboards",
        attrs: [
          ATTR.brand_attr,
          ATTR.color,
          ATTR.material,
          ATTR.skill_level,
          ATTR.warranty,
        ],
        children: [
          "Musical Keyboards",
          "Digital Pianos",
          "Synthesizers",
          "MIDI Keyboards",
          "Keyboard Stands",
          "Keyboard Adapters",
          "Keyboard Bags",
          "Beginner Keyboards",
          "Professional Keyboards",
        ],
      },
      {
        key: "microphones",
        name: "Microphones",
        attrs: [
          ATTR.brand_attr,
          ATTR.color,
          ATTR.connectivity,
          ATTR.microphone,
          ATTR.compatible_device,
          ATTR.warranty,
        ],
        children: [
          "Wired Microphones",
          "Wireless Microphones",
          "Karaoke Microphones",
          "Studio Microphones",
          "Condenser Microphones",
          "Dynamic Microphones",
          "Lapel Microphones",
          "USB Microphones",
          "Microphone Stands",
        ],
      },
      {
        key: "instruments",
        name: "Instruments",
        attrs: [
          ATTR.brand_attr,
          ATTR.color,
          ATTR.material,
          ATTR.skill_level,
          ATTR.warranty,
        ],
        children: [
          "Tabla",
          "Harmonium",
          "Flutes",
          "Violins",
          "Drums",
          "Ukuleles",
          "Saxophones",
          "Cajons",
          "Percussion Instruments",
        ],
      },
      {
        key: "accessories",
        name: "Accessories",
        attrs: [
          ATTR.brand_attr,
          ATTR.color,
          ATTR.material,
          ATTR.compatible_device,
        ],
        children: [
          "Music Stands",
          "Instrument Stands",
          "Guitar Capos",
          "Instrument Cables",
          "Tuners",
          "Metronomes",
          "Sheet Music Stands",
          "Instrument Bags",
          "Audio Adapters",
        ],
      },
    ],
  },

  {
    key: "toys",
    name: "Toys & Baby Products",
    order: 13,
    attrs: [ATTR.brand_attr, ATTR.country_origin],
    subs: [
      {
        key: "baby-diapers",
        name: "Diaper",
        attrs: [ATTR.diaper_size, ATTR.baby_weight_range, ATTR.pack_size],
        children: [
          "Tape Diapers",
          "Pant Style Diapers",
          "Overnight Diapers",
          "Swim Diapers",
          "Cloth Diapers",
          "Newborn Diapers",
          "Premium Diapers",
          "Diaper Inserts",
          "Diaper Pants Combos",
        ],
      },
      {
        key: "baby-skin-hair-care",
        name: "Skin & Hair Care",
        attrs: [ATTR.age_group, ATTR.skin_type, ATTR.formulation, ATTR.volume],
        children: [
          "Baby Lotions",
          "Baby Creams",
          "Baby Oils",
          "Baby Wash & Shampoo",
          "Baby Soap",
          "Baby Hair Oil",
          "Baby Powder",
          "Baby Sunscreen",
          "Baby Grooming Kits",
        ],
      },
      {
        key: "baby-bedding",
        name: "Bedding",
        attrs: [ATTR.age_group, ATTR.color, ATTR.material, ATTR.wash],
        children: [
          "Baby Blankets",
          "Baby Bedding Sets",
          "Crib Sheets",
          "Baby Pillows",
          "Baby Mattress Protectors",
          "Mosquito Nets",
          "Swaddles",
          "Sleeping Bags",
          "Baby Quilts",
        ],
      },
      {
        key: "baby-combos",
        name: "Combos",
        attrs: [ATTR.age_group, ATTR.pack_size],
        children: [
          "Diaper Combos",
          "Baby Care Combos",
          "Feeding Combos",
          "Bathing Combos",
          "Newborn Gift Sets",
          "Toy Combos",
          "School Combos",
          "Travel Combos",
          "Baby Essentials Kits",
        ],
      },
      {
        key: "art-kits",
        name: "Art Kits",
        attrs: [ATTR.minimum_age, ATTR.skill_development],
        children: [
          "Drawing Kits",
          "Painting Kits",
          "Coloring Sets",
          "Craft Kits",
          "Clay Kits",
          "DIY Art Kits",
          "Sketching Kits",
          "Origami Kits",
          "Activity Books",
        ],
      },
      {
        key: "toys-games",
        name: "Toys & Games",
        attrs: [
          ATTR.minimum_age,
          ATTR.battery_operated,
          ATTR.skill_development,
        ],
        children: [
          "Learning Toys",
          "Building Blocks",
          "Remote Control Toys",
          "Board Games",
          "Puzzles",
          "Dolls",
          "Action Figures",
          "Soft Toys",
          "Musical Toys",
        ],
      },
      {
        key: "baby-travel",
        name: "Travel",
        attrs: [
          ATTR.age_group,
          ATTR.color,
          ATTR.material,
          ATTR.weight_kg,
          ATTR.warranty,
        ],
        children: [
          "Baby Strollers",
          "Baby Car Seats",
          "Baby Carriers",
          "Diaper Bags",
          "Travel Beds",
          "Portable High Chairs",
          "Baby Travel Kits",
          "Travel Bottle Warmers",
          "Baby Harnesses",
        ],
      },
      {
        key: "summer-play",
        name: "Summer Play",
        attrs: [ATTR.minimum_age, ATTR.color],
        children: [
          "Inflatable Pools",
          "Water Guns",
          "Beach Toys",
          "Bubble Toys",
          "Swimming Floats",
          "Outdoor Play Tents",
          "Splash Mats",
          "Garden Slides",
          "Summer Sports Toys",
        ],
      },
      {
        key: "kids-stationery",
        name: "Stationery",
        attrs: [ATTR.age_group],
        children: [
          "Pencil Boxes",
          "Color Pencils",
          "Crayons",
          "Sketch Pens",
          "Notebooks",
          "Erasers & Sharpeners",
          "Craft Paper",
          "School Labels",
          "Exam Pads",
        ],
      },
      {
        key: "pet-toys",
        name: "Pet Toys",
        attrs: [ATTR.color, ATTR.material],
        children: [
          "Dog Chew Toys",
          "Dog Balls",
          "Rope Toys",
          "Cat Teasers",
          "Cat Balls",
          "Plush Pet Toys",
          "Interactive Pet Toys",
          "Squeaky Toys",
          "Pet Training Toys",
        ],
      },
      {
        key: "school-supplies",
        name: "School Supplies",
        attrs: [ATTR.age_group, ATTR.pack_size],
        children: [
          "School Bags",
          "Lunch Boxes",
          "Water Bottles",
          "Pencil Boxes",
          "Geometry Boxes",
          "Notebooks",
          "Exam Pads",
          "School Labels",
          "Stationery Kits",
        ],
      },
      {
        key: "baby-wipes",
        name: "Wipes",
        attrs: [ATTR.skin_type, ATTR.pack_size, ATTR.container_type],
        children: [
          "Baby Wipes",
          "Wet Wipes",
          "Water Wipes",
          "Sensitive Skin Wipes",
          "Fragrance Free Wipes",
          "Travel Wipes",
          "Diaper Wipes",
          "Face Wipes",
          "Wipe Combos",
        ],
      },
    ],
  },
];

class CategoriesSeed {
  constructor() {
    this.logger = new SeedLogger("Categories");
    this.mongoose = mongoose;
  }

  async execute() {
    const conn = this.mongoose.connection;
    if (!conn || !conn.collection)
      throw new Error("MongoDB connection not available");

    let totalRoot = 0,
      totalSubs = 0,
      totalChildren = 0;
    CATEGORY_TREE.forEach((r) => {
      totalRoot++;
      r.subs.forEach((s) => {
        totalSubs++;
        totalChildren += s.children.length;
      });
    });
    this.logger.info(
      `📂 Seeding Categories — ${totalRoot} root, ${totalSubs} sub, ${totalChildren} child`,
    );

    await conn.collection("categorytrees").deleteMany({});

    const docs = [];
    for (const root of CATEGORY_TREE) {
      docs.push({
        _id: new mongoose.Types.ObjectId(),
        categoryKey: root.key,
        title: root.name,
        parentKey: null,
        level: 0,
        attributeSchema: root.attrs,
        attributesSchema: {},
        active: true,
        sortOrder: root.order,
        imageUrl: `https://cdn.shopify.com/s/files/1/0533/2089/files/${root.key}.jpg`,
        bannerUrl: `https://cdn.shopify.com/s/files/1/0533/2089/files/${root.key}_banner.jpg`,
        iconUrl: `https://cdn.shopify.com/s/files/1/0533/2089/files/icon_${root.key}.svg`,
        isDashboardVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      });

      for (let si = 0; si < root.subs.length; si++) {
        const sub = root.subs[si];
        docs.push({
          _id: new mongoose.Types.ObjectId(),
          categoryKey: sub.key,
          title: sub.name,
          parentKey: root.key,
          level: 1,
          attributeSchema: sub.attrs,
          attributesSchema: {},
          active: true,
          sortOrder: si + 1,
          imageUrl: `https://cdn.shopify.com/s/files/1/0533/2089/files/${sub.key}.jpg`,
          bannerUrl: "",
          iconUrl: "",
          isDashboardVisible: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        });

        for (let ci = 0; ci < sub.children.length; ci++) {
          const childName = sub.children[ci];
          const childSlug = childName
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, "-")
            .replace(/(^-|-$)/g, "");
          const childKey = `${root.key}-${sub.key}-${childSlug}`;
          // Merge root + sub attrs so child inherits the complete attribute set; dedupe by key
          const seenKeys = new Set();
          const mergedAttrs = [...root.attrs, ...sub.attrs].filter((a) => {
            if (seenKeys.has(a.key)) return false;
            seenKeys.add(a.key);
            return true;
          });
          docs.push({
            _id: new mongoose.Types.ObjectId(),
            categoryKey: childKey,
            title: childName,
            parentKey: sub.key,
            level: 2,
            attributeSchema: mergedAttrs,
            attributesSchema: {},
            active: true,
            sortOrder: ci + 1,
            imageUrl: "",
            bannerUrl: "",
            iconUrl: "",
            isDashboardVisible: false,
            createdAt: new Date(),
            updatedAt: new Date(),
          });
        }
      }
    }

    const BATCH = 200;
    for (let i = 0; i < docs.length; i += BATCH) {
      await conn
        .collection("categorytrees")
        .insertMany(docs.slice(i, i + BATCH));
      this.logger.recordBatch(Math.min(BATCH, docs.length - i));
    }

    this.logger.printStats();
    return {
      created: docs.length,
      rootCategories: totalRoot,
      subCategories: totalSubs,
      childCategories: totalChildren,
    };
  }
}

module.exports = CategoriesSeed;
