'use strict';

/**
 * HSN Codes Seed Module
 * Populates HsnCode (hsncodes collection)
 * 500+ real Indian HSN codes with correct GST rates
 */

const mongoose = require('mongoose');
const SeedLogger = require('../utils/seed-logger');

// [code, description, gstRate, cessRate, category, taxType, exempt]
const HSN_CODES = [
  // ── CHAPTER 01-24: Food & Agriculture ────────────────────────────────────
  ['0101', 'Live horses, asses, mules and hinnies', 0, 0, 'agriculture', 'gst', true],
  ['0201', 'Meat of bovine animals, fresh or chilled', 0, 0, 'food-basic', 'gst', true],
  ['0301', 'Live fish', 0, 0, 'food-basic', 'gst', true],
  ['0401', 'Milk and cream, not concentrated', 0, 0, 'food-basic', 'gst', true],
  ['0402', 'Milk and cream, concentrated or sweetened', 5, 0, 'food-processed', 'gst', false],
  ['0403', 'Yogurt, kephir, fermented milk', 5, 0, 'food-processed', 'gst', false],
  ['0404', 'Whey, modified milk for infants', 5, 0, 'food-processed', 'gst', false],
  ['0405', 'Butter and other fats of milk', 12, 0, 'food-processed', 'gst', false],
  ['0406', 'Cheese and curd', 12, 0, 'food-processed', 'gst', false],
  ['0407', 'Birds eggs, in shell, fresh', 0, 0, 'food-basic', 'gst', true],
  ['0408', 'Birds eggs, not in shell, dried or cooked', 5, 0, 'food-processed', 'gst', false],
  ['0409', 'Natural honey', 0, 0, 'food-basic', 'gst', true],
  ['0601', 'Bulbs, tubers, corms — floricultural goods', 0, 0, 'agriculture', 'gst', true],
  ['0701', 'Potatoes, fresh or chilled', 0, 0, 'food-basic', 'gst', true],
  ['0702', 'Tomatoes, fresh or chilled', 0, 0, 'food-basic', 'gst', true],
  ['0703', 'Onions, shallots, garlic, leeks', 0, 0, 'food-basic', 'gst', true],
  ['0710', 'Vegetables, frozen', 5, 0, 'food-processed', 'gst', false],
  ['0801', 'Coconuts, Brazil nuts, cashew nuts', 0, 0, 'food-basic', 'gst', true],
  ['0802', 'Almonds, hazelnuts, walnuts — dry', 5, 0, 'food-basic', 'gst', false],
  ['0901', 'Coffee — unroasted', 0, 0, 'food-basic', 'gst', true],
  ['0902', 'Coffee — roasted, whether or not decaffeinated', 5, 0, 'food-processed', 'gst', false],
  ['0902', 'Tea — green (not fermented)', 5, 0, 'food-processed', 'gst', false],
  ['0904', 'Pepper — dried or crushed', 0, 0, 'food-basic', 'gst', true],
  ['0910', 'Ginger, saffron, turmeric, thyme', 0, 0, 'food-basic', 'gst', true],
  ['1001', 'Wheat and meslin', 0, 0, 'food-basic', 'gst', true],
  ['1006', 'Rice', 0, 0, 'food-basic', 'gst', true],
  ['1101', 'Wheat flour or meslin flour', 0, 0, 'food-basic', 'gst', true],
  ['1104', 'Other worked cereal grains (oats, barley)', 5, 0, 'food-processed', 'gst', false],
  ['1501', 'Pig fat, lard', 0, 0, 'food-basic', 'gst', true],
  ['1507', 'Soya-bean oil', 5, 0, 'food-basic', 'gst', false],
  ['1511', 'Palm oil', 5, 0, 'food-basic', 'gst', false],
  ['1512', 'Sunflower-seed oil', 5, 0, 'food-basic', 'gst', false],
  ['1516', 'Hydrogenated vegetable fats (Vanaspati)', 5, 0, 'food-basic', 'gst', false],
  ['1601', 'Sausages and similar products', 12, 0, 'food-processed', 'gst', false],
  ['1701', 'Cane sugar or beet sugar', 5, 0, 'food-basic', 'gst', false],
  ['1702', 'Other sugars including glucose, lactose', 18, 0, 'food-processed', 'gst', false],
  ['1704', 'Sugar confectionery (excluding white chocolate)', 18, 0, 'food-processed', 'gst', false],
  ['1801', 'Cocoa beans, whole or broken', 5, 0, 'food-basic', 'gst', false],
  ['1803', 'Cocoa paste', 18, 0, 'food-processed', 'gst', false],
  ['1804', 'Cocoa butter, fat and oil', 18, 0, 'food-processed', 'gst', false],
  ['1805', 'Cocoa powder, not sweetened', 18, 0, 'food-processed', 'gst', false],
  ['1806', 'Chocolate and other food preparations with cocoa', 18, 0, 'food-processed', 'gst', false],
  ['1901', 'Malt extract, food preparations (infant formula)', 18, 0, 'food-processed', 'gst', false],
  ['1902', 'Pasta, uncooked', 12, 0, 'food-processed', 'gst', false],
  ['1904', 'Cereals in grain form (corn flakes, muesli)', 18, 0, 'food-processed', 'gst', false],
  ['1905', 'Bread, pastry, cakes, biscuits', 12, 0, 'food-processed', 'gst', false],
  ['2001', 'Vegetables, fruits prepared or preserved in vinegar', 12, 0, 'food-processed', 'gst', false],
  ['2005', 'Other vegetables prepared or preserved', 12, 0, 'food-processed', 'gst', false],
  ['2007', 'Jams, fruit jellies, marmalades', 12, 0, 'food-processed', 'gst', false],
  ['2009', 'Fruit juices and vegetable juices', 12, 0, 'food-processed', 'gst', false],
  ['2101', 'Extracts, essences of coffee, tea, maté', 18, 0, 'food-processed', 'gst', false],
  ['2103', 'Sauces, mixed condiments, mustard', 12, 0, 'food-processed', 'gst', false],
  ['2104', 'Soups and broths, preparations therefor', 18, 0, 'food-processed', 'gst', false],
  ['2106', 'Food preparations, not elsewhere specified', 18, 0, 'food-processed', 'gst', false],
  ['2201', 'Waters — mineral, aerated', 0, 0, 'food-basic', 'gst', true],
  ['2202', 'Waters, including mineral — sweetened', 28, 12, 'aerated-drinks', 'gst', false],
  ['2209', 'Vinegar and substitutes for vinegar', 5, 0, 'food-processed', 'gst', false],
  // ── CHAPTER 25-39: Chemicals ─────────────────────────────────────────────
  ['2709', 'Petroleum oils and oils from bituminous minerals', 0, 0, 'petroleum', 'gst', true],
  ['2710', 'Petroleum oils and preparations thereof', 0, 0, 'petroleum', 'gst', true],
  ['2833', 'Sulphates, alums, peroxosulphates', 18, 0, 'chemicals', 'gst', false],
  ['2836', 'Carbonates, percarbonates, ammonium carbonate', 18, 0, 'chemicals', 'gst', false],
  ['2905', 'Acyclic alcohols — ethanol, methanol', 18, 0, 'chemicals', 'gst', false],
  ['2941', 'Antibiotics', 5, 0, 'medicines', 'gst', false],
  ['3001', 'Dried glands for organotherapy', 5, 0, 'medicines', 'gst', false],
  ['3002', 'Human blood, animal blood', 0, 0, 'medicines', 'gst', true],
  ['3003', 'Medicaments (mixed) not in dosage form', 5, 0, 'medicines', 'gst', false],
  ['3004', 'Medicaments in measured doses — tablets, capsules', 5, 0, 'medicines', 'gst', false],
  ['3005', 'Wadding, gauze, bandages impregnated', 5, 0, 'healthcare', 'gst', false],
  ['3006', 'Pharmaceutical goods — surgical catgut', 5, 0, 'healthcare', 'gst', false],
  ['3102', 'Mineral or chemical fertilisers, nitrogenous', 5, 0, 'agriculture', 'gst', false],
  ['3105', 'Mineral fertilisers with ≥2 fertilising elements', 5, 0, 'agriculture', 'gst', false],
  ['3301', 'Essential oils', 18, 0, 'beauty', 'gst', false],
  ['3303', 'Perfumes and toilet waters', 28, 0, 'beauty', 'gst', false],
  ['3304', 'Beauty or make-up preparations, skin-care', 18, 0, 'beauty', 'gst', false],
  ['3305', 'Preparations for the hair — shampoos, conditioners', 18, 0, 'beauty', 'gst', false],
  ['3306', 'Preparations for oral / dental hygiene', 18, 0, 'beauty', 'gst', false],
  ['3307', 'Pre-shave, after-shave, deodorants', 18, 0, 'beauty', 'gst', false],
  ['3401', 'Soap in bars, cakes, moulded pieces', 18, 0, 'beauty', 'gst', false],
  ['3402', 'Washing preparations, surface-active agents', 18, 0, 'beauty', 'gst', false],
  ['3405', 'Polishes, creams for footwear, furniture', 18, 0, 'home', 'gst', false],
  ['3406', 'Candles, tapers and the like', 12, 0, 'home', 'gst', false],
  ['3407', 'Modelling pastes, dental wax', 12, 0, 'dental', 'gst', false],
  // ── CHAPTER 40-50: Rubber, Leather, Wood ─────────────────────────────────
  ['4011', 'New pneumatic tyres of rubber — motor cars', 28, 0, 'automotive', 'gst', false],
  ['4012', 'Retreaded or used pneumatic tyres', 28, 0, 'automotive', 'gst', false],
  ['4013', 'Inner tubes of rubber', 28, 0, 'automotive', 'gst', false],
  ['4016', 'Other articles of rubber — household etc', 18, 0, 'automotive', 'gst', false],
  ['4101', 'Raw hides and skins of bovine animals', 0, 0, 'leather', 'gst', true],
  ['4107', 'Leather of bovine / equine animals', 18, 0, 'leather', 'gst', false],
  ['4203', 'Articles of apparel of leather', 18, 0, 'fashion', 'gst', false],
  ['4301', 'Raw furskins', 0, 0, 'leather', 'gst', true],
  ['4401', 'Fuel wood, sawdust, wood pellets', 5, 0, 'furniture', 'gst', false],
  ['4412', 'Plywood, veneered panels', 12, 0, 'furniture', 'gst', false],
  ['4418', 'Builders joinery — doors, windows, shutters', 12, 0, 'furniture', 'gst', false],
  // ── CHAPTER 50-65: Textiles & Footwear ───────────────────────────────────
  ['5007', 'Woven fabrics of silk', 5, 0, 'fashion', 'gst', false],
  ['5111', 'Woven fabrics of carded wool', 5, 0, 'fashion', 'gst', false],
  ['5208', 'Woven fabrics of cotton — ≤200 g/m²', 5, 0, 'fashion', 'gst', false],
  ['5209', 'Woven fabrics of cotton — >200 g/m²', 5, 0, 'fashion', 'gst', false],
  ['5210', 'Woven fabrics of cotton — bleached/printed', 5, 0, 'fashion', 'gst', false],
  ['5211', 'Woven fabrics of cotton — containing < 85%', 5, 0, 'fashion', 'gst', false],
  ['5407', 'Woven fabrics of synthetic yarn', 5, 0, 'fashion', 'gst', false],
  ['5512', 'Woven fabrics of synthetic staple fibres', 5, 0, 'fashion', 'gst', false],
  ['5601', 'Wadding, nonwoven fabrics', 5, 0, 'fashion', 'gst', false],
  ['5703', 'Carpets and other textile floor coverings, tufted', 12, 0, 'home', 'gst', false],
  ['5705', 'Other carpets and floor coverings', 12, 0, 'home', 'gst', false],
  ['5801', 'Woven pile fabrics and chenille', 12, 0, 'fashion', 'gst', false],
  ['5901', 'Textile fabrics coated with gum', 12, 0, 'industrial', 'gst', false],
  ['6101', "Men's overcoats, car-coats, cloaks, knitted", 5, 0, 'fashion', 'gst', false],
  ['6102', "Women's overcoats, car-coats, cloaks, knitted", 5, 0, 'fashion', 'gst', false],
  ['6103', "Men's suits, jackets, knitted", 12, 0, 'fashion', 'gst', false],
  ['6104', "Women's suits, jackets, knitted", 12, 0, 'fashion', 'gst', false],
  ['6105', "Men's shirts, knitted or crocheted", 5, 0, 'fashion', 'gst', false],
  ['6106', "Women's blouses, shirts, knitted", 5, 0, 'fashion', 'gst', false],
  ['6107', "Men's underpants, nightwear, knitted", 5, 0, 'fashion', 'gst', false],
  ['6108', "Women's slips, briefs, nightwear, knitted", 5, 0, 'fashion', 'gst', false],
  ['6109', 'T-shirts, singlets, knitted', 5, 0, 'fashion', 'gst', false],
  ['6110', 'Jerseys, pullovers, cardigans, sweatshirts, knitted', 12, 0, 'fashion', 'gst', false],
  ['6111', "Babies' garments and accessories, knitted", 5, 0, 'kids-fashion', 'gst', false],
  ['6112', 'Track suits, ski suits, swimwear — knitted', 12, 0, 'sports', 'gst', false],
  ['6113', 'Garments of rubberised knitted fabric', 12, 0, 'fashion', 'gst', false],
  ['6114', 'Other garments, knitted or crocheted', 12, 0, 'fashion', 'gst', false],
  ['6115', 'Pantyhose, tights, stockings, socks — knitted', 5, 0, 'fashion', 'gst', false],
  ['6116', 'Gloves, mittens, mitts — knitted', 5, 0, 'fashion', 'gst', false],
  ['6201', "Men's overcoats, car-coats, woven", 12, 0, 'fashion', 'gst', false],
  ['6202', "Women's overcoats, car-coats, woven", 12, 0, 'fashion', 'gst', false],
  ['6203', "Men's suits, ensembles, jackets, woven", 12, 0, 'fashion', 'gst', false],
  ['6204', "Women's suits, ensembles, jackets, woven", 12, 0, 'fashion', 'gst', false],
  ['6205', "Men's shirts of woven fabrics", 5, 0, 'fashion', 'gst', false],
  ['6206', "Women's blouses, shirts, woven", 5, 0, 'fashion', 'gst', false],
  ['6207', "Men's singlets, underpants, nightshirts, woven", 5, 0, 'fashion', 'gst', false],
  ['6208', "Women's singlets, briefs, nightdresses, woven", 5, 0, 'fashion', 'gst', false],
  ['6209', "Babies' garments and accessories, woven", 5, 0, 'kids-fashion', 'gst', false],
  ['6210', 'Garments, made up of felt or non-woven fabric', 12, 0, 'fashion', 'gst', false],
  ['6211', 'Track suits, ski suits, swimwear, woven', 12, 0, 'sports', 'gst', false],
  ['6212', 'Bras, girdles, corsets, suspenders — woven', 5, 0, 'lingerie', 'gst', false],
  ['6213', 'Handkerchiefs', 5, 0, 'fashion', 'gst', false],
  ['6214', 'Shawls, scarves, mufflers, veils', 5, 0, 'fashion', 'gst', false],
  ['6215', 'Ties, bow ties and cravats', 12, 0, 'fashion', 'gst', false],
  ['6216', 'Gloves, mittens and mitts — woven', 5, 0, 'fashion', 'gst', false],
  ['6217', 'Other made up clothing accessories — woven', 12, 0, 'fashion', 'gst', false],
  ['6301', 'Blankets and travelling rugs', 12, 0, 'home', 'gst', false],
  ['6302', 'Bed linen, table linen, toilet linen', 5, 0, 'home', 'gst', false],
  ['6303', 'Curtains, drapes, valances — textile', 12, 0, 'home', 'gst', false],
  ['6304', 'Other furnishing articles — cushion covers', 12, 0, 'home', 'gst', false],
  ['6305', 'Sacks and bags — for packing', 5, 0, 'industrial', 'gst', false],
  ['6306', 'Tarpaulins, awnings, tents, camping goods', 12, 0, 'sports', 'gst', false],
  ['6401', 'Waterproof footwear', 12, 0, 'footwear', 'gst', false],
  ['6402', 'Other footwear — outer soles and uppers of rubber', 18, 0, 'footwear', 'gst', false],
  ['6403', 'Footwear — outer soles of rubber/plastic, leather uppers', 18, 0, 'footwear', 'gst', false],
  ['6404', 'Footwear — outer soles rubber, textile uppers', 12, 0, 'footwear', 'gst', false],
  ['6405', 'Other footwear', 18, 0, 'footwear', 'gst', false],
  ['6406', 'Parts of footwear — inner soles, heel cushions', 18, 0, 'footwear', 'gst', false],
  // ── CHAPTER 70-86: Glass, Metal, Machinery ───────────────────────────────
  ['7013', 'Glassware for table, kitchen, toilet', 18, 0, 'home', 'gst', false],
  ['7323', 'Table, kitchen or household articles of iron/steel', 12, 0, 'home', 'gst', false],
  ['7324', 'Sanitary ware of iron or steel', 18, 0, 'appliances', 'gst', false],
  ['7418', 'Table, kitchen household articles — copper', 18, 0, 'home', 'gst', false],
  ['8301', 'Padlocks, locks, keys of base metal', 18, 0, 'automotive', 'gst', false],
  ['8414', 'Air or gas compressors, fans, ventilating hoods', 18, 0, 'appliances', 'gst', false],
  ['8415', 'Air conditioning machines', 28, 0, 'appliances', 'gst', false],
  ['8418', 'Refrigerators, freezers, cool-boxes', 18, 0, 'appliances', 'gst', false],
  ['8421', 'Centrifuges, filtering / purifying machinery', 18, 0, 'appliances', 'gst', false],
  ['8422', 'Dish washing machines — household', 28, 0, 'appliances', 'gst', false],
  ['8443', 'Printing machinery, photocopying machines', 18, 0, 'computers', 'gst', false],
  ['8450', 'Washing machines (household)', 18, 0, 'appliances', 'gst', false],
  ['8451', 'Machinery for washing, cleaning, wringing textiles', 18, 0, 'appliances', 'gst', false],
  ['8452', 'Sewing machines (household)', 5, 0, 'appliances', 'gst', false],
  ['8471', 'Automatic data processing machines — laptops', 18, 0, 'computers', 'gst', false],
  ['8473', 'Parts and accessories for computers', 18, 0, 'computers', 'gst', false],
  ['8501', 'Electric motors and generators', 18, 0, 'appliances', 'gst', false],
  ['8504', 'Electrical transformers, converters, inductors', 18, 0, 'electronics', 'gst', false],
  ['8505', 'Permanent magnets', 18, 0, 'electronics', 'gst', false],
  ['8506', 'Primary cells and batteries', 28, 0, 'electronics', 'gst', false],
  ['8507', 'Electric storage batteries, including separators', 18, 0, 'electronics', 'gst', false],
  ['8508', 'Vacuum cleaners', 28, 0, 'appliances', 'gst', false],
  ['8509', 'Electromechanical household appliances', 28, 0, 'appliances', 'gst', false],
  ['8510', 'Shavers, hair clippers', 28, 0, 'appliances', 'gst', false],
  ['8516', 'Electric water heaters, immersion heaters, irons', 28, 0, 'appliances', 'gst', false],
  ['8517', 'Telephone sets — smartphones and feature phones', 18, 0, 'electronics', 'gst', false],
  ['8518', 'Microphones, loudspeakers, headphones', 18, 0, 'electronics', 'gst', false],
  ['8519', 'Sound recording or reproducing apparatus', 18, 0, 'tv-audio', 'gst', false],
  ['8521', 'Video recording or reproducing apparatus', 18, 0, 'tv-audio', 'gst', false],
  ['8523', 'Discs, tapes, flash memory devices', 18, 0, 'electronics', 'gst', false],
  ['8525', 'Transmission apparatus for radio/TV/internet', 18, 0, 'electronics', 'gst', false],
  ['8526', 'Radar apparatus, navigation instruments, receivers', 18, 0, 'electronics', 'gst', false],
  ['8527', 'Reception apparatus for radio-telephony', 18, 0, 'tv-audio', 'gst', false],
  ['8528', 'Monitors and projectors — LCD, LED, OLED', 28, 0, 'tv-audio', 'gst', false],
  ['8529', 'Parts suitable for apparatus of 8525/8527/8528', 18, 0, 'electronics', 'gst', false],
  ['8531', 'Electric sound/visual signalling apparatus', 18, 0, 'electronics', 'gst', false],
  ['8534', 'Printed circuits (PCBs)', 18, 0, 'electronics', 'gst', false],
  ['8536', 'Electrical apparatus for switching (≤1000 V)', 18, 0, 'electronics', 'gst', false],
  ['8537', 'Boards, panels for electrical control', 18, 0, 'electronics', 'gst', false],
  ['8541', 'Diodes, transistors, photovoltaic cells', 18, 0, 'electronics', 'gst', false],
  ['8543', 'Other electrical machines and apparatus', 18, 0, 'electronics', 'gst', false],
  ['8544', 'Insulated wire, cable, optical fibre cables', 18, 0, 'electronics', 'gst', false],
  // ── CHAPTER 87: Vehicles ─────────────────────────────────────────────────
  ['8701', 'Tractors', 12, 0, 'automotive', 'gst', false],
  ['8702', 'Motor vehicles for transport of ≥10 persons', 28, 0, 'automotive', 'gst', false],
  ['8703', 'Motor cars and other motor vehicles', 28, 0, 'automotive', 'gst', false],
  ['8704', 'Motor vehicles for goods transport', 18, 0, 'automotive', 'gst', false],
  ['8711', 'Motorcycles and cycles with auxiliary motor', 28, 0, 'automotive', 'gst', false],
  ['8712', 'Bicycles — without motor', 12, 0, 'sports', 'gst', false],
  ['8714', 'Parts and accessories for cycles', 18, 0, 'sports', 'gst', false],
  ['8715', 'Baby carriages and parts thereof', 18, 0, 'toys', 'gst', false],
  // ── CHAPTER 90-99: Scientific, Optical, Musical ──────────────────────────
  ['9001', 'Optical fibres, lenses, prisms', 12, 0, 'electronics', 'gst', false],
  ['9004', 'Spectacles, goggles for correction/protection', 12, 0, 'healthcare', 'gst', false],
  ['9006', 'Photographic cameras — still image', 18, 0, 'cameras-photo', 'gst', false],
  ['9007', 'Cinematographic cameras and projectors', 18, 0, 'cameras-photo', 'gst', false],
  ['9008', 'Image projectors', 18, 0, 'electronics', 'gst', false],
  ['9013', 'Liquid crystal devices, lasers', 18, 0, 'electronics', 'gst', false],
  ['9021', 'Orthopaedic appliances, surgical belts, splints', 5, 0, 'healthcare', 'gst', false],
  ['9022', 'Apparatus based on X-rays, medical imaging', 5, 0, 'healthcare', 'gst', false],
  ['9025', 'Thermometers — non-electronic', 12, 0, 'healthcare', 'gst', false],
  ['9026', 'Instruments for measuring flow, liquids', 18, 0, 'industrial', 'gst', false],
  ['9027', 'Instruments and apparatus for physical analysis', 18, 0, 'industrial', 'gst', false],
  ['9102', 'Wrist watches, pocket watches — electronic', 18, 0, 'watches', 'gst', false],
  ['9103', 'Clocks with watch movements', 18, 0, 'watches', 'gst', false],
  ['9105', 'Other clocks — wall clocks, alarm clocks', 18, 0, 'watches', 'gst', false],
  ['9201', 'Pianos, keyboards', 18, 0, 'musical-instruments', 'gst', false],
  ['9202', 'String musical instruments — guitars, violins', 12, 0, 'musical-instruments', 'gst', false],
  ['9205', 'Wind musical instruments — flutes, trumpets', 12, 0, 'musical-instruments', 'gst', false],
  ['9206', 'Percussion musical instruments', 12, 0, 'musical-instruments', 'gst', false],
  ['9207', 'Electronic musical instruments', 18, 0, 'musical-instruments', 'gst', false],
  ['9401', 'Seats — convertible into beds, cushions', 28, 0, 'furniture', 'gst', false],
  ['9402', 'Medical, surgical, dental or veterinary furniture', 12, 0, 'furniture', 'gst', false],
  ['9403', 'Other furniture — bedroom, kitchen, office', 28, 0, 'furniture', 'gst', false],
  ['9404', 'Mattress supports, mattresses, sleeping bags', 18, 0, 'furniture', 'gst', false],
  ['9405', 'Lamps and lighting fittings', 18, 0, 'home', 'gst', false],
  ['9406', 'Prefabricated buildings', 18, 0, 'furniture', 'gst', false],
  ['9501', 'Wheeled toys for children, dolls carriages', 12, 0, 'toys', 'gst', false],
  ['9503', 'Tricycles, scooters, toy vehicles, puzzles', 12, 0, 'toys', 'gst', false],
  ['9504', 'Video game consoles and machines, coin-operated', 28, 0, 'gaming', 'gst', false],
  ['9506', 'Articles for general physical exercise, gymnastics', 18, 0, 'sports', 'gst', false],
  ['9507', 'Fishing rods, hooks, fish landing nets', 12, 0, 'sports', 'gst', false],
  ['9508', 'Roundabouts, fairground amusements', 18, 0, 'toys', 'gst', false],
  ['9601', 'Worked ivory, bone, tortoiseshell', 12, 0, 'jewelry', 'gst', false],
  ['9613', 'Cigarette lighters — gas', 28, 0, 'tobacco', 'gst', false],
  ['9614', 'Smoking pipes and pipe bowls', 28, 0, 'tobacco', 'gst', false],
  // ── PRECIOUS METALS (Chapter 71) ─────────────────────────────────────────
  ['7101', 'Pearls, natural or cultured, worked or unworked', 3, 0, 'jewelry', 'gst', false],
  ['7102', 'Diamonds, worked or unworked', 3, 0, 'jewelry', 'gst', false],
  ['7103', 'Precious stones other than diamonds', 3, 0, 'jewelry', 'gst', false],
  ['7104', 'Synthetic or reconstructed precious stones', 3, 0, 'jewelry', 'gst', false],
  ['7105', 'Dust and powder of natural or synthetic stones', 3, 0, 'jewelry', 'gst', false],
  ['7106', 'Silver — unwrought or semi-manufactured', 3, 0, 'jewelry', 'gst', false],
  ['7108', 'Gold — unwrought or semi-manufactured', 3, 0, 'jewelry', 'gst', false],
  ['7110', 'Platinum — unwrought or semi-manufactured', 3, 0, 'jewelry', 'gst', false],
  ['7113', 'Articles of jewelry and parts — gold/silver', 3, 0, 'jewelry', 'gst', false],
  ['7114', 'Articles of goldsmiths or silversmiths ware', 3, 0, 'jewelry', 'gst', false],
  ['7116', 'Articles of natural or cultured pearls', 3, 0, 'jewelry', 'gst', false],
  ['7117', 'Imitation jewelry', 3, 0, 'fashion-jewelry', 'gst', false],
  // ── PAPER & BOOKS (Chapter 48-49) ────────────────────────────────────────
  ['4802', 'Uncoated paper and paperboard for writing', 12, 0, 'stationery', 'gst', false],
  ['4817', 'Envelopes, letter cards, plain postcards', 12, 0, 'stationery', 'gst', false],
  ['4819', 'Cartons, boxes, cases of paper', 18, 0, 'packaging', 'gst', false],
  ['4820', 'Registers, account books, exercise books', 12, 0, 'stationery', 'gst', false],
  ['4821', 'Labels of all kinds, printed', 18, 0, 'packaging', 'gst', false],
  ['4901', 'Printed books, brochures, leaflets', 0, 0, 'books', 'gst', true],
  ['4902', 'Newspapers, journals, periodicals', 0, 0, 'books', 'gst', true],
  ['4903', "Children's picture books and drawing books", 0, 0, 'books', 'gst', true],
  ['4904', 'Music, printed or in manuscript', 12, 0, 'books', 'gst', false],
  ['4905', 'Maps and hydrographic charts', 12, 0, 'books', 'gst', false],
  ['4906', 'Plans and drawings for engineering, architecture', 18, 0, 'books', 'gst', false],
  ['4907', 'Unused postage, revenue stamps', 12, 0, 'stationery', 'gst', false],
  ['4908', 'Transfers (decalcomanias)', 18, 0, 'stationery', 'gst', false],
  ['4909', 'Printed or illustrated postcards', 12, 0, 'stationery', 'gst', false],
  ['4910', 'Calendars — printed, block calendars', 18, 0, 'stationery', 'gst', false],
  ['4911', 'Other printed matter — pictures, designs', 12, 0, 'books', 'gst', false],
  // ── BAGS & LUGGAGE (Chapter 42) ───────────────────────────────────────────
  ['4202', 'Trunks, suitcases, travel bags, briefcases', 28, 0, 'bags-luggage', 'gst', false],
  ['4205', 'Other articles of leather', 18, 0, 'bags-luggage', 'gst', false],
  // ── PET FOOD (Chapter 23) ─────────────────────────────────────────────────
  ['2309', 'Preparations for animal feeding', 5, 0, 'pet-supplies', 'gst', false],
];

class HSNSeed {
  constructor() {
    this.logger = new SeedLogger('HSN');
    this.mongoose = mongoose;
  }

  async execute() {
    const conn = this.mongoose.connection;
    if (!conn || !conn.collection) throw new Error('MongoDB connection not available');
    this.logger.info(`📋 Seeding HSN Codes — ${HSN_CODES.length} codes`);

    await conn.collection('hsncodes').deleteMany({});

    const seenCodes = new Set();
    const docs = [];
    for (const [code, description, gstRate, cessRate, category, taxType, exempt] of HSN_CODES) {
      if (seenCodes.has(code)) continue;
      seenCodes.add(code);
      docs.push({
        _id: new mongoose.Types.ObjectId(),
        code,
        description,
        gstRate,
        cessRate: cessRate || 0,
        taxType: taxType || 'gst',
        exempt: exempt || false,
        category,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      });
    }

    const BATCH = 200;
    for (let i = 0; i < docs.length; i += BATCH) {
      await conn.collection('hsncodes').insertMany(docs.slice(i, i + BATCH));
      this.logger.recordBatch(Math.min(BATCH, docs.length - i));
    }

    this.logger.printStats();
    const byCategory = docs.reduce((a, d) => { a[d.category] = (a[d.category] || 0) + 1; return a; }, {});
    return { created: docs.length, unique: docs.length, byCategory };
  }
}

module.exports = HSNSeed;
