'use strict';

/**
 * Options Seed Module
 * Populates PlatformProductOption + PlatformProductOptionValue
 * 25+ options with 300+ values
 */

const mongoose = require('mongoose');
const SeedLogger = require('../utils/seed-logger');

const OPTIONS = [
  {
    name: 'Color',
    slug: 'color',
    displayType: 'color_swatch',
    description: 'Product color variant',
    values: [
      { name: 'Black',        valueCode: 'black',        colorHex: '#000000', sortOrder: 1 },
      { name: 'White',        valueCode: 'white',        colorHex: '#FFFFFF', sortOrder: 2 },
      { name: 'Red',          valueCode: 'red',          colorHex: '#FF0000', sortOrder: 3 },
      { name: 'Blue',         valueCode: 'blue',         colorHex: '#0066CC', sortOrder: 4 },
      { name: 'Navy Blue',    valueCode: 'navy-blue',    colorHex: '#000080', sortOrder: 5 },
      { name: 'Royal Blue',   valueCode: 'royal-blue',   colorHex: '#4169E1', sortOrder: 6 },
      { name: 'Sky Blue',     valueCode: 'sky-blue',     colorHex: '#87CEEB', sortOrder: 7 },
      { name: 'Green',        valueCode: 'green',        colorHex: '#008000', sortOrder: 8 },
      { name: 'Olive Green',  valueCode: 'olive-green',  colorHex: '#6B8E23', sortOrder: 9 },
      { name: 'Dark Green',   valueCode: 'dark-green',   colorHex: '#006400', sortOrder: 10 },
      { name: 'Yellow',       valueCode: 'yellow',       colorHex: '#FFD700', sortOrder: 11 },
      { name: 'Mustard',      valueCode: 'mustard',      colorHex: '#FFDB58', sortOrder: 12 },
      { name: 'Orange',       valueCode: 'orange',       colorHex: '#FF8C00', sortOrder: 13 },
      { name: 'Coral',        valueCode: 'coral',        colorHex: '#FF7F50', sortOrder: 14 },
      { name: 'Pink',         valueCode: 'pink',         colorHex: '#FF69B4', sortOrder: 15 },
      { name: 'Rose',         valueCode: 'rose',         colorHex: '#FF007F', sortOrder: 16 },
      { name: 'Peach',        valueCode: 'peach',        colorHex: '#FFCBA4', sortOrder: 17 },
      { name: 'Purple',       valueCode: 'purple',       colorHex: '#800080', sortOrder: 18 },
      { name: 'Lavender',     valueCode: 'lavender',     colorHex: '#E6E6FA', sortOrder: 19 },
      { name: 'Violet',       valueCode: 'violet',       colorHex: '#8B00FF', sortOrder: 20 },
      { name: 'Brown',        valueCode: 'brown',        colorHex: '#8B4513', sortOrder: 21 },
      { name: 'Tan',          valueCode: 'tan',          colorHex: '#D2B48C', sortOrder: 22 },
      { name: 'Camel',        valueCode: 'camel',        colorHex: '#C19A6B', sortOrder: 23 },
      { name: 'Khaki',        valueCode: 'khaki',        colorHex: '#C3B091', sortOrder: 24 },
      { name: 'Grey',         valueCode: 'grey',         colorHex: '#808080', sortOrder: 25 },
      { name: 'Light Grey',   valueCode: 'light-grey',   colorHex: '#D3D3D3', sortOrder: 26 },
      { name: 'Charcoal',     valueCode: 'charcoal',     colorHex: '#36454F', sortOrder: 27 },
      { name: 'Beige',        valueCode: 'beige',        colorHex: '#F5F5DC', sortOrder: 28 },
      { name: 'Off White',    valueCode: 'off-white',    colorHex: '#FAF9F6', sortOrder: 29 },
      { name: 'Ivory',        valueCode: 'ivory',        colorHex: '#FFFFF0', sortOrder: 30 },
      { name: 'Cream',        valueCode: 'cream',        colorHex: '#FFFDD0', sortOrder: 31 },
      { name: 'Gold',         valueCode: 'gold',         colorHex: '#FFD700', sortOrder: 32 },
      { name: 'Silver',       valueCode: 'silver',       colorHex: '#C0C0C0', sortOrder: 33 },
      { name: 'Rose Gold',    valueCode: 'rose-gold',    colorHex: '#B76E79', sortOrder: 34 },
      { name: 'Maroon',       valueCode: 'maroon',       colorHex: '#800000', sortOrder: 35 },
      { name: 'Burgundy',     valueCode: 'burgundy',     colorHex: '#800020', sortOrder: 36 },
      { name: 'Teal',         valueCode: 'teal',         colorHex: '#008080', sortOrder: 37 },
      { name: 'Cyan',         valueCode: 'cyan',         colorHex: '#00FFFF', sortOrder: 38 },
      { name: 'Turquoise',    valueCode: 'turquoise',    colorHex: '#40E0D0', sortOrder: 39 },
      { name: 'Mint',         valueCode: 'mint',         colorHex: '#98FF98', sortOrder: 40 },
      { name: 'Rust',         valueCode: 'rust',         colorHex: '#B7410E', sortOrder: 41 },
      { name: 'Copper',       valueCode: 'copper',       colorHex: '#B87333', sortOrder: 42 },
      { name: 'Bronze',       valueCode: 'bronze',       colorHex: '#CD7F32', sortOrder: 43 },
      { name: 'Multicolor',   valueCode: 'multicolor',   colorHex: '#FF00FF', sortOrder: 44 },
      { name: 'Printed',      valueCode: 'printed',      colorHex: '#999999', sortOrder: 45 },
    ],
  },
  {
    name: 'Size',
    slug: 'size',
    displayType: 'button',
    description: 'Clothing and apparel size',
    values: [
      { name: 'XS',        valueCode: 'xs',       sortOrder: 1 },
      { name: 'S',         valueCode: 's',        sortOrder: 2 },
      { name: 'M',         valueCode: 'm',        sortOrder: 3 },
      { name: 'L',         valueCode: 'l',        sortOrder: 4 },
      { name: 'XL',        valueCode: 'xl',       sortOrder: 5 },
      { name: 'XXL',       valueCode: 'xxl',      sortOrder: 6 },
      { name: '3XL',       valueCode: '3xl',      sortOrder: 7 },
      { name: '4XL',       valueCode: '4xl',      sortOrder: 8 },
      { name: '5XL',       valueCode: '5xl',      sortOrder: 9 },
      { name: 'Free Size', valueCode: 'free-size',sortOrder: 10 },
      { name: '28',        valueCode: '28',       sortOrder: 11 },
      { name: '30',        valueCode: '30',       sortOrder: 12 },
      { name: '32',        valueCode: '32',       sortOrder: 13 },
      { name: '34',        valueCode: '34',       sortOrder: 14 },
      { name: '36',        valueCode: '36',       sortOrder: 15 },
      { name: '38',        valueCode: '38',       sortOrder: 16 },
      { name: '40',        valueCode: '40',       sortOrder: 17 },
      { name: '42',        valueCode: '42',       sortOrder: 18 },
      { name: '44',        valueCode: '44',       sortOrder: 19 },
      { name: '46',        valueCode: '46',       sortOrder: 20 },
    ],
  },
  {
    name: 'Shoe Size',
    slug: 'shoe-size',
    displayType: 'button',
    description: 'UK/Indian shoe size',
    values: [
      { name: '4',  valueCode: '4',  sortOrder: 1 },
      { name: '5',  valueCode: '5',  sortOrder: 2 },
      { name: '6',  valueCode: '6',  sortOrder: 3 },
      { name: '7',  valueCode: '7',  sortOrder: 4 },
      { name: '8',  valueCode: '8',  sortOrder: 5 },
      { name: '9',  valueCode: '9',  sortOrder: 6 },
      { name: '10', valueCode: '10', sortOrder: 7 },
      { name: '11', valueCode: '11', sortOrder: 8 },
      { name: '12', valueCode: '12', sortOrder: 9 },
      { name: '13', valueCode: '13', sortOrder: 10 },
      { name: '3 (Kids)', valueCode: '3-kids', sortOrder: 11 },
      { name: '4 (Kids)', valueCode: '4-kids', sortOrder: 12 },
      { name: '5 (Kids)', valueCode: '5-kids', sortOrder: 13 },
      { name: '1C (Infant)', valueCode: '1c-infant', sortOrder: 14 },
      { name: '2C (Infant)', valueCode: '2c-infant', sortOrder: 15 },
      { name: '3C (Infant)', valueCode: '3c-infant', sortOrder: 16 },
    ],
  },
  {
    name: 'RAM',
    slug: 'ram',
    displayType: 'button',
    description: 'Device RAM / Memory',
    values: [
      { name: '1GB',  valueCode: '1gb',  sortOrder: 1 },
      { name: '2GB',  valueCode: '2gb',  sortOrder: 2 },
      { name: '3GB',  valueCode: '3gb',  sortOrder: 3 },
      { name: '4GB',  valueCode: '4gb',  sortOrder: 4 },
      { name: '6GB',  valueCode: '6gb',  sortOrder: 5 },
      { name: '8GB',  valueCode: '8gb',  sortOrder: 6 },
      { name: '12GB', valueCode: '12gb', sortOrder: 7 },
      { name: '16GB', valueCode: '16gb', sortOrder: 8 },
      { name: '24GB', valueCode: '24gb', sortOrder: 9 },
      { name: '32GB', valueCode: '32gb', sortOrder: 10 },
      { name: '48GB', valueCode: '48gb', sortOrder: 11 },
      { name: '64GB', valueCode: '64gb', sortOrder: 12 },
    ],
  },
  {
    name: 'Storage',
    slug: 'storage',
    displayType: 'button',
    description: 'Internal / external storage capacity',
    values: [
      { name: '8GB',   valueCode: '8gb',   sortOrder: 1 },
      { name: '16GB',  valueCode: '16gb',  sortOrder: 2 },
      { name: '32GB',  valueCode: '32gb',  sortOrder: 3 },
      { name: '64GB',  valueCode: '64gb',  sortOrder: 4 },
      { name: '128GB', valueCode: '128gb', sortOrder: 5 },
      { name: '256GB', valueCode: '256gb', sortOrder: 6 },
      { name: '512GB', valueCode: '512gb', sortOrder: 7 },
      { name: '1TB',   valueCode: '1tb',   sortOrder: 8 },
      { name: '2TB',   valueCode: '2tb',   sortOrder: 9 },
      { name: '4TB',   valueCode: '4tb',   sortOrder: 10 },
    ],
  },
  {
    name: 'Network',
    slug: 'network',
    displayType: 'button',
    description: 'Mobile network generation',
    values: [
      { name: '5G',     valueCode: '5g',     sortOrder: 1 },
      { name: '4G LTE', valueCode: '4g-lte', sortOrder: 2 },
      { name: '3G',     valueCode: '3g',     sortOrder: 3 },
      { name: '2G',     valueCode: '2g',     sortOrder: 4 },
    ],
  },
  {
    name: 'Screen Size',
    slug: 'screen-size',
    displayType: 'dropdown',
    description: 'Display / screen diagonal size',
    values: [
      { name: '5.0 inches',  valueCode: '5-0-inch',  sortOrder: 1 },
      { name: '5.5 inches',  valueCode: '5-5-inch',  sortOrder: 2 },
      { name: '6.0 inches',  valueCode: '6-0-inch',  sortOrder: 3 },
      { name: '6.1 inches',  valueCode: '6-1-inch',  sortOrder: 4 },
      { name: '6.5 inches',  valueCode: '6-5-inch',  sortOrder: 5 },
      { name: '6.7 inches',  valueCode: '6-7-inch',  sortOrder: 6 },
      { name: '13 inches',   valueCode: '13-inch',   sortOrder: 7 },
      { name: '14 inches',   valueCode: '14-inch',   sortOrder: 8 },
      { name: '15.6 inches', valueCode: '15-6-inch', sortOrder: 9 },
      { name: '16 inches',   valueCode: '16-inch',   sortOrder: 10 },
      { name: '32 inches',   valueCode: '32-inch',   sortOrder: 11 },
      { name: '40 inches',   valueCode: '40-inch',   sortOrder: 12 },
      { name: '43 inches',   valueCode: '43-inch',   sortOrder: 13 },
      { name: '50 inches',   valueCode: '50-inch',   sortOrder: 14 },
      { name: '55 inches',   valueCode: '55-inch',   sortOrder: 15 },
      { name: '65 inches',   valueCode: '65-inch',   sortOrder: 16 },
      { name: '75 inches',   valueCode: '75-inch',   sortOrder: 17 },
      { name: '85 inches',   valueCode: '85-inch',   sortOrder: 18 },
    ],
  },
  {
    name: 'Material',
    slug: 'material',
    displayType: 'dropdown',
    description: 'Product material / fabric type',
    values: [
      { name: 'Cotton',          valueCode: 'cotton',          sortOrder: 1 },
      { name: 'Pure Cotton',     valueCode: 'pure-cotton',     sortOrder: 2 },
      { name: 'Polyester',       valueCode: 'polyester',       sortOrder: 3 },
      { name: 'Silk',            valueCode: 'silk',            sortOrder: 4 },
      { name: 'Pure Silk',       valueCode: 'pure-silk',       sortOrder: 5 },
      { name: 'Wool',            valueCode: 'wool',            sortOrder: 6 },
      { name: 'Linen',           valueCode: 'linen',           sortOrder: 7 },
      { name: 'Nylon',           valueCode: 'nylon',           sortOrder: 8 },
      { name: 'Viscose',         valueCode: 'viscose',         sortOrder: 9 },
      { name: 'Rayon',           valueCode: 'rayon',           sortOrder: 10 },
      { name: 'Satin',           valueCode: 'satin',           sortOrder: 11 },
      { name: 'Chiffon',         valueCode: 'chiffon',         sortOrder: 12 },
      { name: 'Georgette',       valueCode: 'georgette',       sortOrder: 13 },
      { name: 'Crepe',           valueCode: 'crepe',           sortOrder: 14 },
      { name: 'Denim',           valueCode: 'denim',           sortOrder: 15 },
      { name: 'Leather',         valueCode: 'leather',         sortOrder: 16 },
      { name: 'Faux Leather',    valueCode: 'faux-leather',    sortOrder: 17 },
      { name: 'Suede',           valueCode: 'suede',           sortOrder: 18 },
      { name: 'Canvas',          valueCode: 'canvas',          sortOrder: 19 },
      { name: 'Mesh',            valueCode: 'mesh',            sortOrder: 20 },
      { name: 'Jersey',          valueCode: 'jersey',          sortOrder: 21 },
      { name: 'Fleece',          valueCode: 'fleece',          sortOrder: 22 },
      { name: 'Velvet',          valueCode: 'velvet',          sortOrder: 23 },
      { name: 'Acrylic',         valueCode: 'acrylic',         sortOrder: 24 },
      { name: 'Spandex',         valueCode: 'spandex',         sortOrder: 25 },
      { name: 'Modal',           valueCode: 'modal',           sortOrder: 26 },
      { name: 'Bamboo',          valueCode: 'bamboo',          sortOrder: 27 },
      { name: 'Cotton Blend',    valueCode: 'cotton-blend',    sortOrder: 28 },
      { name: 'Poly Cotton',     valueCode: 'poly-cotton',     sortOrder: 29 },
      { name: 'Linen Cotton',    valueCode: 'linen-cotton',    sortOrder: 30 },
      { name: 'Jacquard',        valueCode: 'jacquard',        sortOrder: 31 },
      { name: 'Brocade',         valueCode: 'brocade',         sortOrder: 32 },
      { name: 'Velour',          valueCode: 'velour',          sortOrder: 33 },
      { name: 'Organza',         valueCode: 'organza',         sortOrder: 34 },
      { name: 'Net',             valueCode: 'net',             sortOrder: 35 },
      { name: 'Rubber',          valueCode: 'rubber',          sortOrder: 36 },
      { name: 'EVA',             valueCode: 'eva',             sortOrder: 37 },
      { name: 'Plastic',         valueCode: 'plastic',         sortOrder: 38 },
      { name: 'Metal',           valueCode: 'metal',           sortOrder: 39 },
      { name: 'Stainless Steel', valueCode: 'stainless-steel', sortOrder: 40 },
    ],
  },
  {
    name: 'Fit',
    slug: 'fit',
    displayType: 'radio',
    description: 'Clothing fit type',
    values: [
      { name: 'Slim Fit',     valueCode: 'slim-fit',     sortOrder: 1 },
      { name: 'Regular Fit',  valueCode: 'regular-fit',  sortOrder: 2 },
      { name: 'Relaxed Fit',  valueCode: 'relaxed-fit',  sortOrder: 3 },
      { name: 'Loose Fit',    valueCode: 'loose-fit',    sortOrder: 4 },
      { name: 'Oversized',    valueCode: 'oversized',    sortOrder: 5 },
      { name: 'Skinny Fit',   valueCode: 'skinny-fit',   sortOrder: 6 },
      { name: 'Straight Fit', valueCode: 'straight-fit', sortOrder: 7 },
      { name: 'Bootcut',      valueCode: 'bootcut',      sortOrder: 8 },
      { name: 'Tapered',      valueCode: 'tapered',      sortOrder: 9 },
      { name: 'Athletic Fit', valueCode: 'athletic-fit', sortOrder: 10 },
    ],
  },
  {
    name: 'Occasion',
    slug: 'occasion',
    displayType: 'dropdown',
    description: 'Suitable occasion / use',
    values: [
      { name: 'Casual',    valueCode: 'casual',    sortOrder: 1 },
      { name: 'Formal',    valueCode: 'formal',    sortOrder: 2 },
      { name: 'Party',     valueCode: 'party',     sortOrder: 3 },
      { name: 'Sports',    valueCode: 'sports',    sortOrder: 4 },
      { name: 'Ethnic',    valueCode: 'ethnic',    sortOrder: 5 },
      { name: 'Wedding',   valueCode: 'wedding',   sortOrder: 6 },
      { name: 'Festive',   valueCode: 'festive',   sortOrder: 7 },
      { name: 'Office',    valueCode: 'office',    sortOrder: 8 },
      { name: 'Beach',     valueCode: 'beach',     sortOrder: 9 },
      { name: 'Trekking',  valueCode: 'trekking',  sortOrder: 10 },
      { name: 'Lounge',    valueCode: 'lounge',    sortOrder: 11 },
    ],
  },
  {
    name: 'Pattern',
    slug: 'pattern',
    displayType: 'dropdown',
    description: 'Design pattern',
    values: [
      { name: 'Solid',          valueCode: 'solid',          sortOrder: 1 },
      { name: 'Striped',        valueCode: 'striped',        sortOrder: 2 },
      { name: 'Checked',        valueCode: 'checked',        sortOrder: 3 },
      { name: 'Printed',        valueCode: 'printed',        sortOrder: 4 },
      { name: 'Embroidered',    valueCode: 'embroidered',    sortOrder: 5 },
      { name: 'Floral',         valueCode: 'floral',         sortOrder: 6 },
      { name: 'Abstract',       valueCode: 'abstract',       sortOrder: 7 },
      { name: 'Geometric',      valueCode: 'geometric',      sortOrder: 8 },
      { name: 'Animal Print',   valueCode: 'animal-print',   sortOrder: 9 },
      { name: 'Camouflage',     valueCode: 'camouflage',     sortOrder: 10 },
      { name: 'Polka Dot',      valueCode: 'polka-dot',      sortOrder: 11 },
      { name: 'Tie-Dye',        valueCode: 'tie-dye',        sortOrder: 12 },
      { name: 'Ikat',           valueCode: 'ikat',           sortOrder: 13 },
      { name: 'Block Print',    valueCode: 'block-print',    sortOrder: 14 },
      { name: 'Batik',          valueCode: 'batik',          sortOrder: 15 },
      { name: 'Self Design',    valueCode: 'self-design',    sortOrder: 16 },
      { name: 'Colorblocked',   valueCode: 'colorblocked',   sortOrder: 17 },
      { name: 'Paisley',        valueCode: 'paisley',        sortOrder: 18 },
    ],
  },
  {
    name: 'Capacity',
    slug: 'capacity',
    displayType: 'dropdown',
    description: 'Container / appliance capacity',
    values: [
      { name: '100 ml',   valueCode: '100ml',  sortOrder: 1 },
      { name: '250 ml',   valueCode: '250ml',  sortOrder: 2 },
      { name: '500 ml',   valueCode: '500ml',  sortOrder: 3 },
      { name: '750 ml',   valueCode: '750ml',  sortOrder: 4 },
      { name: '1 Litre',  valueCode: '1l',     sortOrder: 5 },
      { name: '1.5 L',    valueCode: '1-5l',   sortOrder: 6 },
      { name: '2 Litres', valueCode: '2l',     sortOrder: 7 },
      { name: '3 Litres', valueCode: '3l',     sortOrder: 8 },
      { name: '5 Litres', valueCode: '5l',     sortOrder: 9 },
      { name: '6 Litres', valueCode: '6l',     sortOrder: 10 },
      { name: '8 Litres', valueCode: '8l',     sortOrder: 11 },
      { name: '10 L',     valueCode: '10l',    sortOrder: 12 },
      { name: '15 L',     valueCode: '15l',    sortOrder: 13 },
      { name: '20 L',     valueCode: '20l',    sortOrder: 14 },
      { name: '25 L',     valueCode: '25l',    sortOrder: 15 },
      { name: '50 L',     valueCode: '50l',    sortOrder: 16 },
      { name: '100 L',    valueCode: '100l',   sortOrder: 17 },
      { name: '200 L',    valueCode: '200l',   sortOrder: 18 },
      { name: '350 L',    valueCode: '350l',   sortOrder: 19 },
      { name: '500 L',    valueCode: '500l',   sortOrder: 20 },
    ],
  },
  {
    name: 'Pack Size',
    slug: 'pack-size',
    displayType: 'dropdown',
    description: 'Pack / combo quantity',
    values: [
      { name: '50g',       valueCode: '50g',     sortOrder: 1 },
      { name: '100g',      valueCode: '100g',    sortOrder: 2 },
      { name: '200g',      valueCode: '200g',    sortOrder: 3 },
      { name: '250g',      valueCode: '250g',    sortOrder: 4 },
      { name: '500g',      valueCode: '500g',    sortOrder: 5 },
      { name: '1 kg',      valueCode: '1kg',     sortOrder: 6 },
      { name: '2 kg',      valueCode: '2kg',     sortOrder: 7 },
      { name: '5 kg',      valueCode: '5kg',     sortOrder: 8 },
      { name: '10 kg',     valueCode: '10kg',    sortOrder: 9 },
      { name: 'Pack of 1', valueCode: 'pack-1',  sortOrder: 10 },
      { name: 'Pack of 2', valueCode: 'pack-2',  sortOrder: 11 },
      { name: 'Pack of 3', valueCode: 'pack-3',  sortOrder: 12 },
      { name: 'Pack of 5', valueCode: 'pack-5',  sortOrder: 13 },
      { name: 'Pack of 6', valueCode: 'pack-6',  sortOrder: 14 },
      { name: 'Pack of 10',valueCode: 'pack-10', sortOrder: 15 },
      { name: 'Pack of 12',valueCode: 'pack-12', sortOrder: 16 },
      { name: 'Pack of 24',valueCode: 'pack-24', sortOrder: 17 },
      { name: 'Set of 2',  valueCode: 'set-2',   sortOrder: 18 },
      { name: 'Set of 3',  valueCode: 'set-3',   sortOrder: 19 },
      { name: 'Set of 4',  valueCode: 'set-4',   sortOrder: 20 },
    ],
  },
  {
    name: 'Flavor',
    slug: 'flavor',
    displayType: 'dropdown',
    description: 'Food / beverage flavor',
    values: [
      { name: 'Unflavored',       valueCode: 'unflavored',       sortOrder: 1 },
      { name: 'Chocolate',        valueCode: 'chocolate',        sortOrder: 2 },
      { name: 'Vanilla',          valueCode: 'vanilla',          sortOrder: 3 },
      { name: 'Strawberry',       valueCode: 'strawberry',       sortOrder: 4 },
      { name: 'Mango',            valueCode: 'mango',            sortOrder: 5 },
      { name: 'Mixed Fruit',      valueCode: 'mixed-fruit',      sortOrder: 6 },
      { name: 'Butterscotch',     valueCode: 'butterscotch',     sortOrder: 7 },
      { name: 'Pineapple',        valueCode: 'pineapple',        sortOrder: 8 },
      { name: 'Orange',           valueCode: 'orange',           sortOrder: 9 },
      { name: 'Lemon',            valueCode: 'lemon',            sortOrder: 10 },
      { name: 'Mint',             valueCode: 'mint',             sortOrder: 11 },
      { name: 'Caramel',          valueCode: 'caramel',          sortOrder: 12 },
      { name: 'Honey',            valueCode: 'honey',            sortOrder: 13 },
      { name: 'Coffee',           valueCode: 'coffee',           sortOrder: 14 },
      { name: 'Masala',           valueCode: 'masala',           sortOrder: 15 },
      { name: 'Salt & Pepper',    valueCode: 'salt-pepper',      sortOrder: 16 },
      { name: 'Chilli',           valueCode: 'chilli',           sortOrder: 17 },
      { name: 'Cheese',           valueCode: 'cheese',           sortOrder: 18 },
      { name: 'Tomato',           valueCode: 'tomato',           sortOrder: 19 },
      { name: 'Peanut Butter',    valueCode: 'peanut-butter',    sortOrder: 20 },
    ],
  },
  {
    name: 'Warranty',
    slug: 'warranty',
    displayType: 'dropdown',
    description: 'Product warranty period',
    values: [
      { name: 'No Warranty',  valueCode: 'no-warranty', sortOrder: 1 },
      { name: '3 Months',     valueCode: '3-months',    sortOrder: 2 },
      { name: '6 Months',     valueCode: '6-months',    sortOrder: 3 },
      { name: '1 Year',       valueCode: '1-year',      sortOrder: 4 },
      { name: '2 Years',      valueCode: '2-years',     sortOrder: 5 },
      { name: '3 Years',      valueCode: '3-years',     sortOrder: 6 },
      { name: '5 Years',      valueCode: '5-years',     sortOrder: 7 },
      { name: 'Lifetime',     valueCode: 'lifetime',    sortOrder: 8 },
    ],
  },
  {
    name: 'Energy Rating',
    slug: 'energy-rating',
    displayType: 'radio',
    description: 'BEE energy efficiency star rating',
    values: [
      { name: '1 Star', valueCode: '1-star', sortOrder: 1 },
      { name: '2 Star', valueCode: '2-star', sortOrder: 2 },
      { name: '3 Star', valueCode: '3-star', sortOrder: 3 },
      { name: '4 Star', valueCode: '4-star', sortOrder: 4 },
      { name: '5 Star', valueCode: '5-star', sortOrder: 5 },
    ],
  },
  {
    name: 'Finish',
    slug: 'finish',
    displayType: 'dropdown',
    description: 'Furniture surface finish',
    values: [
      { name: 'Matte',         valueCode: 'matte',        sortOrder: 1 },
      { name: 'Glossy',        valueCode: 'glossy',       sortOrder: 2 },
      { name: 'Satin',         valueCode: 'satin',        sortOrder: 3 },
      { name: 'Walnut Finish', valueCode: 'walnut',       sortOrder: 4 },
      { name: 'Teak Finish',   valueCode: 'teak',         sortOrder: 5 },
      { name: 'Wenge Finish',  valueCode: 'wenge',        sortOrder: 6 },
      { name: 'Oak Finish',    valueCode: 'oak',          sortOrder: 7 },
      { name: 'Cherry Finish', valueCode: 'cherry',       sortOrder: 8 },
      { name: 'Pine Finish',   valueCode: 'pine',         sortOrder: 9 },
      { name: 'Mahogany',      valueCode: 'mahogany',     sortOrder: 10 },
      { name: 'Lacquered',     valueCode: 'lacquered',    sortOrder: 11 },
      { name: 'Powder Coated', valueCode: 'powder-coated',sortOrder: 12 },
      { name: 'Anodized',      valueCode: 'anodized',     sortOrder: 13 },
      { name: 'Natural',       valueCode: 'natural',      sortOrder: 14 },
    ],
  },
  {
    name: 'Metal Type',
    slug: 'metal-type',
    displayType: 'dropdown',
    description: 'Jewelry metal type',
    values: [
      { name: 'Gold 22K',       valueCode: 'gold-22k',      sortOrder: 1 },
      { name: 'Gold 18K',       valueCode: 'gold-18k',      sortOrder: 2 },
      { name: 'Gold 14K',       valueCode: 'gold-14k',      sortOrder: 3 },
      { name: 'Gold Plated',    valueCode: 'gold-plated',   sortOrder: 4 },
      { name: 'Silver 92.5%',   valueCode: 'silver-925',    sortOrder: 5 },
      { name: 'Silver Plated',  valueCode: 'silver-plated', sortOrder: 6 },
      { name: 'Platinum',       valueCode: 'platinum',      sortOrder: 7 },
      { name: 'Rose Gold',      valueCode: 'rose-gold',     sortOrder: 8 },
      { name: 'White Gold',     valueCode: 'white-gold',    sortOrder: 9 },
      { name: 'Stainless Steel',valueCode: 'stainless-steel',sortOrder: 10 },
      { name: 'Brass',          valueCode: 'brass',         sortOrder: 11 },
      { name: 'Copper',         valueCode: 'copper',        sortOrder: 12 },
      { name: 'Alloy',          valueCode: 'alloy',         sortOrder: 13 },
      { name: 'Oxidized Silver',valueCode: 'oxidized-silver',sortOrder: 14 },
    ],
  },
  {
    name: 'Stone Type',
    slug: 'stone-type',
    displayType: 'dropdown',
    description: 'Gemstone / stone in jewelry',
    values: [
      { name: 'Diamond',    valueCode: 'diamond',   sortOrder: 1 },
      { name: 'Ruby',       valueCode: 'ruby',      sortOrder: 2 },
      { name: 'Emerald',    valueCode: 'emerald',   sortOrder: 3 },
      { name: 'Sapphire',   valueCode: 'sapphire',  sortOrder: 4 },
      { name: 'Pearl',      valueCode: 'pearl',     sortOrder: 5 },
      { name: 'Topaz',      valueCode: 'topaz',     sortOrder: 6 },
      { name: 'Amethyst',   valueCode: 'amethyst',  sortOrder: 7 },
      { name: 'Garnet',     valueCode: 'garnet',    sortOrder: 8 },
      { name: 'Turquoise',  valueCode: 'turquoise', sortOrder: 9 },
      { name: 'Coral',      valueCode: 'coral',     sortOrder: 10 },
      { name: 'Opal',       valueCode: 'opal',      sortOrder: 11 },
      { name: 'Citrine',    valueCode: 'citrine',   sortOrder: 12 },
      { name: 'American Diamond', valueCode: 'american-diamond', sortOrder: 13 },
      { name: 'No Stone',   valueCode: 'no-stone',  sortOrder: 14 },
    ],
  },
  {
    name: 'Volume',
    slug: 'volume',
    displayType: 'dropdown',
    description: 'Liquid / cosmetic volume',
    values: [
      { name: '5 ml',   valueCode: '5ml',   sortOrder: 1 },
      { name: '10 ml',  valueCode: '10ml',  sortOrder: 2 },
      { name: '15 ml',  valueCode: '15ml',  sortOrder: 3 },
      { name: '20 ml',  valueCode: '20ml',  sortOrder: 4 },
      { name: '30 ml',  valueCode: '30ml',  sortOrder: 5 },
      { name: '50 ml',  valueCode: '50ml',  sortOrder: 6 },
      { name: '75 ml',  valueCode: '75ml',  sortOrder: 7 },
      { name: '100 ml', valueCode: '100ml', sortOrder: 8 },
      { name: '150 ml', valueCode: '150ml', sortOrder: 9 },
      { name: '200 ml', valueCode: '200ml', sortOrder: 10 },
      { name: '250 ml', valueCode: '250ml', sortOrder: 11 },
      { name: '300 ml', valueCode: '300ml', sortOrder: 12 },
      { name: '400 ml', valueCode: '400ml', sortOrder: 13 },
      { name: '500 ml', valueCode: '500ml', sortOrder: 14 },
      { name: '750 ml', valueCode: '750ml', sortOrder: 15 },
      { name: '1 Litre',valueCode: '1000ml',sortOrder: 16 },
    ],
  },
  {
    name: 'Processor',
    slug: 'processor',
    displayType: 'dropdown',
    description: 'CPU / chipset model',
    values: [
      { name: 'Intel Core i3 (13th Gen)',    valueCode: 'i3-13gen',  sortOrder: 1 },
      { name: 'Intel Core i5 (13th Gen)',    valueCode: 'i5-13gen',  sortOrder: 2 },
      { name: 'Intel Core i7 (13th Gen)',    valueCode: 'i7-13gen',  sortOrder: 3 },
      { name: 'Intel Core i9 (13th Gen)',    valueCode: 'i9-13gen',  sortOrder: 4 },
      { name: 'AMD Ryzen 3 (7000)',           valueCode: 'ryzen3-7k',  sortOrder: 5 },
      { name: 'AMD Ryzen 5 (7000)',           valueCode: 'ryzen5-7k',  sortOrder: 6 },
      { name: 'AMD Ryzen 7 (7000)',           valueCode: 'ryzen7-7k',  sortOrder: 7 },
      { name: 'AMD Ryzen 9 (7000)',           valueCode: 'ryzen9-7k',  sortOrder: 8 },
      { name: 'Apple M1',                    valueCode: 'apple-m1',   sortOrder: 9 },
      { name: 'Apple M2',                    valueCode: 'apple-m2',   sortOrder: 10 },
      { name: 'Apple M3',                    valueCode: 'apple-m3',   sortOrder: 11 },
      { name: 'Snapdragon 8 Gen 2',          valueCode: 'sd-8gen2',   sortOrder: 12 },
      { name: 'Snapdragon 8 Gen 3',          valueCode: 'sd-8gen3',   sortOrder: 13 },
      { name: 'MediaTek Dimensity 9200',     valueCode: 'mtk-9200',   sortOrder: 14 },
      { name: 'Exynos 2400',                 valueCode: 'exynos-2400',sortOrder: 15 },
      { name: 'Snapdragon 695',              valueCode: 'sd-695',     sortOrder: 16 },
      { name: 'MediaTek Helio G99',          valueCode: 'mtk-g99',    sortOrder: 17 },
    ],
  },
  {
    name: 'Operating System',
    slug: 'os',
    displayType: 'radio',
    description: 'Device operating system',
    values: [
      { name: 'Android 14', valueCode: 'android-14', sortOrder: 1 },
      { name: 'Android 13', valueCode: 'android-13', sortOrder: 2 },
      { name: 'iOS 17',     valueCode: 'ios-17',     sortOrder: 3 },
      { name: 'iOS 16',     valueCode: 'ios-16',     sortOrder: 4 },
      { name: 'Windows 11', valueCode: 'windows-11', sortOrder: 5 },
      { name: 'Windows 10', valueCode: 'windows-10', sortOrder: 6 },
      { name: 'macOS Sonoma',valueCode: 'macos-sonoma',sortOrder: 7 },
      { name: 'macOS Ventura',valueCode: 'macos-ventura',sortOrder: 8 },
      { name: 'Linux',      valueCode: 'linux',      sortOrder: 9 },
      { name: 'Chrome OS',  valueCode: 'chrome-os',  sortOrder: 10 },
      { name: 'HarmonyOS',  valueCode: 'harmonyos',  sortOrder: 11 },
    ],
  },
  {
    name: 'Gender',
    slug: 'gender',
    displayType: 'radio',
    description: 'Target gender',
    values: [
      { name: 'Men',     valueCode: 'men',     sortOrder: 1 },
      { name: 'Women',   valueCode: 'women',   sortOrder: 2 },
      { name: 'Unisex',  valueCode: 'unisex',  sortOrder: 3 },
      { name: 'Boys',    valueCode: 'boys',    sortOrder: 4 },
      { name: 'Girls',   valueCode: 'girls',   sortOrder: 5 },
      { name: 'Infant',  valueCode: 'infant',  sortOrder: 6 },
    ],
  },
  {
    name: 'Age Group',
    slug: 'age-group',
    displayType: 'dropdown',
    description: 'Target age group',
    values: [
      { name: 'Infant (0-12 months)',  valueCode: '0-12m',    sortOrder: 1 },
      { name: 'Toddler (1-3 years)',   valueCode: '1-3y',     sortOrder: 2 },
      { name: 'Kids (3-8 years)',      valueCode: '3-8y',     sortOrder: 3 },
      { name: 'Kids (8-12 years)',     valueCode: '8-12y',    sortOrder: 4 },
      { name: 'Teen (12-17 years)',    valueCode: '12-17y',   sortOrder: 5 },
      { name: 'Adult (18+ years)',     valueCode: '18plus',   sortOrder: 6 },
      { name: 'Senior (60+ years)',    valueCode: '60plus',   sortOrder: 7 },
    ],
  },
  {
    name: 'Sleeve Length',
    slug: 'sleeve-length',
    displayType: 'dropdown',
    description: 'Garment sleeve length',
    values: [
      { name: 'Full Sleeve',    valueCode: 'full-sleeve',    sortOrder: 1 },
      { name: 'Half Sleeve',    valueCode: 'half-sleeve',    sortOrder: 2 },
      { name: '3/4 Sleeve',     valueCode: '3-4-sleeve',     sortOrder: 3 },
      { name: 'Sleeveless',     valueCode: 'sleeveless',     sortOrder: 4 },
      { name: 'Cap Sleeve',     valueCode: 'cap-sleeve',     sortOrder: 5 },
      { name: 'Bell Sleeve',    valueCode: 'bell-sleeve',    sortOrder: 6 },
      { name: 'Flutter Sleeve', valueCode: 'flutter-sleeve', sortOrder: 7 },
      { name: 'Roll-Up Sleeve', valueCode: 'roll-up',        sortOrder: 8 },
    ],
  },
  {
    name: 'Neck / Collar',
    slug: 'neck-collar',
    displayType: 'dropdown',
    description: 'Neckline / collar style',
    values: [
      { name: 'Round Neck',    valueCode: 'round-neck',   sortOrder: 1 },
      { name: 'V-Neck',        valueCode: 'v-neck',       sortOrder: 2 },
      { name: 'Polo / Collar', valueCode: 'polo',         sortOrder: 3 },
      { name: 'Mandarin',      valueCode: 'mandarin',     sortOrder: 4 },
      { name: 'Hooded',        valueCode: 'hooded',       sortOrder: 5 },
      { name: 'Square Neck',   valueCode: 'square-neck',  sortOrder: 6 },
      { name: 'Off-Shoulder',  valueCode: 'off-shoulder', sortOrder: 7 },
      { name: 'Deep V',        valueCode: 'deep-v',       sortOrder: 8 },
      { name: 'Cowl Neck',     valueCode: 'cowl-neck',    sortOrder: 9 },
      { name: 'Turtle Neck',   valueCode: 'turtle-neck',  sortOrder: 10 },
    ],
  },
];

class OptionsSeed {
  constructor() {
    this.logger = new SeedLogger('Options');
    this.mongoose = mongoose;
  }

  async execute() {
    const conn = this.mongoose.connection;
    if (!conn || !conn.collection) throw new Error('MongoDB connection not available');

    const totalValues = OPTIONS.reduce((a, o) => a + o.values.length, 0);
    this.logger.info(`⚙️  Seeding Options — ${OPTIONS.length} options, ${totalValues} values`);

    await conn.collection('platformproductoptions').deleteMany({});
    await conn.collection('platformproductoptionvalues').deleteMany({});

    const optionDocs = [];
    const valueDocs = [];

    for (const opt of OPTIONS) {
      const optId = new mongoose.Types.ObjectId();
      optionDocs.push({
        _id: optId,
        name: opt.name,
        slug: opt.slug,
        displayType: opt.displayType,
        description: opt.description,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      });

      for (const val of opt.values) {
        valueDocs.push({
          _id: new mongoose.Types.ObjectId(),
          optionId: optId.toString(),
          option_id: optId.toString(),
          name: val.name,
          optionName: opt.name,
          valueCode: val.valueCode,
          colorHex: val.colorHex || '',
          imageUrl: '',
          sortOrder: val.sortOrder,
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        });
      }
    }

    await conn.collection('platformproductoptions').insertMany(optionDocs);
    this.logger.recordBatch(optionDocs.length);

    const BATCH = 200;
    for (let i = 0; i < valueDocs.length; i += BATCH) {
      await conn.collection('platformproductoptionvalues').insertMany(valueDocs.slice(i, i + BATCH));
    }
    this.logger.recordBatch(valueDocs.length);

    this.logger.printStats();
    return { created: optionDocs.length + valueDocs.length, options: optionDocs.length, values: valueDocs.length };
  }
}

module.exports = OptionsSeed;
