const { mongoose } = require("../../../infrastructure/mongo/mongo-client");

const returnItemSchema = new mongoose.Schema(
  {
    orderItemId: String,
    productId: String,
    productTitle: String,
    productSku: String,
    productImage: String,
    sellerId: { type: String, index: true },
    variantId: String,
    variantSku: String,
    quantity: Number,
    requestedQuantity: Number,
    approvedQuantity: Number,
    receivedQuantity: Number,
    unitPrice: Number,
    lineTotal: Number,
    taxAmount: { type: Number, default: 0 },
    eligibleRefundAmount: { type: Number, default: 0 },
    refundAmount: { type: Number, default: 0 },
    condition: String,
    qcResult: {
      type: String,
      enum: ["pending", "sellable", "damaged", "missing", "rejected"],
      default: "pending",
    },
    qcNotes: String,
    qcPhotos: [String],
    restockedQuantity: { type: Number, default: 0 },
    damagedQuantity: { type: Number, default: 0 },
    photos: [String],
  },
  { _id: false },
);

const shipmentEventSchema = new mongoose.Schema(
  {
    status: String,
    location: String,
    note: String,
    source: String,
    rawPayload: { type: Object, default: {} },
    actorId: String,
    at: { type: Date, default: Date.now },
  },
  { _id: false },
);

const refundAttemptSchema = new mongoose.Schema(
  {
    attemptId: String,
    idempotencyKey: String,
    method: String,
    provider: String,
    amount: Number,
    walletAmount: Number,
    providerAmount: Number,
    providerRefundId: String,
    status: String,
    failureReason: String,
    metadata: { type: Object, default: {} },
    actorId: String,
    startedAt: Date,
    completedAt: Date,
  },
  { _id: false },
);

const returnSchema = new mongoose.Schema(
  {
    returnNumber: { type: String, index: true, unique: true, sparse: true },
    orderId: { type: String, required: true, index: true },
    buyerId: { type: String, required: true, index: true },
    sellerId: { type: String, index: true },
    reason: {
      type: String,
      enum: [
        "defective",
        "damaged_in_transit",
        "wrong_item",
        "missing_parts",
        "size_issue",
        "quality_issue",
        "not_as_described",
        "changed_mind",
        "other",
      ],
      required: true,
    },
    resolution: {
      type: String,
      enum: ["refund", "replacement", "exchange", "store_credit"],
      default: "refund",
    },
    description: String,
    items: [returnItemSchema],
    status: {
      type: String,
      enum: [
        "requested",
        "approved",
        "rejected",
        "reverse_pickup_scheduled",
        "pickup_failed",
        "manual_ship_back",
        "shipped_back",
        "in_reverse_transit",
        "received",
        "qc_passed",
        "qc_failed",
        "qc_completed",
        "refund_pending",
        "refund_failed",
        "partially_refunded",
        "refunded",
        "replacement_pending",
        "replaced",
        "closed",
      ],
      default: "requested",
      index: true,
    },
    refundAmount: Number,
    refundBreakup: { type: Object, default: {} },
    refundReferenceId: String,
    refundMethod: String,
    providerRefundId: String,
    trackingNumber: String,
    replacementOrderId: String,
    replacementShipmentId: String,
    policySnapshot: {
      returnable: { type: Boolean, default: true },
      returnWindowDays: Number,
      deliveredAt: Date,
      eligibleUntil: Date,
      shippingPaidBy: String,
      requiresQc: { type: Boolean, default: true },
      source: String,
    },
    buyerSnapshot: { type: Object, default: {} },
    shipFromSnapshot: { type: Object, default: {} },
    shipToSnapshot: { type: Object, default: {} },
    reverseShipment: {
      shipmentId: String,
      provider: String,
      courierName: String,
      awbNumber: String,
      trackingNumber: String,
      labelUrl: String,
      status: String,
      pickupScheduledAt: Date,
      pickedUpAt: Date,
      deliveredToWarehouseAt: Date,
      packageSnapshot: { type: Object, default: {} },
      pickupAddressSnapshot: { type: Object, default: {} },
      warehouseAddressSnapshot: { type: Object, default: {} },
      rateSnapshot: { type: Object, default: {} },
      cost: Number,
      events: [shipmentEventSchema],
      metadata: { type: Object, default: {} },
    },
    refund: {
      status: {
        type: String,
        enum: ["not_started", "pending", "provider_pending", "completed", "failed", "manual_review"],
        default: "not_started",
      },
      requestedAmount: Number,
      approvedAmount: Number,
      refundedAmount: { type: Number, default: 0 },
      walletAmount: { type: Number, default: 0 },
      providerAmount: { type: Number, default: 0 },
      method: String,
      provider: String,
      providerRefundId: String,
      referenceId: String,
      idempotencyKey: String,
      failureReason: String,
      attempts: [refundAttemptSchema],
      processedAt: Date,
      metadata: { type: Object, default: {} },
    },
    replacement: {
      status: String,
      orderId: String,
      shipmentId: String,
      trackingNumber: String,
      createdAt: Date,
      deliveredAt: Date,
      metadata: { type: Object, default: {} },
    },
    timeline: [
      {
        status: String,
        actorId: String,
        actorRole: String,
        reason: String,
        note: String,
        metadata: { type: Object, default: {} },
        at: { type: Date, default: Date.now },
      },
    ],
    photos: [String],
    requestedAt: { type: Date, default: Date.now },
    approvedAt: Date,
    rejectedAt: Date,
    receivedAt: Date,
    qcAt: Date,
    refundedAt: Date,
    closedAt: Date,
    lastError: String,
    retryCount: { type: Number, default: 0 },
    notes: String,
    createdBy: { type: String, index: true },
    updatedBy: { type: String, index: true },
  },
  { timestamps: true },
);

const ReturnModel = mongoose.model("Return", returnSchema);

module.exports = { ReturnModel };
